// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tor.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.TargetPlayer


/**
 * Mind Sludge
 * {4}{B}
 * Sorcery
 * Target player discards a card for each Swamp you control.
 */
val MindSludge = card("Mind Sludge") {
    manaCost = "{4}{B}"
    colorIdentity = "B"
    typeLine = "Sorcery"
    oracleText = "Target player discards a card for each Swamp you control."
    spell {
        val t = target("target", TargetPlayer())
        effect = Patterns.Hand.discardCards(1, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "70"
        artist = "Eric Peterson"
        flavorText = "When you get into the swamp, the swamp gets into you."
        imageUri = "https://cards.scryfall.io/normal/front/3/4/34bf3c19-f148-4542-8505-604191fd5a02.jpg"
    }
}
