// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.CounterEffect
import com.wingedsheep.sdk.scripting.targets.TargetSpell


/**
 * Daring Apprentice
 * {1}{U}{U}
 * Creature — Human Wizard
 * 1/1
 * {T}, Sacrifice this creature: Counter target spell.
 */
val DaringApprentice = card("Daring Apprentice") {
    manaCost = "{1}{U}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Human Wizard"
    oracleText = "{T}, Sacrifice this creature: Counter target spell."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Composite(Costs.Tap, Costs.SacrificeSelf)
        val t = target("target", TargetSpell())
        effect = CounterEffect()
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "60"
        artist = "Kaja Foglio"
        flavorText = "In front of every great wizard is a doomed apprentice."
        imageUri = "https://cards.scryfall.io/normal/front/f/8/f87b3c06-5479-4060-8d3a-d161fd5830c1.jpg"
    }
}
