package com.wingedsheep.engine.core

import com.wingedsheep.engine.state.Component
import com.wingedsheep.engine.state.components.battlefield.*
import com.wingedsheep.engine.state.components.combat.*
import com.wingedsheep.engine.state.components.identity.*
import com.wingedsheep.engine.state.components.player.*
import com.wingedsheep.engine.state.components.stack.*
import com.wingedsheep.engine.mechanics.layers.ContinuousEffectSourceComponent
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/**
 * Serializers module for all engine types that require polymorphic serialization.
 *
 * This module must be registered with Json instances that need to serialize/deserialize
 * GameAction, GameEvent, and other polymorphic types from the engine.
 *
 * Usage:
 * ```kotlin
 * val json = Json {
 *     serializersModule = engineSerializersModule
 * }
 * ```
 */
val engineSerializersModule = SerializersModule {
    // GameAction hierarchy
    polymorphic(GameAction::class) {
        subclass(PassPriority::class)
        subclass(CastSpell::class)
        subclass(ActivateAbility::class)
        subclass(PlayLand::class)
        subclass(DeclareAttackers::class)
        subclass(DeclareBlockers::class)
        subclass(OrderBlockers::class)
        subclass(ChooseManaColor::class)
        subclass(SubmitDecision::class)
        subclass(TakeMulligan::class)
        subclass(KeepHand::class)
        subclass(BottomCards::class)
        subclass(Concede::class)
        subclass(CrewVehicle::class)
        subclass(CycleCard::class)
        subclass(TurnFaceUp::class)
        subclass(TypecycleCard::class)
    }

    // GameEvent hierarchy
    polymorphic(GameEvent::class) {
        subclass(ZoneChangeEvent::class)
        subclass(LifeChangedEvent::class)
        subclass(DamageDealtEvent::class)
        subclass(SpellCastEvent::class)
        subclass(AbilityActivatedEvent::class)
        subclass(AbilityTriggeredEvent::class)
        subclass(ResolvedEvent::class)
        subclass(SpellCounteredEvent::class)
        subclass(SpellFizzledEvent::class)
        subclass(AbilityResolvedEvent::class)
        subclass(AbilityFizzledEvent::class)
        subclass(AttackersDeclaredEvent::class)
        subclass(BlockersDeclaredEvent::class)
        subclass(BlockerOrderDeclaredEvent::class)
        subclass(AttackerOrderDeclaredEvent::class)
        subclass(DamageAssignedEvent::class)
        subclass(PhaseChangedEvent::class)
        subclass(StepChangedEvent::class)
        subclass(TurnChangedEvent::class)
        subclass(PriorityChangedEvent::class)
        subclass(TappedEvent::class)
        subclass(UntappedEvent::class)
        subclass(CountersAddedEvent::class)
        subclass(CountersRemovedEvent::class)
        subclass(CardsDrawnEvent::class)
        subclass(CardRevealedFromDrawEvent::class)
        subclass(DrawFailedEvent::class)
        subclass(CardsDiscardedEvent::class)
        subclass(DiscardRequiredEvent::class)
        subclass(LibraryShuffledEvent::class)
        subclass(DecisionRequestedEvent::class)
        subclass(DecisionSubmittedEvent::class)
        subclass(GameEndedEvent::class)
        subclass(PlayerLostEvent::class)
        subclass(CreatureDestroyedEvent::class)
        subclass(ManaAddedEvent::class)
        subclass(ManaSpentEvent::class)
        subclass(AbilityCounteredEvent::class)
        subclass(BecomesTargetEvent::class)
        subclass(CardCycledEvent::class)
        subclass(CardsRevealedEvent::class)
        subclass(ClassLevelChangedEvent::class)
        subclass(CoinFlipEvent::class)
        subclass(ControlChangedEvent::class)
        subclass(CreatureTypeChangedEvent::class)
        subclass(CreatureTypeChosenEvent::class)
        subclass(GiftGivenEvent::class)
        subclass(HandLookedAtEvent::class)
        subclass(HandRevealedEvent::class)
        subclass(KeywordGrantedEvent::class)
        subclass(LibraryReorderedEvent::class)
        subclass(LookedAtCardsEvent::class)
        subclass(LoyaltyChangedEvent::class)
        subclass(PermanentsSacrificedEvent::class)
        subclass(StatsModifiedEvent::class)
        subclass(TargetReselectedEvent::class)
        subclass(TurnFaceUpEvent::class)
        subclass(TurnedFaceDownEvent::class)
    }

    // PendingDecision hierarchy
    polymorphic(PendingDecision::class) {
        subclass(ChooseTargetsDecision::class)
        subclass(SelectCardsDecision::class)
        subclass(YesNoDecision::class)
        subclass(ChooseModeDecision::class)
        subclass(ChooseColorDecision::class)
        subclass(ChooseNumberDecision::class)
        subclass(DistributeDecision::class)
        subclass(OrderObjectsDecision::class)
        subclass(SplitPilesDecision::class)
        subclass(ChooseOptionDecision::class)
        subclass(BudgetModalDecision::class)
        subclass(AssignDamageDecision::class)
        subclass(SearchLibraryDecision::class)
        subclass(ReorderLibraryDecision::class)
        subclass(SelectManaSourcesDecision::class)
    }

    // DecisionResponse hierarchy
    polymorphic(DecisionResponse::class) {
        subclass(TargetsResponse::class)
        subclass(CardsSelectedResponse::class)
        subclass(YesNoResponse::class)
        subclass(ModesChosenResponse::class)
        subclass(ColorChosenResponse::class)
        subclass(NumberChosenResponse::class)
        subclass(DistributionResponse::class)
        subclass(OrderedResponse::class)
        subclass(PilesSplitResponse::class)
        subclass(OptionChosenResponse::class)
        subclass(BudgetModalResponse::class)
        subclass(DamageAssignmentResponse::class)
        subclass(CancelDecisionResponse::class)
        subclass(ManaSourcesSelectedResponse::class)
    }

    // ContinuationFrame hierarchy
    polymorphic(ContinuationFrame::class) {
        subclass(EffectContinuation::class)
        subclass(TriggeredAbilityContinuation::class)
        subclass(TriggerDamageDistributionContinuation::class)
        subclass(DamageAssignmentContinuation::class)
        subclass(ResolveSpellContinuation::class)
        subclass(SacrificeContinuation::class)
        subclass(ReturnToHandContinuation::class)
        subclass(ExileMultiZoneContinuation::class)
        subclass(MayAbilityContinuation::class)
        subclass(HandSizeDiscardContinuation::class)
        subclass(LegendRuleContinuation::class)
        subclass(BlockerOrderContinuation::class)
        subclass(AttackerOrderContinuation::class)
        subclass(PayOrSufferContinuation::class)
        subclass(PayOrSufferChoiceContinuation::class)
        subclass(ChooseColorProtectionContinuation::class)
        subclass(ChooseColorProtectionTargetContinuation::class)
        subclass(ChooseFromCreatureTypeContinuation::class)
        subclass(ChooseToCreatureTypeContinuation::class)
        subclass(PutFromHandContinuation::class)
        subclass(UntapChoiceContinuation::class)
        subclass(PendingTriggersContinuation::class)
        subclass(BecomeCreatureTypeContinuation::class)
        subclass(CounterUnlessPaysContinuation::class)
        subclass(ModalContinuation::class)
        subclass(ModalTargetContinuation::class)
        subclass(CloneEntersContinuation::class)
        subclass(EntersWithChoiceSpellContinuation::class)
        subclass(EntersWithChoiceLandContinuation::class)
        subclass(PayLifeOrEnterTappedLandContinuation::class)
        subclass(PayLifeOrEnterTappedSpellContinuation::class)
        subclass(RevealCountersContinuation::class)
        subclass(CastWithCreatureTypeContinuation::class)
        subclass(MoveCollectionAuraTargetContinuation::class)
        subclass(ChainCopyAfterActionContinuation::class)
        subclass(ChainCopyDecisionContinuation::class)
        subclass(ChainCopyCostContinuation::class)
        subclass(ChainCopyTargetContinuation::class)
        subclass(DamagePreventionContinuation::class)
        subclass(EachPlayerChoosesCreatureTypeContinuation::class)
        subclass(ChangeSpellTargetContinuation::class)
        subclass(SecretBidContinuation::class)
        subclass(DrawReplacementRemainingDrawsContinuation::class)
        subclass(DrawReplacementActivationContinuation::class)
        subclass(DrawReplacementTargetContinuation::class)
        subclass(ReadTheRunesContinuation::class)
        subclass(ForEachTargetContinuation::class)
        subclass(ForEachPlayerContinuation::class)
        subclass(DrawUpToContinuation::class)
        subclass(RepeatWhileContinuation::class)
        subclass(SelectFromCollectionContinuation::class)
        subclass(MoveCollectionOrderContinuation::class)
        subclass(ChooseOptionPipelineContinuation::class)
        subclass(SelectTargetPipelineContinuation::class)
        subclass(CycleDrawContinuation::class)
        subclass(TypecycleSearchContinuation::class)
        subclass(DistributeCountersContinuation::class)
        subclass(StormCopyTargetContinuation::class)
        subclass(DeflectDamageSourceChoiceContinuation::class)
        subclass(PreventDamageFromChosenSourceContinuation::class)
        subclass(AddDynamicManaContinuation::class)
        subclass(AssignAsUnblockedContinuation::class)
        subclass(BudgetModalContinuation::class)
        subclass(PutOnTopOrBottomContinuation::class)
        subclass(AnyPlayerMayPayContinuation::class)
        subclass(ChooseActionContinuation::class)
        subclass(CounterUnlessPaysManaSelectionContinuation::class)
        subclass(CreateTokenCopyOfChosenContinuation::class)
        subclass(DistributeDamageContinuation::class)
        subclass(EachPlayerDiscardsOrLoseLifeContinuation::class)
        subclass(ManaSourceSelectionContinuation::class)
        subclass(MayPayManaContinuation::class)
        subclass(MayPayManaSelectionContinuation::class)
        subclass(MayPayManaTriggerContinuation::class)
        subclass(MayPayXContinuation::class)
        subclass(MayTriggerContinuation::class)
        subclass(PutOnBottomOfLibraryContinuation::class)
        subclass(ReflexiveTriggerResolveContinuation::class)
        subclass(ReflexiveTriggerTargetContinuation::class)
        subclass(ReturnFromGraveyardContinuation::class)
        subclass(ReturnFromLinkedExileContinuation::class)
        subclass(StaticDrawReplacementContinuation::class)
    }

    // Component hierarchy (for GameState persistence)
    polymorphic(Component::class) {
        // Identity components
        subclass(CardComponent::class)
        subclass(OwnerComponent::class)
        subclass(ControllerComponent::class)
        subclass(PlayerComponent::class)
        subclass(LifeTotalComponent::class)
        subclass(TokenComponent::class)
        subclass(FaceDownComponent::class)
        subclass(RevealedToComponent::class)
        subclass(MorphDataComponent::class)
        subclass(TextReplacementComponent::class)
        subclass(ProtectionComponent::class)
        subclass(HexproofFromColorComponent::class)
        subclass(CopyOfComponent::class)
        subclass(ChosenColorComponent::class)
        subclass(ChosenCreatureTypeComponent::class)
        subclass(CantBeCounteredComponent::class)
        subclass(ChosenCreatureComponent::class)
        subclass(ExileAfterResolveComponent::class)
        subclass(HasMorphAbilityComponent::class)
        subclass(MayPlayFromExileComponent::class)
        subclass(PlayWithAdditionalCostComponent::class)
        subclass(PlayWithoutPayingCostComponent::class)
        subclass(WarpExiledComponent::class)

        // Battlefield components
        subclass(TappedComponent::class)
        subclass(SummoningSicknessComponent::class)
        subclass(CastFromHandComponent::class)
        subclass(CountersComponent::class)
        subclass(DamageComponent::class)
        subclass(AttachedToComponent::class)
        subclass(AttachmentsComponent::class)
        subclass(EnteredThisTurnComponent::class)
        subclass(WasDealtDamageThisTurnComponent::class)
        subclass(HasDealtDamageComponent::class)
        subclass(HasDealtCombatDamageToPlayerComponent::class)
        subclass(TimestampComponent::class)
        subclass(AbilityActivatedEverComponent::class)
        subclass(AbilityActivatedThisTurnComponent::class)
        subclass(AbilityResolutionCountThisTurnComponent::class)
        subclass(CantBeTargetedByOpponentAbilitiesComponent::class)
        subclass(ClassLevelComponent::class)
        subclass(DamageDealtToCreaturesThisTurnComponent::class)
        subclass(ExileOnLeaveBattlefieldComponent::class)
        subclass(GrantCantBeBlockedToSmallCreaturesComponent::class)
        subclass(GrantsCantLoseGameComponent::class)
        subclass(GrantsControllerHexproofComponent::class)
        subclass(GrantsControllerShroudComponent::class)
        subclass(GraveyardEntryTurnComponent::class)
        subclass(GraveyardPlayPermissionUsedComponent::class)
        subclass(LinkedExileComponent::class)
        subclass(ReplacementEffectSourceComponent::class)
        subclass(SagaComponent::class)
        subclass(TargetedByControllerThisTurnComponent::class)
        subclass(TriggeredAbilityFiredThisTurnComponent::class)
        subclass(WarpedComponent::class)
        subclass(WasKickedComponent::class)

        // Combat components
        subclass(AttackingComponent::class)
        subclass(BlockingComponent::class)
        subclass(BlockedComponent::class)
        subclass(DamageAssignmentComponent::class)
        subclass(DamageAssignmentOrderComponent::class)
        subclass(AttackerOrderComponent::class)
        subclass(DealtFirstStrikeDamageComponent::class)
        subclass(RequiresManualDamageAssignmentComponent::class)
        subclass(AttackersDeclaredThisCombatComponent::class)
        subclass(BlockersDeclaredThisCombatComponent::class)
        subclass(MustAttackPlayerComponent::class)
        subclass(MustAttackThisTurnComponent::class)
        subclass(PlayerAttackedThisTurnComponent::class)

        // Player components
        subclass(ManaPoolComponent::class)
        subclass(LandDropsComponent::class)
        subclass(MulliganStateComponent::class)
        subclass(SkipCombatPhasesComponent::class)
        subclass(SkipUntapComponent::class)
        subclass(PlayerLostComponent::class)
        subclass(LoseAtEndStepComponent::class)
        subclass(CardsDrawnThisTurnComponent::class)
        subclass(WasDealtCombatDamageThisTurnComponent::class)
        subclass(AdditionalCombatPhasesComponent::class)
        subclass(CantCastSpellsComponent::class)
        subclass(CardsLeftGraveyardThisTurnComponent::class)
        subclass(CreaturesDiedThisTurnComponent::class)
        subclass(DamageBonusComponent::class)
        subclass(DamageReceivedThisTurnComponent::class)
        subclass(GrantedSpellKeywordsComponent::class)
        subclass(LifeGainedThisTurnComponent::class)
        subclass(LifeLostThisTurnComponent::class)
        subclass(ManaSpentOnSpellsThisTurnComponent::class)
        subclass(MayCastCreaturesFromGraveyardWithForageComponent::class)
        subclass(NonTokenCreaturesDiedThisTurnComponent::class)
        subclass(OpponentCreaturesExiledThisTurnComponent::class)
        subclass(PlayerHexproofComponent::class)
        subclass(PlayerShroudComponent::class)
        subclass(SacrificedFoodThisTurnComponent::class)
        subclass(SkipNextTurnComponent::class)

        // Stack components
        subclass(SpellOnStackComponent::class)
        subclass(TriggeredAbilityOnStackComponent::class)
        subclass(ActivatedAbilityOnStackComponent::class)
        subclass(AbilityOnStackComponent::class)
        subclass(TargetsComponent::class)
        subclass(SpellContextComponent::class)

        // Continuous effects
        subclass(ContinuousEffectSourceComponent::class)
    }
}
