// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dsk.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Bear Trap
 * {1}
 * Artifact
 * Flash
 * {3}, {T}, Sacrifice this artifact: It deals 3 damage to target creature.
 */
val BearTrap = card("Bear Trap") {
    manaCost = "{1}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "Flash\n{3}, {T}, Sacrifice this artifact: It deals 3 damage to target creature."
    keywords(Keyword.FLASH)
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{3}"), Costs.Tap, Costs.SacrificeSelf)
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = DealDamageEffect(3, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "243"
        artist = "Michele Giorgi"
        flavorText = "Every time its teeth tasted blood, its hunger grew, until one day it was no longer a trap but a hunter."
        imageUri = "https://cards.scryfall.io/normal/front/e/2/e27c27d6-dc3a-4420-bb35-d97dc216e002.jpg"
    }
}
