// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dsk.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Emerge from the Cocoon
 * {4}{W}
 * Sorcery
 * Return target creature card from your graveyard to the battlefield. You gain 3 life.
 */
val EmergeFromTheCocoon = card("Emerge from the Cocoon") {
    manaCost = "{4}{W}"
    colorIdentity = "W"
    typeLine = "Sorcery"
    oracleText = "Return target creature card from your graveyard to the battlefield. You gain 3 life."
    spell {
        val t = target("target", TargetObject(filter = TargetFilter.CreatureInYourGraveyard))
        effect = Effects.Composite(
            Effects.Move(t, Zone.BATTLEFIELD),
            GainLifeEffect(3)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "5"
        artist = "Marta Nael"
        flavorText = "Within the silken shroud, all doubts are cleansed, and all desires are united with Valgavoth."
        imageUri = "https://cards.scryfall.io/normal/front/3/b/3ba16fbf-2d44-4337-87cb-6ff6b84a258a.jpg"
    }
}
