// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dsk.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Final Vengeance
 * {B}
 * Sorcery
 * As an additional cost to cast this spell, sacrifice a creature or enchantment.
 * Exile target creature.
 */
val FinalVengeance = card("Final Vengeance") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Sorcery"
    oracleText = "As an additional cost to cast this spell, sacrifice a creature or enchantment.\nExile target creature."
    additionalCost(Costs.additional.SacrificePermanent(GameObjectFilter.CreatureOrEnchantment))
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Exile(t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "99"
        artist = "David Szabo"
        flavorText = "The cries of survivor and cellarspawn mingled in a single, terrible roar as they plunged into the fathomless depths."
        imageUri = "https://cards.scryfall.io/normal/front/6/4/648da934-71f6-4945-a08f-09698414417b.jpg"
    }
}
