// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dsk.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GrantKeyword
import com.wingedsheep.sdk.scripting.ModifyStats


/**
 * Frantic Strength
 * {2}{G}
 * Enchantment — Aura
 * Flash
 * Enchant creature
 * Enchanted creature gets +2/+2 and has trample.
 */
val FranticStrength = card("Frantic Strength") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Enchantment — Aura"
    oracleText = "Flash\nEnchant creature\nEnchanted creature gets +2/+2 and has trample."
    keywords(Keyword.FLASH)
    auraTarget = Targets.Creature
    staticAbility {
        ability = ModifyStats(2, 2)
    }
    staticAbility {
        ability = GrantKeyword(Keyword.TRAMPLE)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "179"
        artist = "Flavio Greco Paglia"
        flavorText = "With his friends dead and his weapons broken, Taros seized the only thing he could to defend himself."
        imageUri = "https://cards.scryfall.io/normal/front/b/b/bbd9d35d-7fd0-4193-9f7e-b8a59fae4ac5.jpg"
    }
}
