// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dsk.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Wary Watchdog
 * {1}{G}
 * Creature — Dog
 * 3/1
 * When this creature enters or dies, surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
 */
val WaryWatchdog = card("Wary Watchdog") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Dog"
    oracleText = "When this creature enters or dies, surveil 1. (Look at the top card of your library. You may put it into your graveyard.)"
    power = 3
    toughness = 1
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Patterns.Library.surveil(1)
    }
    triggeredAbility {
        trigger = Triggers.Dies
        effect = Patterns.Library.surveil(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "206"
        artist = "Olivier Bernard"
        flavorText = "Valgavoth harbors a special loathing for dogs, whose mere presence provides a powerful antidote to the fear he craves."
        imageUri = "https://cards.scryfall.io/normal/front/2/5/25ed97f2-b47e-49b7-9b1a-694c4bbeca3b.jpg"
    }
}
