// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lci.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Acolyte of Aclazotz
 * {2}{B}
 * Creature — Vampire Cleric
 * 1/4
 * {T}, Sacrifice another creature or artifact: Each opponent loses 1 life and you gain 1 life.
 */
val AcolyteOfAclazotz = card("Acolyte of Aclazotz") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Vampire Cleric"
    oracleText = "{T}, Sacrifice another creature or artifact: Each opponent loses 1 life and you gain 1 life."
    power = 1
    toughness = 4
    activatedAbility {
        cost = Costs.Composite(Costs.Tap, Costs.SacrificeAnother(GameObjectFilter.CreatureOrArtifact))
        effect = Effects.Composite(
            Effects.LoseLife(1, EffectTarget.PlayerRef(Player.EachOpponent)),
            GainLifeEffect(1)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "89"
        artist = "Irina Nordsol"
        flavorText = "\"Great Aclazotz, receive this offering. Wrought with skill. Captured with strength. Anointed with the blood of your enemies.\""
        imageUri = "https://cards.scryfall.io/normal/front/9/9/99009400-ffa4-40af-8305-78295ae605ac.jpg"
    }
}
