// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lci.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Bartolomé del Presidio
 * {W}{B}
 * Legendary Creature — Vampire Knight
 * 2/1
 * Sacrifice another creature or artifact: Put a +1/+1 counter on Bartolomé del Presidio.
 */
val BartolomeDelPresidio = card("Bartolomé del Presidio") {
    manaCost = "{W}{B}"
    colorIdentity = "WB"
    typeLine = "Legendary Creature — Vampire Knight"
    oracleText = "Sacrifice another creature or artifact: Put a +1/+1 counter on Bartolomé del Presidio."
    power = 2
    toughness = 1
    activatedAbility {
        cost = Costs.SacrificeAnother(GameObjectFilter.CreatureOrArtifact)
        effect = AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "224"
        artist = "Randy Gallegos"
        flavorText = "\"Bless this sinner, who sacrificed his blood so that I may live.\""
        imageUri = "https://cards.scryfall.io/normal/front/6/9/690ccdc7-6c43-4902-9d11-2f07b7a36b11.jpg"
    }
}
