// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lci.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Cogwork Wrestler
 * {U}
 * Artifact Creature — Gnome
 * 1/2
 * Flash
 * When this creature enters, target creature an opponent controls gets -2/-0 until end of turn.
 */
val CogworkWrestler = card("Cogwork Wrestler") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Artifact Creature — Gnome"
    oracleText = "Flash\nWhen this creature enters, target creature an opponent controls gets -2/-0 until end of turn."
    power = 1
    toughness = 2
    keywords(Keyword.FLASH)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.opponentControls()))
        effect = Effects.ModifyStats(-2, 0, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "49"
        artist = "Tomek Larek"
        flavorText = "Years of adventure and adversity on the open seas did not prepare Brog for the humiliation of losing a sparring match to a cogwork doll less than half his size."
        imageUri = "https://cards.scryfall.io/normal/front/a/9/a9d329ad-6b19-4aa7-a53f-38c7b76c4c96.jpg"
    }
}
