// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lci.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Colossadactyl
 * {2}{G}{G}
 * Creature — Dinosaur
 * 4/5
 * Reach, trample
 */
val Colossadactyl = card("Colossadactyl") {
    manaCost = "{2}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Dinosaur"
    oracleText = "Reach, trample"
    power = 4
    toughness = 5
    keywords(Keyword.REACH, Keyword.TRAMPLE)
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "180"
        artist = "Campbell White"
        flavorText = "Accustomed to hunting nimble flying prey, the dinosaur was delighted to have its meal delivered neatly in a box."
        imageUri = "https://cards.scryfall.io/normal/front/8/7/8702e776-be2c-48a9-9bc5-bb8ea514333b.jpg"
    }
}
