// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lci.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.effects.WardCost
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Dusk Rose Reliquary
 * {W}
 * Artifact
 * As an additional cost to cast this spell, sacrifice an artifact or creature.
 * Ward {2}
 * When this artifact enters, exile target artifact or creature an opponent controls until this artifact leaves the battlefield.
 */
val DuskRoseReliquary = card("Dusk Rose Reliquary") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Artifact"
    oracleText = "As an additional cost to cast this spell, sacrifice an artifact or creature.\nWard {2}\nWhen this artifact enters, exile target artifact or creature an opponent controls until this artifact leaves the battlefield."
    additionalCost(Costs.additional.SacrificePermanent(GameObjectFilter.CreatureOrArtifact))
    keywordAbility(KeywordAbility.Ward(WardCost.Mana("{2}")))
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target(
            "target",
            TargetPermanent(filter = TargetFilter(GameObjectFilter.CreatureOrArtifact.opponentControls()))
        )
        effect = Effects.ExileUntilLeaves(t)
    }
    triggeredAbility {
        trigger = Triggers.LeavesBattlefield
        effect = Effects.ReturnLinkedExileUnderOwnersControl()
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "10"
        artist = "Samuel Araya"
        imageUri = "https://cards.scryfall.io/normal/front/a/5/a5f231ef-4167-4b0a-b54c-a098b2eb2f6f.jpg"
    }
}
