// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lci.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Greedy Freebooter
 * {B}
 * Creature — Human Pirate
 * 1/1
 * When this creature dies, scry 1 and create a Treasure token. (To scry 1, look at the top card of your library. You may put that card on the bottom. A Treasure token is an artifact with "{T}, Sacrifice this token: Add one mana of any color.")
 */
val GreedyFreebooter = card("Greedy Freebooter") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Creature — Human Pirate"
    oracleText = "When this creature dies, scry 1 and create a Treasure token. (To scry 1, look at the top card of your library. You may put that card on the bottom. A Treasure token is an artifact with \"{T}, Sacrifice this token: Add one mana of any color.\")"
    power = 1
    toughness = 1
    triggeredAbility {
        trigger = Triggers.Dies
        effect = Effects.Composite(
            Patterns.Library.scry(1),
            Effects.CreateTreasure()
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "109"
        artist = "David Palumbo"
        flavorText = "Neither Nurgam nor the mycoid who laid the trap could quite believe their luck."
        imageUri = "https://cards.scryfall.io/normal/front/6/9/692fe4e8-13b4-4bec-938e-a8073a7fbd71.jpg"
    }
}
