package com.wingedsheep.mtg.sets.definitions.lci.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.ActivatedAbility
import com.wingedsheep.sdk.scripting.Duration
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.effects.BecomeArtifactEffect
import com.wingedsheep.sdk.scripting.effects.WardCost
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent

/**
 * Kitesail Larcenist
 * {2}{U}
 * Creature — Human Pirate
 * 2/3
 *
 * Flying, ward {1}
 * When this creature enters, for each player, choose up to one other target artifact or creature
 * that player controls. For as long as this creature remains on the battlefield, the chosen
 * permanents become Treasure artifacts with "{T}, Sacrifice this artifact: Add one mana of any
 * color" and lose all other abilities.
 *
 * Modeling notes:
 *
 *  - **Flying, ward {1}** — [Keyword.FLYING] plus a `Ward` keyword ability with a {1} mana cost
 *    ([KeywordAbility.Ward] + [WardCost.Mana]).
 *
 *  - **"For each player, choose up to one other target ... that player controls"** — this is a
 *    *targeted* choice (the word "target" matters: ward/hexproof/shroud/protection are checked at
 *    announcement, when the ETB ability goes on the stack). The engine's target system declares a
 *    fixed set of target slots per ability, so in the two-player games the engine models we render
 *    the per-player fan-out as two optional ("up to one") target slots chosen by Kitesail's
 *    controller — one per player:
 *      * `yours` — up to one **other** ([TargetFilter.other], i.e. excluding Kitesail itself)
 *        artifact or creature *you* control ([TargetFilter.youControl]).
 *      * `theirs` — up to one artifact or creature an *opponent* controls
 *        ([TargetFilter.opponentControls]). No `other()` is needed here: Kitesail is never an
 *        opponent's permanent, so it can never be this slot's match anyway.
 *    Both slots are `optional = true` ("up to one" ⇒ may choose none for a player). Because a
 *    permanent has exactly one controller, the two control-scoped filters can never overlap, so
 *    the same permanent can't be chosen twice. (In a hypothetical 3+ player game this two-slot
 *    rendering under-approximates the "for each player" fan-out; the engine's scenario coverage is
 *    two-player — same approximation Unstable Glyphbridge documents for its "for each player"
 *    winnow.)
 *
 *  - **"become Treasure artifacts ... and lose all other abilities"** — a CR 611.2b continuous
 *    effect generated by the resolving ETB, applied to each chosen permanent via
 *    [BecomeArtifactEffect]:
 *      * `cardTypes = {ARTIFACT}` (Layer 4) *replaces* all card types — "becomes an artifact" with
 *        no "in addition to", so a chosen creature stops being a creature (can't attack/block; its
 *        power/toughness stop mattering).
 *      * `subtypes = {Treasure}` (Layer 4) replaces all subtypes.
 *      * `colors = null` — the effect makes **no** Layer-5 change: "become Treasure artifacts" is a
 *        pure type change, and the oracle never says "colorless", so each permanent keeps its own
 *        color. (Contrast Vraska, the Silencer / Imprisoned in the Moon, whose oracle text is an
 *        explicitly *colorless* object — those pass `emptySet()`.)
 *      * `loseAllAbilities = true` (Layer 6) — "lose all other abilities".
 *      * `grantedAbility` = the standard Treasure "{T}, Sacrifice this artifact: Add one mana of any
 *        color" (mirrors the predefined Treasure token). It's recorded in the durable
 *        granted-activated-ability store, so it survives the Layer-6 ability wipe.
 *
 *  - **"For as long as this creature remains on the battlefield"** — every floating effect and the
 *    granted ability carry [Duration.WhileSourceOnBattlefield] keyed to Kitesail. When Kitesail
 *    leaves the battlefield, `EndedDurationExpiryCheck` (a state-based action) drops both the
 *    floating type/ability effects and the duration-keyed granted ability, so the chosen permanents
 *    revert (a chosen creature becomes a creature again). Because the duration is source-keyed (not
 *    a one-shot), the transform is a floating effect from the ETB rather than a static ability on
 *    Kitesail — a static would incorrectly bind to Kitesail's own abilities rather than the chosen
 *    permanents.
 *
 * Earliest (and only) printing is The Lost Caverns of Ixalan (2023); this is the canonical
 * definition.
 */
val KitesailLarcenist = card("Kitesail Larcenist") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Human Pirate"
    oracleText = "Flying, ward {1}\n" +
        "When this creature enters, for each player, choose up to one other target artifact or " +
        "creature that player controls. For as long as this creature remains on the battlefield, " +
        "the chosen permanents become Treasure artifacts with \"{T}, Sacrifice this artifact: Add " +
        "one mana of any color\" and lose all other abilities."
    power = 2
    toughness = 3

    keywords(Keyword.FLYING)
    keywordAbility(KeywordAbility.Ward(WardCost.Mana("{1}")))

    // The standard Treasure mana ability granted to each chosen permanent (mirrors the predefined
    // Treasure token). Survives the "lose all other abilities" wipe via the durable granted-ability
    // store.
    val treasureManaAbility = ActivatedAbility(
        cost = Costs.Composite(Costs.Tap, Costs.SacrificeSelf),
        effect = Effects.AddAnyColorMana(1),
        isManaAbility = true,
        descriptionOverride = "{T}, Sacrifice this artifact: Add one mana of any color."
    )

    // The transform lasts for as long as Kitesail Larcenist remains on the battlefield.
    val whileKitesailRemains = Duration.WhileSourceOnBattlefield("Kitesail Larcenist")

    triggeredAbility {
        trigger = Triggers.EntersBattlefield

        // "for each player, choose up to one other target artifact or creature that player controls"
        // (two-player rendering: one optional slot per player — see KDoc).
        val yours = target(
            "up to one other target artifact or creature you control",
            TargetPermanent(
                filter = TargetFilter.CreatureOrArtifact.youControl().other(),
                optional = true
            )
        )
        val theirs = target(
            "up to one target artifact or creature an opponent controls",
            TargetPermanent(
                filter = TargetFilter.CreatureOrArtifact.opponentControls(),
                optional = true
            )
        )

        effect = Effects.Composite(
            BecomeArtifactEffect(
                target = yours,
                cardTypes = setOf("ARTIFACT"),
                subtypes = setOf("Treasure"),
                colors = null,
                loseAllAbilities = true,
                grantedAbility = treasureManaAbility,
                duration = whileKitesailRemains
            ),
            BecomeArtifactEffect(
                target = theirs,
                cardTypes = setOf("ARTIFACT"),
                subtypes = setOf("Treasure"),
                colors = null,
                loseAllAbilities = true,
                grantedAbility = treasureManaAbility,
                duration = whileKitesailRemains
            )
        )
        description = "When this creature enters, for each player, choose up to one other target " +
            "artifact or creature that player controls. For as long as this creature remains on " +
            "the battlefield, the chosen permanents become Treasure artifacts with \"{T}, " +
            "Sacrifice this artifact: Add one mana of any color\" and lose all other abilities."
    }

    metadata {
        rarity = Rarity.RARE
        collectorNumber = "61"
        artist = "Sidharth Chaturvedi"
        imageUri = "https://cards.scryfall.io/normal/front/0/3/03207457-70d8-4462-8c8b-ed39791d56a1.jpg?1782694559"
    }
}
