// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lci.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.effects.LoseLifeEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Mephitic Draught
 * {1}{B}
 * Artifact
 * When this artifact enters or is put into a graveyard from the battlefield, you draw a card and you lose 1 life.
 */
val MephiticDraught = card("Mephitic Draught") {
    manaCost = "{1}{B}"
    colorIdentity = "B"
    typeLine = "Artifact"
    oracleText = "When this artifact enters or is put into a graveyard from the battlefield, you draw a card and you lose 1 life."
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.Composite(
            DrawCardsEffect(1),
            LoseLifeEffect(1, EffectTarget.Controller)
        )
    }
    triggeredAbility {
        trigger = Triggers.PutIntoGraveyardFromBattlefield
        effect = Effects.Composite(
            DrawCardsEffect(1),
            LoseLifeEffect(1, EffectTarget.Controller)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "112"
        artist = "Lauren K. Cannon"
        flavorText = "\"Don't look at me. I'm not drinking it.\"\n—Dranach, Dire Fleet boatswain"
        imageUri = "https://cards.scryfall.io/normal/front/a/d/adcae196-dbcc-44d5-b700-c57b0b646483.jpg"
    }
}
