// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lci.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.ModalEffect
import com.wingedsheep.sdk.scripting.effects.Mode
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Oltec Archaeologists
 * {4}{W}
 * Creature — Human Artificer Scout
 * 4/4
 * When this creature enters, choose one —
 * • Return target artifact card from your graveyard to your hand.
 * • Scry 3. (Look at the top three cards of your library, then put any number of them on the bottom and the rest on top in any order.)
 */
val OltecArchaeologists = card("Oltec Archaeologists") {
    manaCost = "{4}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Artificer Scout"
    oracleText = "When this creature enters, choose one —\n• Return target artifact card from your graveyard to your hand.\n• Scry 3. (Look at the top three cards of your library, then put any number of them on the bottom and the rest on top in any order.)"
    power = 4
    toughness = 4
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = ModalEffect.chooseOne(
            Mode.withTarget(
                Effects.Move(EffectTarget.ContextTarget(0), Zone.HAND),
                TargetObject(filter = TargetFilter(GameObjectFilter.Artifact.ownedByYou(), zone = Zone.GRAVEYARD)),
                "Return target artifact card from your graveyard to your hand"
            ),
            Mode.noTarget(
                Patterns.Library.scry(3),
                "Scry 3. (Look at the top three cards of your library, then put any number of them on the bottom and the rest on top in any order.)"
            )
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "27"
        artist = "Winona Nelson"
        imageUri = "https://cards.scryfall.io/normal/front/5/7/57c21561-2213-4524-89a6-30a305843e5a.jpg"
    }
}
