// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lci.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.CostModification
import com.wingedsheep.sdk.scripting.CostReductionSource
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.ModifySpellCost
import com.wingedsheep.sdk.scripting.SpellCostTarget
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Quicksand Whirlpool
 * {5}{W}
 * Instant
 * This spell costs {3} less to cast if it targets a tapped creature.
 * Exile target creature.
 */
val QuicksandWhirlpool = card("Quicksand Whirlpool") {
    manaCost = "{5}{W}"
    colorIdentity = "W"
    typeLine = "Instant"
    oracleText = "This spell costs {3} less to cast if it targets a tapped creature.\nExile target creature."
    staticAbility {
        ability = ModifySpellCost(
            target = SpellCostTarget.SelfCast,
            modification = CostModification.ReduceGenericBy(
                CostReductionSource.FixedIfAnyTargetMatches(amount = 3, filter = GameObjectFilter.Creature.tapped())
            )
        )
    }
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Exile(t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "31"
        artist = "L.A. Draws"
        flavorText = "\"Those who would steal the blood and breath of the living will drink their fill of the sand.\"\n—Sovereign Okinec Ahau"
        imageUri = "https://cards.scryfall.io/normal/front/a/7/a74ddccb-ebbd-4fad-a9b6-6b9e9bafae31.jpg"
    }
}
