// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lci.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.ManaCost
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect


/**
 * Soaring Sandwing
 * {4}{W}{W}
 * Creature — Dinosaur
 * 3/5
 * Flying
 * When this creature enters, you gain 3 life.
 * Plainscycling {2} ({2}, Discard this card: Search your library for a Plains card, reveal it, put it into your hand, then shuffle.)
 */
val SoaringSandwing = card("Soaring Sandwing") {
    manaCost = "{4}{W}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Dinosaur"
    oracleText = "Flying\nWhen this creature enters, you gain 3 life.\nPlainscycling {2} ({2}, Discard this card: Search your library for a Plains card, reveal it, put it into your hand, then shuffle.)"
    power = 3
    toughness = 5
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = GainLifeEffect(3)
    }
    keywordAbility(KeywordAbility.typecycling("Plains", ManaCost.parse("{2}")))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "35"
        artist = "John Tedrick"
        imageUri = "https://cards.scryfall.io/normal/front/e/7/e7833724-aec6-41a4-a7ea-2aa722467732.jpg"
    }
}
