// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lci.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Vito's Inquisitor
 * {3}{B}
 * Creature — Vampire Knight
 * 3/3
 * {B}, Sacrifice another creature or artifact: Put a +1/+1 counter on this creature. It gains menace until end of turn.
 */
val VitosInquisitor = card("Vito's Inquisitor") {
    manaCost = "{3}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Vampire Knight"
    oracleText = "{B}, Sacrifice another creature or artifact: Put a +1/+1 counter on this creature. It gains menace until end of turn."
    power = 3
    toughness = 3
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{B}"), Costs.SacrificeAnother(GameObjectFilter.CreatureOrArtifact))
        effect = Effects.Composite(
            AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = EffectTarget.Self),
            Effects.GrantKeyword(Keyword.MENACE, EffectTarget.Self)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "130"
        artist = "Anna Pavleeva"
        flavorText = "\"We usher in the Age of Everflowing Blood, when those who are fed upon will be fed, and those who feed will be satiated.\""
        imageUri = "https://cards.scryfall.io/normal/front/9/0/9030048a-b866-4a89-8d4a-aa55411463e4.jpg"
    }
}
