// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.p02.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.effects.ForEachPlayerEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Magma Giant
 * {5}{R}{R}
 * Creature — Giant
 * 5/5
 * When this creature enters, it deals 2 damage to each creature and each player.
 */
val MagmaGiant = card("Magma Giant") {
    manaCost = "{5}{R}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Giant"
    oracleText = "When this creature enters, it deals 2 damage to each creature and each player."
    power = 5
    toughness = 5
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.Composite(
            Effects.ForEachInGroup(GroupFilter(GameObjectFilter.Creature), DealDamageEffect(2, EffectTarget.Self)),
            ForEachPlayerEffect(Player.Each, listOf(DealDamageEffect(2, EffectTarget.Controller)))
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "108"
        artist = "Michael Weaver"
        imageUri = "https://cards.scryfall.io/normal/front/9/2/92bec2e0-a016-42bd-85d9-fbb262998110.jpg"
    }
}
