// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Angel of Flight Alabaster
 * {4}{W}
 * Creature — Angel
 * 4/4
 * Flying
 * At the beginning of your upkeep, return target Spirit card from your graveyard to your hand.
 */
val AngelOfFlightAlabaster = card("Angel of Flight Alabaster") {
    manaCost = "{4}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Angel"
    oracleText = "Flying\nAt the beginning of your upkeep, return target Spirit card from your graveyard to your hand."
    power = 4
    toughness = 4
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.YourUpkeep
        val t = target(
            "target",
            TargetObject(
                filter = TargetFilter(
                    GameObjectFilter.Any.withSubtype(Subtype.SPIRIT).ownedByYou(),
                    zone = Zone.GRAVEYARD
                )
            )
        )
        effect = Effects.Move(t, Zone.HAND)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "2"
        artist = "Howard Lyon"
        flavorText = "She endures without Avacyn but secretly asks each soul she guides if it has seen her."
        imageUri = "https://cards.scryfall.io/normal/front/8/d/8dfe629f-485c-4619-9713-32d2ae406e63.jpg"
    }
}
