// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.ModifyStats
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Battleground Geist
 * {4}{U}
 * Creature — Spirit
 * 3/3
 * Flying
 * Other Spirit creatures you control get +1/+0.
 */
val BattlegroundGeist = card("Battleground Geist") {
    manaCost = "{4}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Spirit"
    oracleText = "Flying\nOther Spirit creatures you control get +1/+0."
    power = 3
    toughness = 3
    keywords(Keyword.FLYING)
    staticAbility {
        ability = ModifyStats(
            powerBonus = 1,
            toughnessBonus = 0,
            filter = GroupFilter(GameObjectFilter.Creature.withSubtype(Subtype.SPIRIT).youControl(), excludeSelf = true)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "45"
        artist = "Clint Cearley"
        flavorText = "Not content to nudge vases and chill drawing rooms, some geists muster spectral armies to claw at the hearts of the living."
        imageUri = "https://cards.scryfall.io/normal/front/1/2/129905ef-5b3b-4860-923c-109a7d7cad80.jpg"
    }
}
