// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GrantKeyword


/**
 * Cobbled Wings
 * {2}
 * Artifact — Equipment
 * Equipped creature has flying.
 * Equip {1} ({1}: Attach to target creature you control. Equip only as a sorcery.)
 */
val CobbledWings = card("Cobbled Wings") {
    manaCost = "{2}"
    colorIdentity = ""
    typeLine = "Artifact — Equipment"
    oracleText = "Equipped creature has flying.\nEquip {1} ({1}: Attach to target creature you control. Equip only as a sorcery.)"
    staticAbility {
        ability = GrantKeyword(Keyword.FLYING)
    }
    equipAbility("{1}")
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "219"
        artist = "Matt Stewart"
        flavorText = "For the necro-alchemist, any puzzle can be solved with intelligence and harvested body parts."
        imageUri = "https://cards.scryfall.io/normal/front/2/4/24abd762-e533-491a-97b6-aed40c214e9d.jpg"
    }
}
