// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.ModifyStats


/**
 * Dead Weight
 * {B}
 * Enchantment — Aura
 * Enchant creature
 * Enchanted creature gets -2/-2.
 */
val DeadWeight = card("Dead Weight") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Enchantment — Aura"
    oracleText = "Enchant creature\nEnchanted creature gets -2/-2."
    auraTarget = Targets.Creature
    staticAbility {
        ability = ModifyStats(-2, -2)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "96"
        artist = "Randy Gallegos"
        flavorText = "The crueler vampires' idea of free-range farming."
        imageUri = "https://cards.scryfall.io/normal/front/7/9/7933987e-7b8c-4d5a-804a-708d6bb6d231.jpg"
    }
}
