// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.GrantKeyword
import com.wingedsheep.sdk.scripting.ModifyStats
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Intangible Virtue
 * {1}{W}
 * Enchantment
 * Creature tokens you control get +1/+1 and have vigilance.
 */
val IntangibleVirtue = card("Intangible Virtue") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Enchantment"
    oracleText = "Creature tokens you control get +1/+1 and have vigilance."
    staticAbility {
        ability = ModifyStats(
            powerBonus = 1,
            toughnessBonus = 1,
            filter = GroupFilter(GameObjectFilter.Creature.token().youControl())
        )
    }
    staticAbility {
        ability = GrantKeyword(Keyword.VIGILANCE, GroupFilter(GameObjectFilter.Creature.token().youControl()))
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "19"
        artist = "Clint Cearley"
        flavorText = "In life, they were a motley crew: farmers, lords, cutpurses, priests. In death, they are united in singular, benevolent purpose."
        imageUri = "https://cards.scryfall.io/normal/front/0/d/0dd21f5e-d284-4072-87b9-7f0e6140fe60.jpg"
    }
}
