// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Markov Patrician
 * {2}{B}
 * Creature — Vampire
 * 3/1
 * Lifelink (Damage dealt by this creature also causes you to gain that much life.)
 */
val MarkovPatrician = card("Markov Patrician") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Vampire"
    oracleText = "Lifelink (Damage dealt by this creature also causes you to gain that much life.)"
    power = 3
    toughness = 1
    keywords(Keyword.LIFELINK)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "107"
        artist = "Jana Schirmer & Johannes Voss"
        flavorText = "Vampires of the Markov bloodline pride themselves on their exquisite taste in fashion, art, and \"wine of the vein.\""
        imageUri = "https://cards.scryfall.io/normal/front/2/9/29c3d3f7-5e28-4fec-8422-87856fcd1e8e.jpg"
    }
}
