// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Maw of the Mire
 * {4}{B}
 * Sorcery
 * Destroy target land. You gain 4 life.
 */
val MawOfTheMire = card("Maw of the Mire") {
    manaCost = "{4}{B}"
    colorIdentity = "B"
    typeLine = "Sorcery"
    oracleText = "Destroy target land. You gain 4 life."
    spell {
        val t = target("target", TargetPermanent(filter = TargetFilter.Land))
        effect = Effects.Composite(
            Effects.Move(t, Zone.GRAVEYARD, byDestruction = true),
            GainLifeEffect(4)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "108"
        artist = "Vincent Proce"
        flavorText = "As the chapel was dragged under, the bell in the tower rang until the murky depths forever silenced its toll."
        imageUri = "https://cards.scryfall.io/normal/front/9/0/90b34a03-3270-412c-90ca-03c1b3e61222.jpg"
    }
}
