// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility


/**
 * Moan of the Unhallowed
 * {2}{B}{B}
 * Sorcery
 * Create two 2/2 black Zombie creature tokens.
 * Flashback {5}{B}{B} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val MoanOfTheUnhallowed = card("Moan of the Unhallowed") {
    manaCost = "{2}{B}{B}"
    colorIdentity = "B"
    typeLine = "Sorcery"
    oracleText = "Create two 2/2 black Zombie creature tokens.\nFlashback {5}{B}{B} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        effect = Effects.CreateToken(
            power = 2,
            toughness = 2,
            colors = setOf(Color.BLACK),
            creatureTypes = setOf("Zombie"),
            count = 2
        )
    }
    keywordAbility(KeywordAbility.flashback("{5}{B}{B}"))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "109"
        artist = "Nils Hamm"
        flavorText = "For a ghoul, every village is a buffet and every disaster is a reunion."
        imageUri = "https://cards.scryfall.io/normal/front/3/e/3e2c5a8f-c03a-40ab-8390-ff6b5b654717.jpg"
    }
}
