// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Morkrut Banshee
 * {3}{B}{B}
 * Creature — Spirit
 * 4/4
 * Morbid — When this creature enters, if a creature died this turn, target creature gets -4/-4 until end of turn.
 */
val MorkrutBanshee = card("Morkrut Banshee") {
    manaCost = "{3}{B}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Spirit"
    oracleText = "Morbid — When this creature enters, if a creature died this turn, target creature gets -4/-4 until end of turn."
    power = 4
    toughness = 4
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        triggerCondition = Conditions.CreatureDiedThisTurn
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ModifyStats(-4, -4, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "110"
        artist = "Svetlin Velinov"
        flavorText = "\"Let go your grudges, or risk wandering the bogs forever in a murderous rage.\"\n—Hildin, priest of Avacyn"
        imageUri = "https://cards.scryfall.io/normal/front/f/f/fff9989f-77a3-4f73-ade6-c04306c98501.jpg"
    }
}
