// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.ModifyStats
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * One-Eyed Scarecrow
 * {3}
 * Artifact Creature — Scarecrow
 * 2/3
 * Defender
 * Creatures with flying your opponents control get -1/-0.
 */
val OneEyedScarecrow = card("One-Eyed Scarecrow") {
    manaCost = "{3}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Scarecrow"
    oracleText = "Defender\nCreatures with flying your opponents control get -1/-0."
    power = 2
    toughness = 3
    keywords(Keyword.DEFENDER)
    staticAbility {
        ability = ModifyStats(
            powerBonus = -1,
            toughnessBonus = 0,
            filter = GroupFilter(GameObjectFilter.Creature.withKeyword(Keyword.FLYING).opponentControls())
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "230"
        artist = "Dave Kendall"
        flavorText = "Farmhands and priests mutter curses at the ragged thing; it unnerves more than just the crows."
        imageUri = "https://cards.scryfall.io/normal/front/5/d/5d495d85-6458-44d5-b3b4-5e09569057e3.jpg"
    }
}
