// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Selfless Cathar
 * {W}
 * Creature — Human Cleric
 * 1/1
 * {1}{W}, Sacrifice this creature: Creatures you control get +1/+1 until end of turn.
 */
val SelflessCathar = card("Selfless Cathar") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Cleric"
    oracleText = "{1}{W}, Sacrifice this creature: Creatures you control get +1/+1 until end of turn."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}{W}"), Costs.SacrificeSelf)
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature.youControl()),
            Effects.ModifyStats(1, 1, EffectTarget.Self)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "30"
        artist = "Slawomir Maniak"
        flavorText = "\"If I fail to offer myself, we will surely be overrun. My fate would be the same.\""
        imageUri = "https://cards.scryfall.io/normal/front/5/a/5a1dc067-1972-4d46-ad5d-56e6a563f638.jpg"
    }
}
