// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Slayer of the Wicked
 * {3}{W}
 * Creature — Human Soldier
 * 3/2
 * When this creature enters, you may destroy target Vampire, Werewolf, or Zombie.
 */
val SlayerOfTheWicked = card("Slayer of the Wicked") {
    manaCost = "{3}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Soldier"
    oracleText = "When this creature enters, you may destroy target Vampire, Werewolf, or Zombie."
    power = 3
    toughness = 2
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        optional = true
        val t = target(
            "target",
            TargetCreature(
                filter = TargetFilter(
                    GameObjectFilter.Creature.withSubtype(
                        "Vampire"
                    ) or GameObjectFilter.Creature.withSubtype("Werewolf") or GameObjectFilter.Creature.withSubtype("Zombie")
                )
            )
        )
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "32"
        artist = "Anthony Palumbo"
        flavorText = "You don't want to see his trophy room."
        imageUri = "https://cards.scryfall.io/normal/front/1/c/1c2cd68e-ff4c-49c7-ba0d-f2299d9c21f4.jpg"
    }
}
