// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Conservator
 * {4}
 * Artifact
 * {3}, {T}: Prevent the next 2 damage that would be dealt to you this turn.
 */
val Conservator = card("Conservator") {
    manaCost = "{4}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{3}, {T}: Prevent the next 2 damage that would be dealt to you this turn."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{3}"), Costs.Tap)
        effect = Effects.PreventNextDamage(2, EffectTarget.Controller)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "237"
        artist = "Amy Weber"
        imageUri = "https://cards.scryfall.io/normal/front/c/7/c7824e2a-4eff-4f72-9216-0db30a4f4252.jpg"
    }
}
