import React from 'react'

export const styles: Record<string, React.CSSProperties> = {
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#0a0a15',
    overflow: 'hidden',
  },
  opponentArea: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexShrink: 1,
    flexGrow: 0,
    minHeight: 0,
    maxHeight: '36vh',
    marginBottom: 8,
    paddingBottom: 8,
  },
  centerArea: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '2px 8px',
    flex: 1,
    gap: 16,
    width: '100%',
  },
  centerLifeSection: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  playerNameWithLabel: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 1,
  },
  playerLabel: {
    color: '#555',
    fontStyle: 'italic',
  },
  handWithMana: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'center',
  },
  floatingPassButton: {
    position: 'fixed',
    bottom: 16,
    right: 16,
    fontWeight: 600,
    backgroundColor: '#e67e22',
    color: 'white',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(0,0,0,0.4)',
    zIndex: 100,
  },
  combatButtonContainer: {
    position: 'fixed',
    bottom: 16,
    right: 16,
    display: 'flex',
    gap: 8,
    zIndex: 100,
  },
  combatButton: {
    padding: '12px 24px',
    fontWeight: 600,
    color: 'white',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(0,0,0,0.4)',
    fontSize: 14,
  },
  combatButtonPrimary: {
    backgroundColor: '#c62828',
    border: '2px solid #ef5350',
  },
  combatButtonSecondary: {
    backgroundColor: '#424242',
    border: '2px solid #757575',
  },
  playerArea: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexShrink: 1,
    flexGrow: 0,
    minHeight: 0,
    maxHeight: '46vh',
    marginTop: 'auto',
    paddingBottom: 0,
  },
  playerRowWithZones: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    justifyContent: 'center',
    minHeight: 0,
  },
  playerMainArea: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 0,
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  zonePile: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  zoneStack: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
  },
  deckPile: {
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 2px 8px rgba(0,0,0,0.5)',
  },
  graveyardPile: {
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 2px 8px rgba(0,0,0,0.5)',
    backgroundColor: '#1a1a2e',
  },
  pileImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  emptyPile: {
    width: '100%',
    height: '100%',
    backgroundColor: '#1a1a2e',
    border: '2px dashed #333',
    borderRadius: 6,
  },
  pileCount: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    backgroundColor: 'rgba(0,0,0,0.8)',
    color: 'white',
    fontSize: 12,
    fontWeight: 700,
    padding: '2px 6px',
    borderRadius: 4,
  },
  zoneLabel: {
    color: '#666',
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  graveyardOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
  } as React.CSSProperties,
  graveyardBrowserContent: {
    maxWidth: '90vw',
    maxHeight: '80vh',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  } as React.CSSProperties,
  graveyardBrowserHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  } as React.CSSProperties,
  graveyardBrowserTitle: {
    color: '#ccc',
    margin: 0,
    fontSize: 18,
    fontWeight: 600,
  } as React.CSSProperties,
  graveyardCloseButton: {
    background: 'none',
    border: '1px solid #555',
    color: '#aaa',
    fontSize: 18,
    cursor: 'pointer',
    padding: '4px 10px',
    borderRadius: 4,
  } as React.CSSProperties,
  graveyardCardGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
    overflowY: 'auto',
    justifyContent: 'center',
  } as React.CSSProperties,
  exilePile: {
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 2px 8px rgba(124, 58, 237, 0.4)',
    backgroundColor: '#1a1a2e',
    border: '1px solid rgba(124, 58, 237, 0.5)',
  },
  exileOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(20, 0, 40, 0.9)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
  } as React.CSSProperties,
  exileBrowserContent: {
    maxWidth: '90vw',
    maxHeight: '80vh',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  } as React.CSSProperties,
  exileBrowserHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  } as React.CSSProperties,
  exileBrowserTitle: {
    color: '#c4b5fd',
    margin: 0,
    fontSize: 18,
    fontWeight: 600,
  } as React.CSSProperties,
  exileCloseButton: {
    background: 'none',
    border: '1px solid #7c3aed',
    color: '#c4b5fd',
    fontSize: 18,
    cursor: 'pointer',
    padding: '4px 10px',
    borderRadius: 4,
  } as React.CSSProperties,
  exileCardGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
    overflowY: 'auto',
    justifyContent: 'center',
  } as React.CSSProperties,
  playerInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  playerName: {
    color: '#888',
  },
  spectatorNameLabel: {
    color: '#e0e0e0',
    fontSize: 14,
    fontWeight: 600,
    backgroundColor: 'rgba(20, 20, 30, 0.9)',
    padding: '8px 16px',
    borderRadius: 6,
    border: '1px solid rgba(255, 255, 255, 0.15)',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.4)',
    letterSpacing: '0.02em',
    zIndex: 100,
  },
  lifeDisplay: {
    borderRadius: '50%',
    border: '3px solid',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 700,
  },
  playerControls: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: 4,
  },
  passButton: {
    padding: '10px 24px',
    fontWeight: 600,
    backgroundColor: '#e67e22',
    color: 'white',
    border: 'none',
    borderRadius: 6,
    cursor: 'pointer',
  },
  cardRow: {
    display: 'flex',
    justifyContent: 'center',
    flexWrap: 'wrap',
    maxWidth: '100%',
  },
  emptyZone: {
    color: '#444',
    padding: 4,
    minHeight: 60,
  },
  battlefieldArea: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    flexShrink: 1,
    minHeight: 0,
  },
  battlefieldRow: {
    display: 'flex',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  card: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#1a1a2e',
    transition: 'transform 0.15s, box-shadow 0.15s',
    flexShrink: 0,
  },
  cardImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  cardFallback: {
    display: 'none',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 4,
    backgroundColor: '#2a2a4e',
  },
  cardName: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 500,
  },
  cardPT: {
    color: 'white',
    fontWeight: 700,
    marginTop: 4,
  },
  ptOverlay: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    padding: '2px 6px',
    borderRadius: 4,
    border: '1px solid rgba(255, 255, 255, 0.3)',
  } as React.CSSProperties,
  keywordIconsContainer: {
    position: 'absolute',
    top: 4,
    left: 4,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    pointerEvents: 'none',
  } as React.CSSProperties,
  keywordIconWrapper: {
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    borderRadius: 4,
    padding: 2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid rgba(255, 255, 255, 0.2)',
  } as React.CSSProperties,
  activeEffectsContainer: {
    position: 'absolute',
    bottom: 28,
    left: 4,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  } as React.CSSProperties,
  activeEffectBadge: {
    backgroundColor: 'rgba(150, 50, 200, 0.9)',
    borderRadius: 4,
    padding: '2px 6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid rgba(255, 200, 255, 0.4)',
    cursor: 'help',
  } as React.CSSProperties,
  activeEffectText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  } as React.CSSProperties,
  cardEffectTooltip: {
    position: 'fixed',
    transform: 'translate(-50%, -100%)',
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    color: '#ffffff',
    padding: '6px 10px',
    borderRadius: 4,
    fontSize: 11,
    whiteSpace: 'nowrap',
    zIndex: 10000,
    marginTop: -8,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.5)',
    pointerEvents: 'none',
    border: '1px solid rgba(150, 50, 200, 0.5)',
  } as React.CSSProperties,
  tappedOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  summoningSicknessOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(100, 100, 150, 0.3)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'none',
  },
  summoningSicknessIcon: {
    opacity: 0.8,
  },
  playableGlow: {
    position: 'absolute',
    top: -2,
    left: -2,
    right: -2,
    bottom: -2,
    borderRadius: 10,
    pointerEvents: 'none',
    animation: 'playablePulse 2s ease-in-out infinite',
    background: 'transparent',
    boxShadow: '0 0 8px rgba(0, 255, 0, 0.4)',
  },
  targetingOverlay: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    padding: '16px 24px',
    borderRadius: 12,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
    zIndex: 100,
    border: '2px solid #ff4444',
  },
  targetingPrompt: {
    color: '#ff4444',
    fontSize: 16,
    fontWeight: 600,
  },
  actionButton: {
    padding: '12px 16px',
    fontSize: 14,
    backgroundColor: '#2a5a2a',
    color: 'white',
    border: 'none',
    borderRadius: 6,
    cursor: 'pointer',
    textAlign: 'left',
  },
  cancelButton: {
    padding: '10px 16px',
    fontSize: 14,
    backgroundColor: '#444',
    color: '#888',
    border: 'none',
    borderRadius: 6,
    cursor: 'pointer',
    marginTop: 8,
  },
  stackContainer: {
    position: 'fixed',
    left: 16,
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '8px 12px',
    backgroundColor: 'rgba(100, 50, 150, 0.3)',
    borderRadius: 8,
    border: '1px solid rgba(150, 100, 200, 0.4)',
    zIndex: 50,
    maxHeight: '60vh',
    overflowY: 'auto',
  },
  stackHeader: {
    color: '#b088d0',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  stackItems: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
  },
  stackItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
    cursor: 'pointer',
    transition: 'transform 0.15s',
  },
  stackItemImage: {
    width: 60,
    height: 84,
    objectFit: 'cover',
    borderRadius: 4,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.5)',
  },
  stackItemName: {
    color: '#ccc',
    marginTop: 4,
    maxWidth: 80,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    textAlign: 'center',
  },
  stackXBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: 'rgba(138, 43, 226, 0.95)',
    color: 'white',
    padding: '2px 6px',
    borderRadius: 4,
    fontSize: 11,
    fontWeight: 700,
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.5)',
    zIndex: 10,
  } as React.CSSProperties,
  stackActiveEffects: {
    position: 'absolute',
    bottom: 4,
    left: 4,
    right: 4,
    zIndex: 10,
  } as React.CSSProperties,
  // Card preview styles
  cardPreviewOverlay: {
    position: 'fixed',
    top: 20,
    left: 20,
    zIndex: 2500,
    pointerEvents: 'none',
  } as React.CSSProperties,
  cardPreviewContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  } as React.CSSProperties,
  cardPreviewCard: {
    borderRadius: 12,
    overflow: 'hidden',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.8), 0 0 0 2px rgba(255, 255, 255, 0.1)',
  } as React.CSSProperties,
  cardPreviewImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  } as React.CSSProperties,
  cardPreviewKeywords: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    padding: 12,
    borderRadius: 8,
    border: '1px solid rgba(255, 255, 255, 0.1)',
  } as React.CSSProperties,
  cardPreviewKeyword: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  } as React.CSSProperties,
  cardPreviewKeywordName: {
    color: '#ffcc00',
    fontWeight: 600,
    fontSize: 14,
  } as React.CSSProperties,
  cardPreviewRulings: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.92)',
    padding: 12,
    borderRadius: 8,
    border: '1px solid rgba(100, 150, 255, 0.3)',
    maxWidth: 320,
    maxHeight: 300,
    overflowY: 'auto',
  } as React.CSSProperties,
  cardPreviewRulingsHeader: {
    color: '#6699ff',
    fontWeight: 700,
    fontSize: 13,
    textTransform: 'uppercase',
    letterSpacing: 1,
    borderBottom: '1px solid rgba(100, 150, 255, 0.2)',
    paddingBottom: 6,
  } as React.CSSProperties,
  cardPreviewRuling: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  } as React.CSSProperties,
  cardPreviewRulingDate: {
    color: '#888888',
    fontSize: 11,
    fontStyle: 'italic',
  } as React.CSSProperties,
  cardPreviewRulingText: {
    color: '#dddddd',
    fontSize: 12,
    lineHeight: 1.4,
  } as React.CSSProperties,
  cardPreviewRulingsHint: {
    color: '#666666',
    fontSize: 11,
    fontStyle: 'italic',
    textAlign: 'center',
    padding: '4px 8px',
  } as React.CSSProperties,
  // Active effect badge styles
  effectBadgesContainer: {
    display: 'flex',
    flexDirection: 'row',
    gap: 4,
    flexWrap: 'wrap',
  } as React.CSSProperties,
  effectBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255, 100, 100, 0.2)',
    border: '1px solid rgba(255, 100, 100, 0.5)',
    borderRadius: 4,
    color: '#ff8888',
    position: 'relative',
    cursor: 'help',
  } as React.CSSProperties,
  effectBadgeIcon: {
    fontSize: 12,
  } as React.CSSProperties,
  effectBadgeName: {
    fontWeight: 500,
    whiteSpace: 'nowrap',
  } as React.CSSProperties,
  effectTooltip: {
    position: 'absolute',
    bottom: '100%',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    color: '#ffffff',
    padding: '6px 10px',
    borderRadius: 4,
    fontSize: 12,
    whiteSpace: 'nowrap',
    zIndex: 1000,
    marginBottom: 4,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.3)',
    pointerEvents: 'none',
  } as React.CSSProperties,
  // Counter badge styles (for +1/+1 counters on battlefield cards)
  counterBadge: {
    position: 'absolute',
    bottom: 22,
    right: 4,
    backgroundColor: 'rgba(30, 80, 140, 0.95)',
    borderRadius: 4,
    border: '1px solid rgba(100, 180, 255, 0.5)',
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    color: '#66ccff',
    fontWeight: 700,
    zIndex: 5,
  } as React.CSSProperties,
  counterBadgeIcon: {
    fontSize: 8,
    opacity: 0.9,
  } as React.CSSProperties,
  counterBadgeText: {
    fontWeight: 700,
  } as React.CSSProperties,
  // Gold counter badge (for Aurification etc.)
  goldCounterBadge: {
    position: 'absolute',
    bottom: 22,
    left: 4,
    backgroundColor: 'rgba(140, 100, 20, 0.95)',
    borderRadius: 4,
    border: '1px solid rgba(218, 165, 32, 0.6)',
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    color: '#ffd700',
    fontWeight: 700,
    zIndex: 5,
  } as React.CSSProperties,
  // Enhanced preview stats box styles
  cardPreviewStatsBox: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'rgba(0, 0, 0, 0.92)',
    borderRadius: 8,
    padding: '8px 12px',
    gap: 6,
    border: '1px solid rgba(255, 255, 255, 0.15)',
  } as React.CSSProperties,
  cardPreviewStatsMain: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  } as React.CSSProperties,
  cardPreviewStatsBreakdown: {
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    borderTop: '1px solid rgba(255, 255, 255, 0.15)',
    paddingTop: 6,
  } as React.CSSProperties,
  cardPreviewStatsRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: 12,
  } as React.CSSProperties,
  cardPreviewStatsLabel: {
    color: '#888888',
    display: 'flex',
    alignItems: 'center',
  } as React.CSSProperties,
  cardPreviewStatsValue: {
    color: '#cccccc',
    fontWeight: 600,
    fontFamily: 'monospace',
  } as React.CSSProperties,
}
