// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.GrantKeyword
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Absolute Law
 * {1}{W}
 * Enchantment
 * All creatures have protection from red.
 */
val AbsoluteLaw = card("Absolute Law") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Enchantment"
    oracleText = "All creatures have protection from red."
    staticAbility {
        ability = GrantKeyword(Keyword.PROTECTION, GroupFilter(GameObjectFilter.Creature))
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "2"
        artist = "Mark Zug"
        flavorText = "The strength of law is unwavering. It is an iron bar in a world of water."
        imageUri = "https://cards.scryfall.io/normal/front/5/9/59d1f05b-f165-47c7-8a78-3b60ee3298ca.jpg"
    }
}
