// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Angelic Page
 * {1}{W}
 * Creature — Angel Spirit
 * 1/1
 * Flying
 * {T}: Target attacking or blocking creature gets +1/+1 until end of turn.
 */
val AngelicPage = card("Angelic Page") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Angel Spirit"
    oracleText = "Flying\n{T}: Target attacking or blocking creature gets +1/+1 until end of turn."
    power = 1
    toughness = 1
    keywords(Keyword.FLYING)
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", TargetCreature(filter = TargetFilter.AttackingOrBlockingCreature))
        effect = Effects.ModifyStats(1, 1, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "4"
        artist = "Rebecca Guay"
        flavorText = "If only every message were as perfect as its bearers."
        imageUri = "https://cards.scryfall.io/normal/front/f/5/f50a4378-8b14-484c-b285-09cc4c4e1b3c.jpg"
    }
}
