// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Argothian Elder
 * {3}{G}
 * Creature — Elf Druid
 * 2/2
 * {T}: Untap two target lands.
 */
val ArgothianElder = card("Argothian Elder") {
    manaCost = "{3}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Elf Druid"
    oracleText = "{T}: Untap two target lands."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", TargetPermanent(count = 2, filter = TargetFilter.Land))
        effect = Effects.UntapEachTarget()
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "233"
        artist = "DiTerlizzi"
        flavorText = "Sharpen your ears\n—Elvish expression meaning \"grow wiser\""
        imageUri = "https://cards.scryfall.io/normal/front/4/5/453e7cb4-bc37-4932-85b7-3a4e160b73dc.jpg"
    }
}
