// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Befoul
 * {2}{B}{B}
 * Sorcery
 * Destroy target land or nonblack creature. It can't be regenerated.
 */
val Befoul = card("Befoul") {
    manaCost = "{2}{B}{B}"
    colorIdentity = "B"
    typeLine = "Sorcery"
    oracleText = "Destroy target land or nonblack creature. It can't be regenerated."
    spell {
        val t = target("target", TargetPermanent(filter = TargetFilter.CreatureOrLandPermanent))
        effect = Effects.Destroy(t, noRegenerate = true)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "116"
        artist = "Pete Venters"
        flavorText = "\"The land putrefied at its touch, turned into an oily bile in seconds.\"\n—Radiant, archangel"
        imageUri = "https://cards.scryfall.io/normal/front/f/9/f92cb48d-315b-4877-b615-ffdf275c4d61.jpg"
    }
}
