// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Blood Vassal
 * {2}{B}
 * Creature — Thrull
 * 2/2
 * Sacrifice this creature: Add {B}{B}.
 */
val BloodVassal = card("Blood Vassal") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Thrull"
    oracleText = "Sacrifice this creature: Add {B}{B}."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.SacrificeSelf
        effect = Effects.AddMana(Color.BLACK, 2)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "118"
        artist = "Chippy"
        flavorText = "\"They are bred to suffer and born to die. Much like humans.\"\n—Gix, Yawgmoth praetor"
        imageUri = "https://cards.scryfall.io/normal/front/7/e/7e692dea-750b-40b2-9440-8b570e67c23e.jpg"
    }
}
