// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Catalog
 * {2}{U}
 * Instant
 * Draw two cards, then discard a card.
 */
val Catalog = card("Catalog") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Draw two cards, then discard a card."
    spell {
        effect = Effects.Composite(
            DrawCardsEffect(2),
            Patterns.Hand.discardCards(1)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "64"
        artist = "Berry"
        flavorText = "\"Without order comes errors, and errors kill on Tolaria.\"\n—Barrin, master wizard"
        imageUri = "https://cards.scryfall.io/normal/front/3/1/31bdef28-0e27-4c8d-a04c-5413519dcb4e.jpg"
    }
}
