// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Cathodion
 * {3}
 * Artifact Creature — Construct
 * 3/3
 * When this creature dies, add {C}{C}{C}.
 */
val Cathodion = card("Cathodion") {
    manaCost = "{3}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Construct"
    oracleText = "When this creature dies, add {C}{C}{C}."
    power = 3
    toughness = 3
    triggeredAbility {
        trigger = Triggers.Dies
        effect = Effects.AddColorlessMana(3)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "287"
        artist = "Henry G. Higginbotham"
        flavorText = "Instead of creating a tool that would be damaged by heat, the Thran built one that was charged by it."
        imageUri = "https://cards.scryfall.io/normal/front/2/8/28def495-1806-40ec-b170-ca727c914f30.jpg"
    }
}
