// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect


/**
 * Claws of Gix
 * {0}
 * Artifact
 * {1}, Sacrifice a permanent: You gain 1 life.
 */
val ClawsOfGix = card("Claws of Gix") {
    manaCost = "{0}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{1}, Sacrifice a permanent: You gain 1 life."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}"), Costs.Sacrifice(GameObjectFilter.Permanent))
        effect = GainLifeEffect(1)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "290"
        artist = "Henry G. Higginbotham"
        flavorText = "When the Brotherhood of Gix dug out the cave of Koilos they found their master's severed hand. They enshrined it, hoping that one day it would point the way to Phyrexia."
        imageUri = "https://cards.scryfall.io/normal/front/7/8/78372366-8c4c-46ac-bd7c-a735c2b24b5d.jpg"
    }
}
