// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.ModifyStats
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Crosswinds
 * {1}{G}
 * Enchantment
 * Creatures with flying get -2/-0.
 */
val Crosswinds = card("Crosswinds") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Enchantment"
    oracleText = "Creatures with flying get -2/-0."
    staticAbility {
        ability = ModifyStats(
            powerBonus = -2,
            toughnessBonus = 0,
            filter = GroupFilter(GameObjectFilter.Creature.withKeyword(Keyword.FLYING))
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "246"
        artist = "Randy Elliott"
        flavorText = "Harbin's ornithopter had been trapped for two days within the currents of the storm. When the skies cleared, all he could see was a horizon of trees."
        imageUri = "https://cards.scryfall.io/normal/front/f/1/f182a85b-a119-46e2-8b8b-48b6758d9c39.jpg"
    }
}
