// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Gaea's Cradle
 * Legendary Land
 * {T}: Add {G} for each creature you control.
 */
val GaeasCradle = card("Gaea's Cradle") {
    manaCost = ""
    colorIdentity = "G"
    typeLine = "Legendary Land"
    oracleText = "{T}: Add {G} for each creature you control."
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(Color.GREEN, DynamicAmount.AggregateBattlefield(Player.You, GameObjectFilter.Creature))
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "321"
        artist = "Mark Zug"
        flavorText = "\"Here sprouted the first seedling of Argoth. Here the last tree will fall.\"\n—Gamelen, Citanul elder"
        imageUri = "https://cards.scryfall.io/normal/front/2/5/25b0b816-0583-44aa-9dc5-f3ff48993a51.jpg"
    }
}
