// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Goblin Spelunkers
 * {2}{R}
 * Creature — Goblin Warrior
 * 2/2
 * Mountainwalk (This creature can't be blocked as long as defending player controls a Mountain.)
 */
val GoblinSpelunkers = card("Goblin Spelunkers") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Goblin Warrior"
    oracleText = "Mountainwalk (This creature can't be blocked as long as defending player controls a Mountain.)"
    power = 2
    toughness = 2
    keywords(Keyword.MOUNTAINWALK)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "195"
        artist = "DiTerlizzi"
        flavorText = "\"It only short jump. You go first.\"\n\"AIIIEEEE!\"\n\"Hmm . . . we go different way now.\""
        imageUri = "https://cards.scryfall.io/normal/front/7/d/7d02a81f-2dac-41f7-a818-811baa238021.jpg"
    }
}
