// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Looming Shade
 * {2}{B}
 * Creature — Shade
 * 1/1
 * {B}: This creature gets +1/+1 until end of turn.
 */
val LoomingShade = card("Looming Shade") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Shade"
    oracleText = "{B}: This creature gets +1/+1 until end of turn."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Mana("{B}")
        effect = Effects.ModifyStats(1, 1, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "139"
        artist = "Vincent Evans"
        flavorText = "The shade tracks victims by reverberations of the pipes, as a spider senses prey tangled in its trembling web."
        imageUri = "https://cards.scryfall.io/normal/front/5/2/525f63ae-e002-4d47-bea5-b24dc89d4d06.jpg"
    }
}
