// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility


/**
 * Lull
 * {1}{G}
 * Instant
 * Prevent all combat damage that would be dealt this turn.
 * Cycling {2} ({2}, Discard this card: Draw a card.)
 */
val Lull = card("Lull") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Prevent all combat damage that would be dealt this turn.\nCycling {2} ({2}, Discard this card: Draw a card.)"
    spell {
        effect = Effects.PreventAllCombatDamage()
    }
    keywordAbility(KeywordAbility.cycling("{2}"))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "267"
        artist = "Terese Nielsen"
        imageUri = "https://cards.scryfall.io/normal/front/e/e/eec5d627-b3d7-4e11-81c7-bf4cef5409a6.jpg"
    }
}
