// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Monk Idealist
 * {2}{W}
 * Creature — Human Monk Cleric
 * 2/2
 * When this creature enters, return target enchantment card from your graveyard to your hand.
 */
val MonkIdealist = card("Monk Idealist") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Monk Cleric"
    oracleText = "When this creature enters, return target enchantment card from your graveyard to your hand."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target(
            "target",
            TargetObject(filter = TargetFilter(GameObjectFilter.Enchantment.ownedByYou(), zone = Zone.GRAVEYARD))
        )
        effect = Effects.Move(t, Zone.HAND)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "20"
        artist = "Daren Bader"
        flavorText = "\"Belief is the strongest mortar.\""
        imageUri = "https://cards.scryfall.io/normal/front/2/8/285a867b-f82e-49cb-a59c-31a25129baf9.jpg"
    }
}
