// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Pegasus Charger
 * {2}{W}
 * Creature — Pegasus
 * 2/1
 * Flying (This creature can't be blocked except by creatures with flying or reach.)
 * First strike (This creature deals combat damage before creatures without first strike.)
 */
val PegasusCharger = card("Pegasus Charger") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Pegasus"
    oracleText = "Flying (This creature can't be blocked except by creatures with flying or reach.)\nFirst strike (This creature deals combat damage before creatures without first strike.)"
    power = 2
    toughness = 1
    keywords(Keyword.FLYING, Keyword.FIRST_STRIKE)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "30"
        artist = "Val Mayerik"
        flavorText = "\"The clouds came alive and dove to the earth! Hooves flashed among the dark army, who fled before the spectacle of fury.\"\n—Song of All, canto 211"
        imageUri = "https://cards.scryfall.io/normal/front/d/6/d62a5287-25ec-4e13-9e39-1c87a4052c4d.jpg"
    }
}
