// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility


/**
 * Pendrell Drake
 * {3}{U}
 * Creature — Drake
 * 2/3
 * Flying
 * Cycling {2} ({2}, Discard this card: Draw a card.)
 */
val PendrellDrake = card("Pendrell Drake") {
    manaCost = "{3}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Drake"
    oracleText = "Flying\nCycling {2} ({2}, Discard this card: Draw a card.)"
    power = 2
    toughness = 3
    keywords(Keyword.FLYING)
    keywordAbility(KeywordAbility.cycling("{2}"))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "86"
        artist = "Jeff Miracola"
        flavorText = "The mages of Tolaria found strange ways to spend their free time. Occasionally they had contests to see whose kite was eaten last."
        imageUri = "https://cards.scryfall.io/normal/front/9/8/986b6708-5ed4-4085-b9b7-d359b2d5b26f.jpg"
    }
}
