// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SacrificeSelfEffect


/**
 * Reclusive Wight
 * {3}{B}
 * Creature — Zombie Minion
 * 4/4
 * At the beginning of your upkeep, if you control another nonland permanent, sacrifice this creature.
 */
val ReclusiveWight = card("Reclusive Wight") {
    manaCost = "{3}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Zombie Minion"
    oracleText = "At the beginning of your upkeep, if you control another nonland permanent, sacrifice this creature."
    power = 4
    toughness = 4
    triggeredAbility {
        trigger = Triggers.YourUpkeep
        triggerCondition = Conditions.YouControl(GameObjectFilter.Land)
        effect = SacrificeSelfEffect
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "153"
        artist = "Vincent Evans"
        flavorText = "There are places so horrible that even the dead hide their faces."
        imageUri = "https://cards.scryfall.io/normal/front/3/8/384b14c6-78a0-4e82-924e-781719c8defb.jpg"
    }
}
