// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Scrap
 * {2}{R}
 * Instant
 * Destroy target artifact.
 * Cycling {2} ({2}, Discard this card: Draw a card.)
 */
val Scrap = card("Scrap") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Destroy target artifact.\nCycling {2} ({2}, Discard this card: Draw a card.)"
    spell {
        val t = target("target", TargetPermanent(filter = TargetFilter.Artifact))
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    keywordAbility(KeywordAbility.cycling("{2}"))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "213"
        artist = "Donato Giancola"
        imageUri = "https://cards.scryfall.io/normal/front/3/f/3f070430-59d6-462f-9f04-306ffc2ae01b.jpg"
    }
}
