// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GrantKeyword
import com.wingedsheep.sdk.scripting.ModifyStats


/**
 * Serra's Embrace
 * {2}{W}{W}
 * Enchantment — Aura
 * Enchant creature
 * Enchanted creature gets +2/+2 and has flying and vigilance. (Attacking doesn't cause it to tap.)
 */
val SerrasEmbrace = card("Serra's Embrace") {
    manaCost = "{2}{W}{W}"
    colorIdentity = "W"
    typeLine = "Enchantment — Aura"
    oracleText = "Enchant creature\nEnchanted creature gets +2/+2 and has flying and vigilance. (Attacking doesn't cause it to tap.)"
    auraTarget = Targets.Creature
    staticAbility {
        ability = ModifyStats(2, 2)
    }
    staticAbility {
        ability = GrantKeyword(Keyword.FLYING)
    }
    staticAbility {
        ability = GrantKeyword(Keyword.VIGILANCE)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "47"
        artist = "Terese Nielsen"
        flavorText = "\"Lifted beyond herself, for that battle Brindri was an angel of light and fury.\"\n—Song of All, canto 524"
        imageUri = "https://cards.scryfall.io/normal/front/1/4/145c3ebd-7a67-4606-8427-f3b91ab26b84.jpg"
    }
}
