// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Serra's Sanctum
 * Legendary Land
 * {T}: Add {W} for each enchantment you control.
 */
val SerrasSanctum = card("Serra's Sanctum") {
    manaCost = ""
    colorIdentity = "W"
    typeLine = "Legendary Land"
    oracleText = "{T}: Add {W} for each enchantment you control."
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(
            Color.WHITE,
            DynamicAmount.AggregateBattlefield(Player.You, GameObjectFilter.Enchantment)
        )
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "325"
        artist = "Ciruelo"
        flavorText = "A fragile cocoon of dreaming will."
        imageUri = "https://cards.scryfall.io/normal/front/f/7/f7a18130-dbaa-4657-a885-3a96a985935a.jpg"
    }
}
