// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.SacrificeSelfEffect


/**
 * Skittering Skirge
 * {B}{B}
 * Creature — Phyrexian Imp
 * 3/2
 * Flying
 * When you cast a creature spell, sacrifice this creature.
 */
val SkitteringSkirge = card("Skittering Skirge") {
    manaCost = "{B}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Phyrexian Imp"
    oracleText = "Flying\nWhen you cast a creature spell, sacrifice this creature."
    power = 3
    toughness = 2
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.YouCastCreature
        effect = SacrificeSelfEffect
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "158"
        artist = "Ron Spencer"
        flavorText = "The imps' warbling cries echo through Phyrexia's towers like those of mourning doves in a cathedral."
        imageUri = "https://cards.scryfall.io/normal/front/9/3/93aba9d5-5f96-4aba-8248-74398b8bfe9d.jpg"
    }
}
