// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Spire Owl
 * {1}{U}
 * Creature — Bird
 * 1/1
 * Flying
 * When this creature enters, look at the top four cards of your library, then put them back in any order.
 */
val SpireOwl = card("Spire Owl") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Bird"
    oracleText = "Flying\nWhen this creature enters, look at the top four cards of your library, then put them back in any order."
    power = 1
    toughness = 1
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Patterns.Library.lookAtTopAndReorder(count = 4)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "98"
        artist = "Steve Firchow"
        imageUri = "https://cards.scryfall.io/normal/front/c/6/c66b2aa6-e891-4ae5-b6c9-1537b797c3ab.jpg"
    }
}
