// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Viashino Runner
 * {3}{R}
 * Creature — Lizard
 * 3/2
 * Menace (This creature can't be blocked except by two or more creatures.)
 */
val ViashinoRunner = card("Viashino Runner") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Lizard"
    oracleText = "Menace (This creature can't be blocked except by two or more creatures.)"
    power = 3
    toughness = 2
    keywords(Keyword.MENACE)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "224"
        artist = "Steve White"
        flavorText = "\"It moved this way, an' that way, an' then before I could stick it, it jumped over my head an' was gone.\"\n—Jula, goblin raider"
        imageUri = "https://cards.scryfall.io/normal/front/1/5/15bf72e0-0b0c-4b29-8709-9dcd460508cb.jpg"
    }
}
