// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Scion of the Wild
 * {1}{G}{G}
 * Creature — Avatar
 * 0/0
 * Scion of the Wild's power and toughness are each equal to the number of creatures you control.
 */
val ScionOfTheWild = card("Scion of the Wild") {
    manaCost = "{1}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Avatar"
    oracleText = "Scion of the Wild's power and toughness are each equal to the number of creatures you control."
    power = 0
    toughness = 0
    dynamicStats(DynamicAmount.AggregateBattlefield(Player.You, GameObjectFilter.Creature))
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "182"
        artist = "Kev Walker"
        flavorText = "It has a hundred thousand extinctions to avenge."
        imageUri = "https://cards.scryfall.io/normal/front/f/e/feb05072-c619-4024-8ed8-440b01f73113.jpg"
    }
}
