package com.wingedsheep.mtg.sets.tokens

import com.wingedsheep.mtg.sets.MtgSetCatalog
import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.model.MtgSet
import com.wingedsheep.sdk.model.TokenPrinting
import java.nio.file.Files
import java.nio.file.Paths

/**
 * Reports every token our cards can create that has **no set-scoped art** — the work list for
 * self-hosting art for sets Scryfall has no token printings for.
 *
 * Roughly a third of the sets we implement predate token *cards* (Alpha through Invasion, Tempest,
 * Odyssey, Onslaught). Their tokens currently fall through to the engine-wide generic art for the
 * creature type, which is a stand-in, not the set's art. This report lists exactly what is missing
 * so the art can be produced, dropped into `web-client/public/images/tokens/`, and declared on the
 * set — the route Invasion's Saproling/Reflection and Outlaws' Rabbit already take.
 *
 * Run with: `just token-art-gaps` (or `./gradlew :mtg-sets:tokenArtGaps`).
 *
 * Writes `backlog/token-art-gaps.md` and prints a summary. For each gap it emits the suggested
 * self-hosted path and a ready-to-paste [TokenPrinting] row, so filling one in is: save the image
 * at the named path, paste the row into that set's `tokenArt`.
 *
 * Distinct from `TokenArtCoverageTest`, which is a build gate on a weaker property — that a token
 * resolves to *some* image. This is the quality backlog: which tokens are showing a generic
 * stand-in rather than their own art.
 */
fun main() {
    val gaps = collectGaps()

    // Worst-first: the sets needing the most art lead, so the report reads as a work queue.
    val bySet = gaps.groupBy { it.setCode }
        .toList()
        .sortedWith(compareByDescending<Pair<String, List<Gap>>> { it.second.size }.thenBy { it.first })

    val markdown = buildString {
        appendLine("# Token art gaps")
        appendLine()
        appendLine("Tokens our cards create that have no set-scoped art, so they render with the")
        appendLine("engine-wide generic art for their creature type. Generated by")
        appendLine("`just token-art-gaps` — do not hand-edit.")
        appendLine()

        // Every token in the corpus has its set's own art. Emitting the empty work queue and its
        // how-to-fill-one-in instructions would read as a report that failed to run.
        if (gaps.isEmpty()) {
            appendLine("**None.** Every token our cards can create resolves to art from the set that")
            appendLine("printed the creating card.")
            appendLine()
            appendLine("This regresses the moment a card is added whose set prints a token Scryfall has no")
            appendLine("`t<code>` row for — re-run to get the work queue back, with a suggested")
            appendLine("`web-client/public/images/tokens/<file>.jpeg` path and a paste-ready")
            appendLine("`TokenPrinting(...)` row for each gap.")
            return@buildString
        }

        appendLine("To fill one in:")
        appendLine()
        appendLine("1. Save the art as `web-client/public/images/tokens/<file>.jpeg` (landscape, art only —")
        appendLine("   the client frames it; a full card image gets cropped to its middle band).")
        appendLine("2. Paste the `TokenPrinting(...)` row into that set's `tokenArt` in its `MtgSet`.")
        appendLine()
        appendLine("Sets missing from Scryfall's token sets entirely (`t<code>`) are the bulk of this:")
        appendLine("Wizards printed no token cards before roughly Odyssey.")
        appendLine()
        appendLine("| Set | Distinct tokens missing art |")
        appendLine("|-----|-----------------------------|")
        for ((setCode, setGaps) in bySet) {
            appendLine("| $setCode | ${setGaps.size} |")
        }
        appendLine()
        appendLine("**${gaps.size} distinct tokens across ${bySet.size} sets.**")
        appendLine()

        for ((setCode, setGaps) in bySet) {
            appendLine("## $setCode")
            appendLine()
            val hasSyncedArt = TokenArtData.forSet(setCode).isNotEmpty()
            if (!hasSyncedArt) {
                appendLine("_No Scryfall token set (`t${setCode.lowercase()}`) — every token here needs self-hosted art._")
                appendLine()
            }
            for (gap in setGaps.sortedBy { it.tokenName }) {
                appendLine("- **${gap.describe()}** — created by ${gap.cards.size} card(s): " +
                    gap.cards.sorted().take(6).joinToString(", ") +
                    if (gap.cards.size > 6) ", …" else "")
                appendLine("  - image: `web-client/public/images/tokens/${gap.suggestedFile()}`")
                appendLine("  - ```kotlin")
                appendLine("    ${gap.kotlinRow()}")
                appendLine("    ```")
            }
            appendLine()
        }
    }

    val target = Paths.get("backlog/token-art-gaps.md")
    Files.createDirectories(target.parent)
    Files.writeString(target, markdown)

    println("Token art gaps: ${gaps.size} distinct tokens across ${bySet.size} sets.")
    println()
    for ((setCode, setGaps) in bySet.take(25)) {
        val note = if (TokenArtData.forSet(setCode).isEmpty()) "  (no Scryfall token set)" else ""
        println("  ${setCode.padEnd(6)} ${setGaps.size.toString().padStart(3)}$note")
    }
    if (bySet.size > 25) println("  … and ${bySet.size - 25} more sets")
    println()
    println("Wrote $target")
}

/** One distinct token identity in one set that has no set-scoped art. */
data class Gap(
    val setCode: String,
    val tokenName: String,
    val power: Int?,
    val toughness: Int?,
    val colors: Set<Color>,
    val predefined: Boolean,
    val cards: Set<String>,
) {
    fun describe(): String {
        val pt = if (power != null && toughness != null) "$power/$toughness " else ""
        val colorText = if (colors.isEmpty()) "colorless " else
            colors.sorted().joinToString("/") { it.displayName.lowercase() } + " "
        return if (predefined) tokenName else "$pt$colorText$tokenName"
    }

    fun suggestedFile(): String =
        "${setCode.lowercase()}-${tokenName.lowercase().replace(Regex("[^a-z0-9]+"), "-").trim('-')}.jpeg"

    fun kotlinRow(): String {
        val parts = mutableListOf(
            "name = \"$tokenName\"",
            "imageUri = \"/images/tokens/${suggestedFile()}\"",
        )
        if (power != null) parts += "power = $power"
        if (toughness != null) parts += "toughness = $toughness"
        if (!predefined) {
            parts += "colors = " + if (colors.isEmpty()) "emptySet()"
            else "setOf(" + colors.sorted().joinToString(", ") { "Color.$it" } + ")"
        }
        return "TokenPrinting(${parts.joinToString(", ")}),"
    }
}

/**
 * Every token identity with no set-scoped art, deduplicated per (set, identity) and carrying the
 * cards that create it.
 *
 * Uses the same matcher the engine does ([TokenPrinting.bestMatch]) against the same sheet the
 * wiring registers ([TokenArtData.forSet] — the set's hand-authored `tokenArt` overriding the
 * synced rows), so a token listed here is genuinely one the engine will render with generic art.
 */
fun collectGaps(sets: List<MtgSet> = MtgSetCatalog.all): List<Gap> {
    val gaps = linkedMapOf<String, Gap>()

    for (set in sets) {
        val art = TokenArtData.forSet(set)
        for (card in set.cards) {
            for (site in TokenCreationSites.of(card)) {
                // A resolution-time chosen type has no static identity to look up, and a card that
                // pins its own art has already answered the question.
                if (site.chosenType || site.explicitImageUri != null) continue
                if (TokenPrinting.bestMatch(
                        art, site.tokenName, site.power, site.toughness, site.colors
                    ) != null
                ) continue

                val key = "${set.code}|${site.tokenName}|${site.power}|${site.toughness}|" +
                    site.colors.sorted().joinToString(",")
                val existing = gaps[key]
                gaps[key] = existing?.copy(cards = existing.cards + card.name)
                    ?: Gap(
                        setCode = set.code,
                        tokenName = site.tokenName,
                        power = site.power,
                        toughness = site.toughness,
                        colors = site.colors,
                        predefined = site.predefined,
                        cards = setOf(card.name),
                    )
            }
        }
    }
    return gaps.values.toList()
}
