// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TriggerBinding
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect


/**
 * Dazzling Angel
 * {2}{W}
 * Creature — Angel
 * 2/3
 * Flying
 * Whenever another creature you control enters, you gain 1 life.
 */
val DazzlingAngel = card("Dazzling Angel") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Angel"
    oracleText = "Flying\nWhenever another creature you control enters, you gain 1 life."
    power = 2
    toughness = 3
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.entersBattlefield(
            filter = GameObjectFilter.Creature.youControl(),
            binding = TriggerBinding.OTHER
        )
        effect = GainLifeEffect(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "732"
        artist = "Daneen Wilkerson"
        flavorText = "Her wings ripple with impossible colors—a sign that a miracle is on the way."
        imageUri = "https://cards.scryfall.io/normal/front/a/0/a0bdf4d1-576f-41b6-a077-8725be608331.jpg"
    }
}
