// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Goblin Surprise
 * {2}{R}
 * Instant
 * Choose one —
 * • Creatures you control get +2/+0 until end of turn.
 * • Create two 1/1 red Goblin creature tokens.
 */
val GoblinSurprise = card("Goblin Surprise") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Choose one —\n• Creatures you control get +2/+0 until end of turn.\n• Create two 1/1 red Goblin creature tokens."
    spell {
        modal(chooseCount = 1) {
            mode("Creatures you control get +2/+0 until end of turn") {
                effect = Effects.ForEachInGroup(
                    GroupFilter(GameObjectFilter.Creature.youControl()),
                    Effects.ModifyStats(2, 0, EffectTarget.Self)
                )
            }
            mode("Create two 1/1 red Goblin creature tokens") {
                effect = Effects.CreateToken(
                    power = 1,
                    toughness = 1,
                    colors = setOf(Color.RED),
                    creatureTypes = setOf("Goblin"),
                    count = 2
                )
            }
        }
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "200"
        artist = "Kevin Sidharta"
        flavorText = "\"Hey, your door's broken!\""
        imageUri = "https://cards.scryfall.io/normal/front/5/2/527dd5d4-5f72-40bb-8a9d-1f5ac3f81e2e.jpg"
    }
}
