// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Icewind Elemental
 * {4}{U}
 * Creature — Elemental
 * 3/4
 * Flying
 * When this creature enters, draw a card, then discard a card.
 */
val IcewindElemental = card("Icewind Elemental") {
    manaCost = "{4}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Elemental"
    oracleText = "Flying\nWhen this creature enters, draw a card, then discard a card."
    power = 3
    toughness = 4
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.Composite(
            DrawCardsEffect(1),
            Patterns.Hand.discardCards(1)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "742"
        artist = "Andrew Mar"
        flavorText = "It surveys its domain on wings of ice, bringing misfortune to all who dare trespass."
        imageUri = "https://cards.scryfall.io/normal/front/c/2/c2bfdfb6-aa0b-4bd7-89ba-6435da730e5e.jpg"
    }
}
