// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Prideful Parent
 * {2}{W}
 * Creature — Cat
 * 2/2
 * Vigilance (Attacking doesn't cause this creature to tap.)
 * When this creature enters, create a 1/1 white Cat creature token.
 */
val PridefulParent = card("Prideful Parent") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Cat"
    oracleText = "Vigilance (Attacking doesn't cause this creature to tap.)\nWhen this creature enters, create a 1/1 white Cat creature token."
    power = 2
    toughness = 2
    keywords(Keyword.VIGILANCE)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.CreateToken(
            power = 1,
            toughness = 1,
            colors = setOf(Color.WHITE),
            creatureTypes = setOf("Cat")
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "21"
        artist = "Leonardo Santanna"
        flavorText = "One day, the future king will protect a pride of his own. For now, he defends his family from the terror of the swishy tail."
        imageUri = "https://cards.scryfall.io/normal/front/b/7/b742117a-8a72-43b9-b05d-274829d138a2.jpg"
    }
}
