// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Quakestrider Ceratops
 * {3}{G}{G}{G}
 * Creature — Dinosaur
 * 12/8
 */
val QuakestriderCeratops = card("Quakestrider Ceratops") {
    manaCost = "{3}{G}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Dinosaur"
    power = 12
    toughness = 8
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "110"
        artist = "Josiah \"Jo\" Cameron"
        flavorText = "\"For the first time in all my travels, I've encountered a creature I can only describe as an apex herbivore.\"\n—Vivien Reid"
        imageUri = "https://cards.scryfall.io/normal/front/0/6/067f72c2-ead6-4879-bc9d-696c9f87c0b2.jpg"
    }
}
