// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.CounterEffect
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.targets.TargetSpell


/**
 * Refute
 * {1}{U}{U}
 * Instant
 * Counter target spell. Draw a card, then discard a card.
 */
val Refute = card("Refute") {
    manaCost = "{1}{U}{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Counter target spell. Draw a card, then discard a card."
    spell {
        val t = target("target", TargetSpell())
        effect = Effects.Composite(
            CounterEffect(),
            DrawCardsEffect(1),
            Patterns.Hand.discardCards(1)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "48"
        artist = "Ignatius Budi"
        flavorText = "\"I said no!\""
        imageUri = "https://cards.scryfall.io/normal/front/3/8/38806934-dd9c-4ad4-a59c-a16dce03a14a.jpg"
    }
}
