// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Rite of the Dragoncaller
 * {4}{R}{R}
 * Enchantment
 * Whenever you cast an instant or sorcery spell, create a 5/5 red Dragon creature token with flying.
 */
val RiteOfTheDragoncaller = card("Rite of the Dragoncaller") {
    manaCost = "{4}{R}{R}"
    colorIdentity = "R"
    typeLine = "Enchantment"
    oracleText = "Whenever you cast an instant or sorcery spell, create a 5/5 red Dragon creature token with flying."
    triggeredAbility {
        trigger = Triggers.YouCastInstantOrSorcery
        effect = Effects.CreateToken(
            power = 5,
            toughness = 5,
            colors = setOf(Color.RED),
            creatureTypes = setOf("Dragon"),
            keywords = setOf(Keyword.FLYING)
        )
    }
    metadata {
        rarity = Rarity.MYTHIC
        collectorNumber = "92"
        artist = "PINDURSKI"
        flavorText = "All at once, a quiet world was seized by wings, claws, fangs, and fire."
        imageUri = "https://cards.scryfall.io/normal/front/6/7/673e4561-8dfd-46db-b492-878009666ac7.jpg"
    }
}
