// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.effects.ConditionalEffect
import com.wingedsheep.sdk.scripting.effects.ModalEffect
import com.wingedsheep.sdk.scripting.effects.Mode
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Sylvan Scavenging
 * {1}{G}{G}
 * Enchantment
 * At the beginning of your end step, choose one —
 * • Put a +1/+1 counter on target creature you control.
 * • Create a 3/3 green Raccoon creature token if you control a creature with power 4 or greater.
 */
val SylvanScavenging = card("Sylvan Scavenging") {
    manaCost = "{1}{G}{G}"
    colorIdentity = "G"
    typeLine = "Enchantment"
    oracleText = "At the beginning of your end step, choose one —\n• Put a +1/+1 counter on target creature you control.\n• Create a 3/3 green Raccoon creature token if you control a creature with power 4 or greater."
    triggeredAbility {
        trigger = Triggers.YourEndStep
        effect = ModalEffect.chooseOne(
            Mode.withTarget(
                AddCountersEffect(
                    counterType = Counters.PLUS_ONE_PLUS_ONE,
                    count = 1,
                    target = EffectTarget.ContextTarget(0)
                ),
                TargetCreature(filter = TargetFilter.Creature.youControl()),
                "Put a +1/+1 counter on target creature you control"
            ),
            Mode.noTarget(
                ConditionalEffect(
                    condition = Conditions.YouControl(GameObjectFilter.Creature.powerAtLeast(4)),
                    effect = Effects.CreateToken(
                        power = 3,
                        toughness = 3,
                        colors = setOf(Color.GREEN),
                        creatureTypes = setOf("Raccoon")
                    )
                ),
                "Create a 3/3 green Raccoon creature token if you control a creature with power 4 or greater"
            )
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "113"
        artist = "Josiah \"Jo\" Cameron"
        imageUri = "https://cards.scryfall.io/normal/front/c/3/c35b683c-d3b2-46a1-876a-81b34e8ba2fc.jpg"
    }
}
