package com.wingedsheep.engine.mechanics.layers

import com.wingedsheep.engine.state.Component
import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.model.EntityId
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.conditions.ComparisonOperator
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.text.TextReplacer
import com.wingedsheep.sdk.scripting.values.DynamicAmount
import kotlinx.serialization.Serializable

/**
 * Component that stores continuous effects generated by a permanent.
 */
@Serializable
data class ContinuousEffectSourceComponent(
    val effects: List<ContinuousEffectData>
) : Component

/**
 * Data for a single continuous effect.
 */
@Serializable
data class ContinuousEffectData(
    val layer: Layer,
    val sublayer: Sublayer? = null,
    val modification: Modification,
    val affectsFilter: AffectsFilter? = null,
    val sourceCondition: SourceProjectionCondition? = null
)

/**
 * Filter for determining which entities are affected.
 */
@Serializable
sealed interface AffectsFilter {

    fun applyTextReplacement(replacer: TextReplacer): AffectsFilter

    @Serializable
    data object Self : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }
    @Serializable
    data object AllCreatures : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }
    @Serializable
    data object AllCreaturesYouControl : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }
    @Serializable
    data object AllCreaturesOpponentsControl : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }
    @Serializable
    data class SpecificEntities(val entityIds: Set<EntityId>) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }
    @Serializable
    data class WithSubtype(val subtype: String) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter {
            val new = replacer.replaceCreatureType(subtype)
            return if (new == subtype) this else WithSubtype(new)
        }
    }

    /**
     * Other creatures with a specific subtype (excludes the source permanent).
     * Used for lord effects like "Other Bird creatures get +1/+1."
     */
    @Serializable
    data class OtherCreaturesWithSubtype(val subtype: String) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter {
            val new = replacer.replaceCreatureType(subtype)
            return if (new == subtype) this else OtherCreaturesWithSubtype(new)
        }
    }

    /**
     * Other tapped creatures you control (excludes the source permanent).
     * Used for effects like "Other tapped creatures you control have indestructible."
     */
    @Serializable
    data object OtherTappedCreaturesYouControl : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * Other creatures you control (excludes the source permanent).
     * Used for lord effects like "Other creatures you control get +1/+1."
     */
    @Serializable
    data object OtherCreaturesYouControl : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * All other creatures (excludes the source permanent).
     */
    @Serializable
    data object AllOtherCreatures : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * The permanent this Aura is attached to.
     * Used for Aura effects like "You control enchanted permanent."
     */
    @Serializable
    data object AttachedPermanent : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * All creatures that have a specific counter type.
     * Used for Aurification: "Each creature with a gold counter on it..."
     */
    @Serializable
    data class CreaturesWithCounter(val counterType: String) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * All creatures you control that have a specific counter type.
     * Used for outlast lords: "Each creature you control with a +1/+1 counter on it has reach."
     */
    @Serializable
    data class OwnCreaturesWithCounter(val counterType: String) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * All face-down creatures.
     * Used for Ixidor, Reality Sculptor: "Face-down creatures get +1/+1."
     */
    @Serializable
    data object FaceDownCreatures : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * All creatures of the chosen creature type (resolved dynamically from source's ChosenCreatureTypeComponent).
     * Used for Shared Triumph: "Creatures of the chosen type get +1/+1."
     */
    @Serializable
    data object ChosenCreatureTypeCreatures : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * Creatures you control of the chosen creature type.
     * Used for Patchwork Banner: "Creatures you control of the chosen type get +1/+1."
     */
    @Serializable
    data object ChosenCreatureTypeCreaturesYouControl : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * Generic filter that preserves the full GroupFilter and evaluates it
     * against in-progress projected values during state projection.
     * Used as a fallback when specific AffectsFilter variants don't cover
     * the predicate combination (e.g., subtype + controller together).
     */
    @Serializable
    data class Generic(val groupFilter: GroupFilter) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter {
            val new = groupFilter.applyTextReplacement(replacer)
            return if (new === groupFilter) this else Generic(new)
        }
    }
}

/**
 * Represents a continuous effect that modifies the game state.
 */
@Serializable
data class ContinuousEffect(
    val sourceId: EntityId,
    val layer: Layer,
    val sublayer: Sublayer? = null,
    val timestamp: Long,
    val modification: Modification,
    val affectedEntities: Set<EntityId> = emptySet(),
    val sourceCondition: SourceProjectionCondition? = null,
    val affectsFilter: AffectsFilter? = null
)

/**
 * Conditions evaluated during state projection against projected values.
 *
 * Unlike SDK Conditions (evaluated by ConditionEvaluator against base GameState),
 * these conditions are checked during layer application so they see the effects
 * of earlier layers. For example, a Layer 6 ability condition can see Layer 4
 * type changes.
 */
@Serializable
sealed interface SourceProjectionCondition {
    /**
     * The source permanent must have a specific creature subtype.
     * Used for "has [keyword] as long as it's a [subtype]."
     */
    @Serializable
    data class HasSubtype(val subtype: String) : SourceProjectionCondition

    /**
     * The source permanent must have a specific keyword.
     * Used for "gets +X/+X as long as it has [keyword]."
     */
    @Serializable
    data class HasKeyword(val keyword: String) : SourceProjectionCondition

    /**
     * The source permanent's controller must control a creature with a specific subtype.
     * Used for "has [keyword] as long as you control a [subtype]."
     */
    @Serializable
    data class ControllerControlsCreatureOfType(val subtype: String) : SourceProjectionCondition

    /**
     * The creature enchanted by the source aura must have a specific subtype.
     * Used for "Enchanted creature gets X as long as it's a [subtype]."
     */
    @Serializable
    data class EnchantedCreatureHasSubtype(val subtype: String) : SourceProjectionCondition

    /**
     * An opponent of the source permanent's controller controls a creature.
     * Used for "as long as no opponent controls a creature" (via Not wrapper).
     */
    @Serializable
    data object OpponentControlsCreature : SourceProjectionCondition

    /**
     * It must be the source permanent's controller's turn.
     * Used for "has [keyword] as long as it's your turn."
     */
    @Serializable
    data object IsYourTurn : SourceProjectionCondition

    /**
     * Any player controls a permanent matching the given filter.
     * Used for "gets +X/+Y as long as any player controls a [color] permanent."
     */
    @Serializable
    data class AnyPlayerControlsPermanentMatchingFilter(
        val filter: GameObjectFilter
    ) : SourceProjectionCondition

    /**
     * The source permanent's controller controls a permanent matching the given filter.
     * Used for "as long as you control a [filter]" conditions.
     */
    @Serializable
    data class ControllerControlsPermanentMatchingFilter(
        val filter: GameObjectFilter
    ) : SourceProjectionCondition

    /**
     * Negation wrapper for source projection conditions.
     * Used for "otherwise" clauses (e.g., "Otherwise, it gets -3/-3").
     */
    @Serializable
    data class Not(val condition: SourceProjectionCondition) : SourceProjectionCondition

    /**
     * Compare two DynamicAmount values using a comparison operator.
     * Used for "as long as there are two or more instant and/or sorcery cards in your graveyard."
     */
    @Serializable
    data class Compare(
        val left: DynamicAmount,
        val operator: ComparisonOperator,
        val right: DynamicAmount
    ) : SourceProjectionCondition
}

/**
 * The layers in which continuous effects are applied (Rule 613).
 */
@Serializable
enum class Layer {
    COPY,           // Layer 1
    CONTROL,        // Layer 2
    TEXT,           // Layer 3
    TYPE,           // Layer 4
    COLOR,          // Layer 5
    ABILITY,        // Layer 6
    POWER_TOUGHNESS // Layer 7
}

/**
 * Sublayers for layer 7 (power/toughness).
 */
@Serializable
enum class Sublayer {
    CHARACTERISTIC_DEFINING,  // 7a
    SET_VALUES,               // 7b
    MODIFICATIONS,            // 7c
    COUNTERS,                 // 7d
    SWITCH                    // 7e
}

/**
 * Types of modifications that can be applied.
 */
@Serializable
sealed interface Modification {
    @Serializable
    data class SetPowerToughness(val power: Int, val toughness: Int) : Modification
    @Serializable
    data class SetPower(val power: Int) : Modification
    @Serializable
    data class ModifyPowerToughness(val powerMod: Int, val toughnessMod: Int) : Modification
    @Serializable
    data class SwitchPowerToughness(val targetId: EntityId) : Modification
    @Serializable
    data class GrantKeyword(val keyword: String) : Modification
    @Serializable
    data class RemoveKeyword(val keyword: String) : Modification
    @Serializable
    data class ChangeColor(val colors: Set<String>) : Modification
    @Serializable
    data class AddColor(val colors: Set<String>) : Modification
    @Serializable
    data class AddType(val type: String) : Modification
    @Serializable
    data class RemoveType(val type: String) : Modification

    /**
     * Add a subtype (also adds to types set).
     * Used for effects like "is a Wall in addition to its other creature types."
     */
    @Serializable
    data class AddSubtype(val subtype: String) : Modification

    /**
     * Replace all creature subtypes with the given set.
     * Used by "becomes the creature type of your choice" effects.
     */
    @Serializable
    data class SetCreatureSubtypes(val subtypes: Set<String>) : Modification

    /**
     * Replace all basic land subtypes with the given set (Rule 305.7).
     * Used by "is an Island" effects that change a land's basic land types.
     * Removes existing basic land subtypes (Plains, Island, Swamp, Mountain, Forest)
     * and replaces them with the specified types.
     */
    @Serializable
    data class SetBasicLandTypes(val subtypes: Set<String>) : Modification
    @Serializable
    data class ChangeController(val newControllerId: EntityId) : Modification

    /**
     * Change controller to whoever controls the source of this effect.
     * Used for Aura effects like "You control enchanted permanent" where
     * the controller is resolved dynamically at projection time.
     */
    @Serializable
    data object ChangeControllerToSourceController : Modification

    @Serializable
    data class GrantProtectionFromColor(val color: String) : Modification

    /**
     * Grants protection from the chosen color (resolved dynamically from source's ChosenColorComponent).
     * Used for Ward Sliver: "All Slivers have protection from the chosen color."
     */
    @Serializable
    data object GrantProtectionFromChosenColor : Modification

    @Serializable
    data object SetCantAttack : Modification
    @Serializable
    data object SetCantBlock : Modification

    @Serializable
    data object SetMustAttack : Modification
    @Serializable
    data object SetMustBlock : Modification

    /** Grants "can block an additional N creatures" to affected entities. Cumulative. */
    @Serializable
    data class CanBlockAdditional(val count: Int = 1) : Modification

    /**
     * Dynamic power/toughness modification based on counters on the source permanent.
     * The actual modification is computed at projection time by reading counter count from source.
     */
    @Serializable
    data class ModifyPowerToughnessPerSourceCounter(
        val counterType: String,
        val powerModPerCounter: Int,
        val toughnessModPerCounter: Int
    ) : Modification

    /**
     * Dynamic power/toughness modification based on other creatures sharing a creature type
     * with the affected entity. The actual modification is computed at projection time.
     */
    @Serializable
    data class ModifyPowerToughnessPerSharedCreatureType(
        val powerModPerCreature: Int,
        val toughnessModPerCreature: Int
    ) : Modification

    /**
     * Blocking restriction: creature can only be blocked by creatures with a specific subtype.
     * Used for Shifting Sliver: "Slivers can't be blocked except by Slivers."
     */
    @Serializable
    data class CantBeBlockedExceptBySubtype(val subtype: String) : Modification

    /**
     * Dynamic power/toughness modification based on a DynamicAmount.
     * The actual modification is computed at projection time by evaluating the DynamicAmount.
     * Used for effects like "gets +2/+2 for each face-down creature on the battlefield."
     */
    @Serializable
    data class ModifyPowerToughnessDynamic(
        val powerBonus: DynamicAmount,
        val toughnessBonus: DynamicAmount
    ) : Modification

    /**
     * Removes all abilities from the affected entity.
     * Used for effects like Deep Freeze ("loses all other abilities") and Turn to Frog.
     * Clears all keywords and sets the lostAllAbilities flag which suppresses
     * activated abilities, triggered abilities, and static abilities.
     */
    @Serializable
    data object RemoveAllAbilities : Modification

    /** No-op modification for effects that don't modify projected state (e.g., combat restrictions) */
    @Serializable
    data object NoOp : Modification
}

/**
 * Mutable projected values during calculation.
 */
internal data class MutableProjectedValues(
    var power: Int? = null,
    var toughness: Int? = null,
    val keywords: MutableSet<String> = mutableSetOf(),
    val colors: MutableSet<String> = mutableSetOf(),
    val types: MutableSet<String> = mutableSetOf(),
    val subtypes: MutableSet<String> = mutableSetOf(),
    var controllerId: EntityId? = null,
    var isFaceDown: Boolean = false,
    var cantAttack: Boolean = false,
    var cantBlock: Boolean = false,
    var mustAttack: Boolean = false,
    var mustBlock: Boolean = false,
    val cantBeBlockedExceptBySubtypes: MutableSet<String> = mutableSetOf(),
    var additionalBlockCount: Int = 0,
    var lostAllAbilities: Boolean = false
)
