package com.wingedsheep.engine.mechanics.layers

import com.wingedsheep.engine.state.Component
import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.model.EntityId
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.conditions.ComparisonOperator
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.text.TextReplacer
import com.wingedsheep.sdk.scripting.values.DynamicAmount
import kotlinx.serialization.Serializable

/**
 * Component that stores continuous effects generated by a permanent.
 */
@Serializable
data class ContinuousEffectSourceComponent(
    val effects: List<ContinuousEffectData>
) : Component

/**
 * Data for a single continuous effect.
 *
 * The [layer] and [sublayer] are derived from the [modification], which declares
 * its own Rule 613 layer. This ensures the layer assignment is always consistent
 * with the modification type.
 */
@Serializable
data class ContinuousEffectData(
    val modification: Modification,
    val affectsFilter: AffectsFilter? = null,
    val sourceCondition: SourceProjectionCondition? = null
) {
    val layer: Layer get() = modification.layer
    val sublayer: Sublayer? get() = modification.sublayer
}

/**
 * Filter for determining which entities are affected.
 */
@Serializable
sealed interface AffectsFilter {

    fun applyTextReplacement(replacer: TextReplacer): AffectsFilter

    @Serializable
    data object Self : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }
    @Serializable
    data object AllCreatures : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }
    @Serializable
    data object AllCreaturesYouControl : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }
    @Serializable
    data object AllCreaturesOpponentsControl : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }
    @Serializable
    data class SpecificEntities(val entityIds: Set<EntityId>) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }
    @Serializable
    data class WithSubtype(val subtype: String) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter {
            val new = replacer.replaceCreatureType(subtype)
            return if (new == subtype) this else WithSubtype(new)
        }
    }

    /**
     * Other creatures with a specific subtype (excludes the source permanent).
     * Used for lord effects like "Other Bird creatures get +1/+1."
     */
    @Serializable
    data class OtherCreaturesWithSubtype(val subtype: String) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter {
            val new = replacer.replaceCreatureType(subtype)
            return if (new == subtype) this else OtherCreaturesWithSubtype(new)
        }
    }

    /**
     * Other tapped creatures you control (excludes the source permanent).
     * Used for effects like "Other tapped creatures you control have indestructible."
     */
    @Serializable
    data object OtherTappedCreaturesYouControl : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * Other creatures you control (excludes the source permanent).
     * Used for lord effects like "Other creatures you control get +1/+1."
     */
    @Serializable
    data object OtherCreaturesYouControl : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * All other creatures (excludes the source permanent).
     */
    @Serializable
    data object AllOtherCreatures : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * The permanent this Aura is attached to.
     * Used for Aura effects like "You control enchanted permanent."
     */
    @Serializable
    data object AttachedPermanent : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * All creatures that have a specific counter type.
     * Used for Aurification: "Each creature with a gold counter on it..."
     */
    @Serializable
    data class CreaturesWithCounter(val counterType: String) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * All creatures you control that have a specific counter type.
     * Used for outlast lords: "Each creature you control with a +1/+1 counter on it has reach."
     */
    @Serializable
    data class OwnCreaturesWithCounter(val counterType: String) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * All lands that have a specific counter type.
     * Used for Eluge: "Each land with a flood counter on it is an Island."
     */
    @Serializable
    data class LandsWithCounter(val counterType: String) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * All face-down creatures.
     * Used for Ixidor, Reality Sculptor: "Face-down creatures get +1/+1."
     */
    @Serializable
    data object FaceDownCreatures : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this
    }

    /**
     * Generic filter that preserves the full GroupFilter and evaluates it
     * against in-progress projected values during state projection.
     * Used as a fallback when specific AffectsFilter variants don't cover
     * the predicate combination (e.g., subtype + controller together).
     */
    @Serializable
    data class Generic(val groupFilter: GroupFilter) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter {
            val new = groupFilter.applyTextReplacement(replacer)
            return if (new === groupFilter) this else Generic(new)
        }
    }
}

/**
 * Represents an active continuous effect during state projection.
 *
 * The [layer] and [sublayer] are derived from the [modification].
 */
@Serializable
data class ContinuousEffect(
    val sourceId: EntityId,
    val timestamp: Long,
    val modification: Modification,
    val affectedEntities: Set<EntityId> = emptySet(),
    val sourceCondition: SourceProjectionCondition? = null,
    val affectsFilter: AffectsFilter? = null
) {
    val layer: Layer get() = modification.layer
    val sublayer: Sublayer? get() = modification.sublayer
}

/**
 * Conditions evaluated during state projection against projected values.
 *
 * Unlike SDK Conditions (evaluated by ConditionEvaluator against base GameState),
 * these conditions are checked during layer application so they see the effects
 * of earlier layers. For example, a Layer 6 ability condition can see Layer 4
 * type changes.
 */
@Serializable
sealed interface SourceProjectionCondition {
    /**
     * The source permanent must have a specific creature subtype.
     * Used for "has [keyword] as long as it's a [subtype]."
     */
    @Serializable
    data class HasSubtype(val subtype: String) : SourceProjectionCondition

    /**
     * The source permanent must have a specific keyword.
     * Used for "gets +X/+X as long as it has [keyword]."
     */
    @Serializable
    data class HasKeyword(val keyword: String) : SourceProjectionCondition

    /**
     * The source permanent's controller must control a creature with a specific subtype.
     * Used for "has [keyword] as long as you control a [subtype]."
     */
    @Serializable
    data class ControllerControlsCreatureOfType(val subtype: String) : SourceProjectionCondition

    /**
     * The creature enchanted by the source aura must have a specific subtype.
     * Used for "Enchanted creature gets X as long as it's a [subtype]."
     */
    @Serializable
    data class EnchantedCreatureHasSubtype(val subtype: String) : SourceProjectionCondition

    /**
     * An opponent of the source permanent's controller controls a creature.
     * Used for "as long as no opponent controls a creature" (via Not wrapper).
     */
    @Serializable
    data object OpponentControlsCreature : SourceProjectionCondition

    /**
     * It must be the source permanent's controller's turn.
     * Used for "has [keyword] as long as it's your turn."
     */
    @Serializable
    data object IsYourTurn : SourceProjectionCondition

    /**
     * The source permanent is tapped.
     * Used for "has [keyword] as long as it's tapped."
     */
    @Serializable
    data object SourceIsTapped : SourceProjectionCondition

    /**
     * The source permanent is untapped.
     * Used for "has [keyword] as long as it's untapped" (e.g., Illusion Spinners).
     */
    @Serializable
    data object SourceIsUntapped : SourceProjectionCondition

    /**
     * The source permanent's controller has lost life this turn.
     * Used for "has [keyword] as long as you've lost life this turn."
     */
    @Serializable
    data object ControllerLostLifeThisTurn : SourceProjectionCondition

    /**
     * Any player controls a permanent matching the given filter.
     * Used for "gets +X/+Y as long as any player controls a [color] permanent."
     */
    @Serializable
    data class AnyPlayerControlsPermanentMatchingFilter(
        val filter: GameObjectFilter
    ) : SourceProjectionCondition

    /**
     * The source permanent's controller controls a permanent matching the given filter.
     * Used for "as long as you control a [filter]" conditions.
     *
     * When [excludeSelf] is true, the source permanent itself is not counted, supporting
     * "another" wording (e.g., "as long as another creature entered the battlefield under your
     * control this turn").
     */
    @Serializable
    data class ControllerControlsPermanentMatchingFilter(
        val filter: GameObjectFilter,
        val excludeSelf: Boolean = false
    ) : SourceProjectionCondition

    /**
     * Negation wrapper for source projection conditions.
     * Used for "otherwise" clauses (e.g., "Otherwise, it gets -3/-3").
     */
    @Serializable
    data class Not(val condition: SourceProjectionCondition) : SourceProjectionCondition

    /**
     * The source permanent entered the battlefield this turn.
     * Used for "as long as this Aura entered this turn" conditions.
     */
    @Serializable
    data object SourceEnteredThisTurn : SourceProjectionCondition

    /**
     * The source permanent is modified (has counters, Equipment, or Auras its controller controls).
     * Used for "has [keyword] as long as it's modified" conditions.
     */
    @Serializable
    data object SourceIsModified : SourceProjectionCondition

    /**
     * Compare two DynamicAmount values using a comparison operator.
     * Used for "as long as there are two or more instant and/or sorcery cards in your graveyard."
     */
    @Serializable
    data class Compare(
        val left: DynamicAmount,
        val operator: ComparisonOperator,
        val right: DynamicAmount
    ) : SourceProjectionCondition
}

/**
 * The layers in which continuous effects are applied (Rule 613).
 */
@Serializable
enum class Layer {
    COPY,           // Layer 1
    CONTROL,        // Layer 2
    TEXT,           // Layer 3
    TYPE,           // Layer 4
    COLOR,          // Layer 5
    ABILITY,        // Layer 6
    POWER_TOUGHNESS // Layer 7
}

/**
 * Sublayers for layer 7 (power/toughness).
 */
@Serializable
enum class Sublayer {
    CHARACTERISTIC_DEFINING,  // 7a
    SET_VALUES,               // 7b
    MODIFICATIONS,            // 7c
    COUNTERS,                 // 7d
    SWITCH                    // 7e
}

/**
 * Types of modifications that can be applied by continuous effects.
 *
 * Each modification declares its own [layer] and [sublayer], making the Rule 613 layer
 * assignment explicit and self-documenting. This prevents mismatches between the modification
 * type and the layer it's applied in.
 */
@Serializable
sealed interface Modification {
    /** The Rule 613 layer this modification applies in. */
    val layer: Layer
    /** The sublayer within Layer 7 (P/T), or null for other layers. */
    val sublayer: Sublayer? get() = null

    // --- Layer 2: Control-changing ---

    @Serializable
    data class ChangeController(val newControllerId: EntityId) : Modification {
        override val layer get() = Layer.CONTROL
    }

    /**
     * Change controller to whoever controls the source of this effect.
     * Used for Aura effects like "You control enchanted permanent" where
     * the controller is resolved dynamically at projection time.
     */
    @Serializable
    data object ChangeControllerToSourceController : Modification {
        override val layer get() = Layer.CONTROL
    }

    // --- Layer 4: Type-changing ---

    @Serializable
    data class AddType(val type: String) : Modification {
        override val layer get() = Layer.TYPE
    }
    @Serializable
    data class RemoveType(val type: String) : Modification {
        override val layer get() = Layer.TYPE
    }

    /**
     * Add a subtype (also adds to types set).
     * Used for effects like "is a Wall in addition to its other creature types."
     */
    @Serializable
    data class AddSubtype(val subtype: String) : Modification {
        override val layer get() = Layer.TYPE
    }

    /**
     * Replace all creature subtypes with the given set.
     * Used by "becomes the creature type of your choice" effects.
     */
    @Serializable
    data class SetCreatureSubtypes(val subtypes: Set<String>) : Modification {
        override val layer get() = Layer.TYPE
    }

    /**
     * Replace all basic land subtypes with the given set (Rule 305.7).
     * Used by "is an Island" effects that change a land's basic land types.
     * Removes existing basic land subtypes (Plains, Island, Swamp, Mountain, Forest)
     * and replaces them with the specified types.
     */
    @Serializable
    data class SetBasicLandTypes(val subtypes: Set<String>) : Modification {
        override val layer get() = Layer.TYPE
    }

    /**
     * Replace ALL card types with the given set.
     * Used for "is a Food artifact" effects that completely replace card types.
     * Removes all existing card types (Creature, Land, Enchantment, etc.)
     * and replaces them with the specified types.
     */
    @Serializable
    data class SetCardTypes(val types: Set<String>) : Modification {
        override val layer get() = Layer.TYPE
    }

    /**
     * Replace ALL subtypes with the given set.
     * Used for "is a Food artifact" effects that completely replace subtypes.
     * Removes all existing subtypes and replaces them with the specified types.
     */
    @Serializable
    data class SetAllSubtypes(val subtypes: Set<String>) : Modification {
        override val layer get() = Layer.TYPE
    }

    // --- Layer 5: Color-changing ---

    @Serializable
    data class ChangeColor(val colors: Set<String>) : Modification {
        override val layer get() = Layer.COLOR
    }
    @Serializable
    data class AddColor(val colors: Set<String>) : Modification {
        override val layer get() = Layer.COLOR
    }

    /**
     * Adds the chosen color (resolved dynamically from source's ChosenColorComponent).
     * Used for Shimmerwilds Growth: "Enchanted land is the chosen color."
     * If the source has no chosen color, no modification is applied.
     */
    @Serializable
    data object AddChosenColor : Modification {
        override val layer get() = Layer.COLOR
    }

    // --- Layer 6: Ability-adding/removing ---

    @Serializable
    data class GrantKeyword(val keyword: String) : Modification {
        override val layer get() = Layer.ABILITY
    }
    @Serializable
    data class RemoveKeyword(val keyword: String) : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Removes all abilities from the affected entity.
     * Used for effects like Deep Freeze ("loses all other abilities") and Turn to Frog.
     * Clears all keywords and sets the lostAllAbilities flag which suppresses
     * activated abilities, triggered abilities, and static abilities.
     */
    @Serializable
    data object RemoveAllAbilities : Modification {
        override val layer get() = Layer.ABILITY
    }

    @Serializable
    data class GrantProtectionFromColor(val color: String) : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Grants protection from the chosen color (resolved dynamically from source's ChosenColorComponent).
     * Used for Ward Sliver: "All Slivers have protection from the chosen color."
     */
    @Serializable
    data object GrantProtectionFromChosenColor : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Grants "hexproof from each of its colors" to each affected entity. Read at apply-time:
     * for every color the entity currently has (post-Layer 5), adds the keyword
     * `HEXPROOF_FROM_<COLOR>` to its keyword set. A colorless entity gains nothing.
     * Used for Tam, Mindful First-Year.
     */
    @Serializable
    data object GrantHexproofFromOwnColors : Modification {
        override val layer get() = Layer.ABILITY
    }

    @Serializable
    data object SetCantAttack : Modification {
        override val layer get() = Layer.ABILITY
    }
    @Serializable
    data object SetCantBlock : Modification {
        override val layer get() = Layer.ABILITY
    }

    @Serializable
    data object SetMustAttack : Modification {
        override val layer get() = Layer.ABILITY
    }
    @Serializable
    data object SetMustBlock : Modification {
        override val layer get() = Layer.ABILITY
    }

    /** Grants "can block an additional N creatures" to affected entities. Cumulative. */
    @Serializable
    data class CanBlockAdditional(val count: Int = 1) : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Blocking restriction: creature can only be blocked by creatures with a specific subtype.
     * Used for Shifting Sliver: "Slivers can't be blocked except by Slivers."
     */
    @Serializable
    data class CantBeBlockedExceptBySubtype(val subtype: String) : Modification {
        override val layer get() = Layer.ABILITY
    }

    // --- Layer 7: Power/toughness ---

    @Serializable
    data class SetPowerToughness(val power: Int, val toughness: Int) : Modification {
        override val layer get() = Layer.POWER_TOUGHNESS
        override val sublayer get() = Sublayer.SET_VALUES
    }
    @Serializable
    data class SetPower(val power: Int) : Modification {
        override val layer get() = Layer.POWER_TOUGHNESS
        override val sublayer get() = Sublayer.SET_VALUES
    }
    @Serializable
    data class SetToughness(val toughness: Int) : Modification {
        override val layer get() = Layer.POWER_TOUGHNESS
        override val sublayer get() = Sublayer.SET_VALUES
    }
    @Serializable
    data class ModifyPowerToughness(val powerMod: Int, val toughnessMod: Int) : Modification {
        override val layer get() = Layer.POWER_TOUGHNESS
        override val sublayer get() = Sublayer.MODIFICATIONS
    }
    @Serializable
    data class SwitchPowerToughness(val targetId: EntityId) : Modification {
        override val layer get() = Layer.POWER_TOUGHNESS
        override val sublayer get() = Sublayer.SWITCH
    }

    /**
     * Dynamic power/toughness modification based on a DynamicAmount.
     * The actual modification is computed at projection time by evaluating the DynamicAmount.
     * Used for effects like "gets +2/+2 for each face-down creature on the battlefield."
     */
    @Serializable
    data class ModifyPowerToughnessDynamic(
        val powerBonus: DynamicAmount,
        val toughnessBonus: DynamicAmount
    ) : Modification {
        override val layer get() = Layer.POWER_TOUGHNESS
        override val sublayer get() = Sublayer.MODIFICATIONS
    }

    // --- No-op ---

    /** No-op modification for effects that don't modify projected state (e.g., combat restrictions) */
    @Serializable
    data object NoOp : Modification {
        override val layer get() = Layer.ABILITY
    }
}

/**
 * Mutable projected values during calculation.
 */
internal data class MutableProjectedValues(
    var power: Int? = null,
    var toughness: Int? = null,
    val keywords: MutableSet<String> = mutableSetOf(),
    val colors: MutableSet<String> = mutableSetOf(),
    val types: MutableSet<String> = mutableSetOf(),
    val subtypes: MutableSet<String> = mutableSetOf(),
    var controllerId: EntityId? = null,
    var isFaceDown: Boolean = false,
    var cantAttack: Boolean = false,
    var cantBlock: Boolean = false,
    var mustAttack: Boolean = false,
    var mustBlock: Boolean = false,
    val cantBeBlockedExceptBySubtypes: MutableSet<String> = mutableSetOf(),
    var additionalBlockCount: Int = 0,
    var lostAllAbilities: Boolean = false
)
