package com.wingedsheep.engine.mechanics.layers

import com.wingedsheep.engine.state.Component
import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.model.EntityId
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.conditions.ComparisonOperator
import com.wingedsheep.sdk.scripting.conditions.Condition
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.text.TextReplacer
import com.wingedsheep.sdk.scripting.values.DynamicAmount
import kotlinx.serialization.Serializable

/**
 * Component that stores continuous effects generated by a permanent.
 */
@Serializable
data class ContinuousEffectSourceComponent(
    val effects: List<ContinuousEffectData>
) : Component

/**
 * Data for a single continuous effect.
 *
 * The [layer] and [sublayer] are derived from the [modification], which declares
 * its own Rule 613 layer. This ensures the layer assignment is always consistent
 * with the modification type.
 */
@Serializable
data class ContinuousEffectData(
    val modification: Modification,
    val affectsFilter: AffectsFilter? = null,
    val sourceCondition: Condition? = null
) {
    val layer: Layer get() = modification.layer
    val sublayer: Sublayer? get() = modification.sublayer
}

/**
 * Filter for determining which entities are affected.
 */
@Serializable
sealed interface AffectsFilter {

    /** Identity by default; cases holding a filter override to recurse. */
    fun applyTextReplacement(replacer: TextReplacer): AffectsFilter = this

    @Serializable
    data object Self : AffectsFilter {
    }
    @Serializable
    data object AllCreatures : AffectsFilter {
    }
    @Serializable
    data object AllCreaturesYouControl : AffectsFilter {
    }
    @Serializable
    data object AllCreaturesOpponentsControl : AffectsFilter {
    }
    @Serializable
    data class SpecificEntities(val entityIds: Set<EntityId>) : AffectsFilter {
    }
    @Serializable
    data class WithSubtype(val subtype: String) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter {
            val new = replacer.replaceCreatureType(subtype)
            return if (new == subtype) this else WithSubtype(new)
        }
    }

    /**
     * Other creatures with a specific subtype (excludes the source permanent).
     * Used for lord effects like "Other Bird creatures get +1/+1."
     */
    @Serializable
    data class OtherCreaturesWithSubtype(val subtype: String) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter {
            val new = replacer.replaceCreatureType(subtype)
            return if (new == subtype) this else OtherCreaturesWithSubtype(new)
        }
    }

    /**
     * Other tapped creatures you control (excludes the source permanent).
     * Used for effects like "Other tapped creatures you control have indestructible."
     */
    @Serializable
    data object OtherTappedCreaturesYouControl : AffectsFilter {
    }

    /**
     * Other creatures you control (excludes the source permanent).
     * Used for lord effects like "Other creatures you control get +1/+1."
     */
    @Serializable
    data object OtherCreaturesYouControl : AffectsFilter {
    }

    /**
     * All other creatures (excludes the source permanent).
     */
    @Serializable
    data object AllOtherCreatures : AffectsFilter {
    }

    /**
     * The permanent this Aura is attached to.
     * Used for Aura effects like "You control enchanted permanent."
     */
    @Serializable
    data object AttachedPermanent : AffectsFilter {
    }

    /**
     * All creatures that have a specific counter type.
     * Used for Aurification: "Each creature with a gold counter on it..."
     */
    @Serializable
    data class CreaturesWithCounter(val counterType: String) : AffectsFilter {
    }

    /**
     * All creatures you control that have a specific counter type.
     * Used for outlast lords: "Each creature you control with a +1/+1 counter on it has reach."
     */
    @Serializable
    data class OwnCreaturesWithCounter(val counterType: String) : AffectsFilter {
    }

    /**
     * All lands that have a specific counter type.
     * Used for Eluge: "Each land with a flood counter on it is an Island."
     */
    @Serializable
    data class LandsWithCounter(val counterType: String) : AffectsFilter {
    }

    /**
     * All face-down creatures.
     * Used for Ixidor, Reality Sculptor: "Face-down creatures get +1/+1."
     */
    @Serializable
    data object FaceDownCreatures : AffectsFilter {
    }

    /**
     * Generic filter that preserves the full GroupFilter and evaluates it
     * against in-progress projected values during state projection.
     * Used as a fallback when specific AffectsFilter variants don't cover
     * the predicate combination (e.g., subtype + controller together).
     */
    @Serializable
    data class Generic(val groupFilter: GroupFilter) : AffectsFilter {
        override fun applyTextReplacement(replacer: TextReplacer): AffectsFilter {
            val new = groupFilter.applyTextReplacement(replacer)
            return if (new === groupFilter) this else Generic(new)
        }
    }
}

/**
 * Represents an active continuous effect during state projection.
 *
 * The [layer] and [sublayer] are derived from the [modification].
 */
@Serializable
data class ContinuousEffect(
    val sourceId: EntityId,
    val timestamp: Long,
    val modification: Modification,
    val affectedEntities: Set<EntityId> = emptySet(),
    val sourceCondition: Condition? = null,
    val affectsFilter: AffectsFilter? = null,
    /**
     * When non-null, this effect applies only to affected entities whose *projected* controller
     * is this player (a "for as long as you control it" gate, e.g. suspend haste — CR 702.62g).
     * Evaluated after Layer 2 control is established, so it tracks control-changing effects.
     */
    val controllerGate: EntityId? = null,
    /**
     * When non-null, the entire effect drops the moment the *source's* projected controller
     * is no longer this player (a "for as long as you control this [source]" gate — Aladdin,
     * Scroll of Isildur Chapter I, etc.). Sibling of [controllerGate] but gated on the source
     * rather than per-affected-entity. Evaluated after Layer 2 control is established, so it
     * tracks every flavor of control-changing effect.
     */
    val sourceControllerGate: EntityId? = null,
    /**
     * Controller captured when the effect was created, used as a fallback when the source has
     * left the battlefield (so its [ControllerComponent] is gone). Needed for floating effects
     * that outlive their source — e.g. Titania's Song's "this effect continues until end of
     * turn" linger, whose Layer-7b dynamic P/T must still resolve a controller for the
     * [EffectContext] after the enchantment has left. Null for static-ability effects, which
     * always resolve their controller from the source permanent on the battlefield.
     */
    val controllerId: EntityId? = null
) {
    val layer: Layer get() = modification.layer
    val sublayer: Sublayer? get() = modification.sublayer
}

/**
 * The layers in which continuous effects are applied (Rule 613).
 */
@Serializable
enum class Layer {
    COPY,           // Layer 1
    CONTROL,        // Layer 2
    TEXT,           // Layer 3
    TYPE,           // Layer 4
    COLOR,          // Layer 5
    ABILITY,        // Layer 6
    POWER_TOUGHNESS // Layer 7
}

/**
 * Sublayers for layer 7 (power/toughness).
 */
@Serializable
enum class Sublayer {
    CHARACTERISTIC_DEFINING,  // 7a
    SET_VALUES,               // 7b
    MODIFICATIONS,            // 7c
    COUNTERS,                 // 7d
    SWITCH                    // 7e
}

/**
 * Types of modifications that can be applied by continuous effects.
 *
 * Each modification declares its own [layer] and [sublayer], making the Rule 613 layer
 * assignment explicit and self-documenting. This prevents mismatches between the modification
 * type and the layer it's applied in.
 */
@Serializable
sealed interface Modification {
    /** The Rule 613 layer this modification applies in. */
    val layer: Layer
    /** The sublayer within Layer 7 (P/T), or null for other layers. */
    val sublayer: Sublayer? get() = null

    // --- Layer 2: Control-changing ---

    @Serializable
    data class ChangeController(val newControllerId: EntityId) : Modification {
        override val layer get() = Layer.CONTROL
    }

    /**
     * Change controller to whoever controls the source of this effect.
     * Used for Aura effects like "You control enchanted permanent" where
     * the controller is resolved dynamically at projection time.
     */
    @Serializable
    data object ChangeControllerToSourceController : Modification {
        override val layer get() = Layer.CONTROL
    }

    // --- Layer 3: Text-changing ---

    /**
     * Sets the affected object's name, overwriting any name it had (CR 612.8: "That object
     * loses any names it had and has only the specified name"). Used by Witness Protection
     * ("...named Legitimate Businessperson"); the [com.wingedsheep.sdk.scripting.TransformPermanent]
     * facade's `setName` lowers to this.
     */
    @Serializable
    data class SetName(val name: String) : Modification {
        override val layer get() = Layer.TEXT
    }

    // --- Layer 4: Type-changing ---

    @Serializable
    data class AddType(val type: String) : Modification {
        override val layer get() = Layer.TYPE
    }
    @Serializable
    data class RemoveType(val type: String) : Modification {
        override val layer get() = Layer.TYPE
    }

    /**
     * Add a subtype (also adds to types set).
     * Used for effects like "is a Wall in addition to its other creature types."
     */
    @Serializable
    data class AddSubtype(val subtype: String) : Modification {
        override val layer get() = Layer.TYPE
    }

    /**
     * Add the creature type chosen as the source entered (resolved dynamically from the
     * source's CastChoicesComponent) as a subtype, in addition to the affected entity's
     * other types. The chosen-value counterpart to [AddSubtype], mirroring [AddChosenColor].
     * Used by Leyline of Transformation: "Creatures you control are the chosen type in
     * addition to their other types." If the source has no chosen creature type, no
     * modification is applied.
     *
     * Layer 4 projection only ever touches battlefield permanents, so the two cross-zone
     * flags ([includeControlledSpells], [includeOwnedCardsOutsideBattlefield]) are not read
     * by [EffectApplicator]; they are read by [StateProjector] to register entries in
     * [ProjectedState.crossZoneSubtypeGrants], which the non-battlefield subtype read-sites
     * consult. See [com.wingedsheep.sdk.scripting.GrantChosenSubtype].
     */
    @Serializable
    data class AddChosenSubtype(
        val includeControlledSpells: Boolean = false,
        val includeOwnedCardsOutsideBattlefield: Boolean = false
    ) : Modification {
        override val layer get() = Layer.TYPE
    }

    /**
     * Add every creature type to the affected entity, in addition to its other
     * subtypes. Used for cards that say "is all creature types" without granting
     * the Changeling keyword (e.g., Stalactite Dagger).
     */
    @Serializable
    data object AddAllCreatureTypes : Modification {
        override val layer get() = Layer.TYPE
    }

    /**
     * Replace all creature subtypes with the given set.
     * Used by "becomes the creature type of your choice" effects.
     */
    @Serializable
    data class SetCreatureSubtypes(val subtypes: Set<String>) : Modification {
        override val layer get() = Layer.TYPE
    }

    /**
     * Replace all basic land subtypes with the given set (Rule 305.7).
     * Used by "is an Island" effects that change a land's basic land types.
     * Removes existing basic land subtypes (Plains, Island, Swamp, Mountain, Forest)
     * and replaces them with the specified types.
     */
    @Serializable
    data class SetBasicLandTypes(val subtypes: Set<String>) : Modification {
        override val layer get() = Layer.TYPE
    }

    /**
     * Replace all basic land subtypes with the type chosen as the source entered
     * (resolved dynamically from the source's CastChoicesComponent).
     * Used by Phantasmal Terrain: "Enchanted land is the chosen type."
     * The chosen-value counterpart to [SetBasicLandTypes], mirroring [AddChosenColor].
     * If the source has no chosen land type, no modification is applied.
     */
    @Serializable
    data object SetBasicLandTypesFromChosen : Modification {
        override val layer get() = Layer.TYPE
    }

    /**
     * Replace ALL card types with the given set.
     * Used for "is a Food artifact" effects that completely replace card types.
     * Removes all existing card types (Creature, Land, Enchantment, etc.)
     * and replaces them with the specified types.
     */
    @Serializable
    data class SetCardTypes(val types: Set<String>) : Modification {
        override val layer get() = Layer.TYPE
    }

    /**
     * Replace ALL subtypes with the given set.
     * Used for "is a Food artifact" effects that completely replace subtypes.
     * Removes all existing subtypes and replaces them with the specified types.
     */
    @Serializable
    data class SetAllSubtypes(val subtypes: Set<String>) : Modification {
        override val layer get() = Layer.TYPE
    }

    // --- Layer 5: Color-changing ---

    @Serializable
    data class ChangeColor(val colors: Set<String>) : Modification {
        override val layer get() = Layer.COLOR
    }
    @Serializable
    data class AddColor(val colors: Set<String>) : Modification {
        override val layer get() = Layer.COLOR
    }

    /**
     * Adds the chosen color (resolved dynamically from source's CastChoicesComponent).
     * Used for Shimmerwilds Growth: "Enchanted land is the chosen color."
     * If the source has no chosen color, no modification is applied.
     */
    @Serializable
    data object AddChosenColor : Modification {
        override val layer get() = Layer.COLOR
    }

    // --- Layer 6: Ability-adding/removing ---

    @Serializable
    data class GrantKeyword(val keyword: String) : Modification {
        override val layer get() = Layer.ABILITY
    }
    @Serializable
    data class RemoveKeyword(val keyword: String) : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Removes all abilities from the affected entity.
     * Used for effects like Deep Freeze ("loses all other abilities") and Turn to Frog.
     * Clears all keywords and sets the lostAllAbilities flag which suppresses
     * activated abilities, triggered abilities, and static abilities.
     */
    @Serializable
    data object RemoveAllAbilities : Modification {
        override val layer get() = Layer.ABILITY
    }

    @Serializable
    data class GrantProtectionFromColor(val color: String) : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Grants protection from a card type (e.g. "protection from creatures"). [cardType] is the
     * uppercase card-type name; realized as a `PROTECTION_FROM_CARDTYPE_<TYPE>` keyword.
     */
    @Serializable
    data class GrantProtectionFromCardType(val cardType: String) : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Grants protection from the chosen color (resolved dynamically from source's CastChoicesComponent).
     * Used for Ward Sliver: "All Slivers have protection from the chosen color."
     */
    @Serializable
    data object GrantProtectionFromChosenColor : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Grants the landwalk keyword matching the source's chosen basic land type (resolved at
     * apply-time from the source's `CastChoicesComponent`): Plains→PLAINSWALK, Island→ISLANDWALK,
     * Swamp→SWAMPWALK, Mountain→MOUNTAINWALK, Forest→FORESTWALK. Used for Traveler's Cloak. The
     * chosen-value counterpart to [GrantKeyword]. If the source has no chosen land type (or an
     * unrecognized one), nothing is granted.
     */
    @Serializable
    data object GrantLandwalkFromChosen : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Grants "hexproof from each of its colors" to each affected entity. Read at apply-time:
     * for every color the entity currently has (post-Layer 5), adds the keyword
     * `HEXPROOF_FROM_<COLOR>` to its keyword set. A colorless entity gains nothing.
     * Used for Tam, Mindful First-Year.
     */
    @Serializable
    data object GrantHexproofFromOwnColors : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Grants "hexproof from monocolored" to each affected entity — adds the keyword
     * `HEXPROOF_FROM_MONOCOLORED`, which blocks targeting by monocolored (exactly one color)
     * spells and abilities opponents control. Used for Dragonfire Blade.
     */
    @Serializable
    data object GrantHexproofFromMonocolored : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Grants each affected entity "protection from the colors of permanents the source's
     * controller controls". Read at apply-time: collects the projected colors of every
     * battlefield permanent controlled by the source's (projected) controller, then adds
     * `PROTECTION_FROM_<COLOR>` for each. Applied in Layer 6 (ABILITY) after Layer 5 colors
     * are final, so it tracks the controller's board in real time. Used for Pledge of Loyalty.
     */
    @Serializable
    data object GrantProtectionFromControlledColors : Modification {
        override val layer get() = Layer.ABILITY
    }

    @Serializable
    data object SetCantAttack : Modification {
        override val layer get() = Layer.ABILITY
    }
    @Serializable
    data object SetCantBlock : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Marks a permanent as suspected — the first-class named status for the suspect mechanic.
     * Applied together with [GrantKeyword](Menace) and [SetCantBlock] by [SuspectEffectHandler].
     * Stored as a distinct modification so future cards can query or remove the status
     * independently of the granted abilities.
     */
    @Serializable
    data object SetSuspected : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Prevents the affected permanent from being turned face up (CR-style "it can't be turned
     * face up"). Used by Unable to Scream: "As long as enchanted creature is face down, it can't
     * be turned face up." Only meaningful while the permanent is face down; [TurnFaceUpHandler]
     * rejects the special action when this flag is projected onto the source.
     */
    @Serializable
    data object SetCantBeTurnedFaceUp : Modification {
        override val layer get() = Layer.ABILITY
    }

    @Serializable
    data object SetMustAttack : Modification {
        override val layer get() = Layer.ABILITY
    }
    @Serializable
    data object SetMustBlock : Modification {
        override val layer get() = Layer.ABILITY
    }

    /** Grants "can block an additional N creatures" to affected entities. Cumulative. */
    @Serializable
    data class CanBlockAdditional(val count: Int = 1) : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Blocking restriction: creature can only be blocked by creatures matching the filter.
     * Generalized "can't be blocked except by X" — used for Shifting Sliver
     * ("Slivers can't be blocked except by Slivers"), Realm of Koh's Spirit token
     * ("can't be blocked by non-Spirit creatures"), and any analogous restriction.
     */
    @Serializable
    data class CantBeBlockedExceptBy(val blockerFilter: GameObjectFilter) : Modification {
        override val layer get() = Layer.ABILITY
    }

    /**
     * Blocking restriction: creature can only block creatures matching the filter.
     * Generalized "can block only X creatures" — used for tokens and printed cards alike
     * (e.g., the Spirit token from Realm of Koh: "can't block ... non-Spirit creatures").
     */
    @Serializable
    data class CanOnlyBlockCreaturesWith(val blockerFilter: GameObjectFilter) : Modification {
        override val layer get() = Layer.ABILITY
    }

    // --- Layer 7: Power/toughness ---

    @Serializable
    data class SetPowerToughness(val power: Int, val toughness: Int) : Modification {
        override val layer get() = Layer.POWER_TOUGHNESS
        override val sublayer get() = Sublayer.SET_VALUES
    }
    @Serializable
    data class SetPower(val power: Int) : Modification {
        override val layer get() = Layer.POWER_TOUGHNESS
        override val sublayer get() = Sublayer.SET_VALUES
    }
    @Serializable
    data class SetToughness(val toughness: Int) : Modification {
        override val layer get() = Layer.POWER_TOUGHNESS
        override val sublayer get() = Sublayer.SET_VALUES
    }
    @Serializable
    data class ModifyPowerToughness(val powerMod: Int, val toughnessMod: Int) : Modification {
        override val layer get() = Layer.POWER_TOUGHNESS
        override val sublayer get() = Sublayer.MODIFICATIONS
    }
    @Serializable
    data class SwitchPowerToughness(val targetId: EntityId) : Modification {
        override val layer get() = Layer.POWER_TOUGHNESS
        override val sublayer get() = Sublayer.SWITCH
    }

    /**
     * Dynamic base power/toughness *setting* (characteristic-defining ability) — Layer 7b
     * (SET_VALUES). The amounts are computed at projection time by evaluating the DynamicAmounts.
     * Distinct from [ModifyPowerToughnessDynamic], which is a Layer 7c additive bonus. Used for
     * star/star CDAs like Beau ("power and toughness each equal to the number of lands you control").
     */
    @Serializable
    data class SetPowerToughnessDynamic(
        val power: DynamicAmount,
        val toughness: DynamicAmount
    ) : Modification {
        override val layer get() = Layer.POWER_TOUGHNESS
        override val sublayer get() = Sublayer.SET_VALUES
    }

    /**
     * Dynamic power/toughness modification based on a DynamicAmount.
     * The actual modification is computed at projection time by evaluating the DynamicAmount.
     * Used for effects like "gets +2/+2 for each face-down creature on the battlefield."
     */
    @Serializable
    data class ModifyPowerToughnessDynamic(
        val powerBonus: DynamicAmount,
        val toughnessBonus: DynamicAmount
    ) : Modification {
        override val layer get() = Layer.POWER_TOUGHNESS
        override val sublayer get() = Sublayer.MODIFICATIONS
    }

    // --- No-op ---

    /** No-op modification for effects that don't modify projected state (e.g., combat restrictions) */
    @Serializable
    data object NoOp : Modification {
        override val layer get() = Layer.ABILITY
    }
}

/**
 * Mutable projected values during calculation.
 */
internal data class MutableProjectedValues(
    var power: Int? = null,
    var toughness: Int? = null,
    var name: String? = null,
    val keywords: MutableSet<String> = mutableSetOf(),
    val colors: MutableSet<String> = mutableSetOf(),
    val types: MutableSet<String> = mutableSetOf(),
    val subtypes: MutableSet<String> = mutableSetOf(),
    var controllerId: EntityId? = null,
    var isFaceDown: Boolean = false,
    var isSuspected: Boolean = false,
    var cantAttack: Boolean = false,
    var cantBlock: Boolean = false,
    var cantBeTurnedFaceUp: Boolean = false,
    var mustAttack: Boolean = false,
    var mustBlock: Boolean = false,
    val cantBeBlockedExceptByFilters: MutableList<GameObjectFilter> = mutableListOf(),
    val canOnlyBlockCreaturesWithFilters: MutableList<GameObjectFilter> = mutableListOf(),
    var additionalBlockCount: Int = 0,
    var lostAllAbilities: Boolean = false,
    /** See [com.wingedsheep.engine.mechanics.layers.ProjectedValues.basicLandTypesSetByEffect]. */
    var basicLandTypesSetByEffect: Boolean = false
)
