package com.wingedsheep.mtg.sets.definitions.bloomburrow

import com.wingedsheep.mtg.sets.definitions.bloomburrow.cards.*

/**
 * Bloomburrow Set (2024)
 *
 * Bloomburrow is a plane inhabited entirely by anthropomorphic animals.
 * The set features a variety of creature types including Mice, Rabbits,
 * Frogs, Otters, and more.
 *
 * Set Code: BLB
 * Release Date: August 2, 2024
 * Card Count: 266
 */
object BloomburrowSet {

    const val SET_CODE = "BLB"
    const val SET_NAME = "Bloomburrow"

    /**
     * All cards implemented from this set.
     */
    val basicLands = BloomburrowBasicLands.map { it.copy(setCode = SET_CODE) }

    val allCards = listOf(
        AlaniaDivergentStorm,
        AlaniasPathmaker,
        AgateAssault,
        AgateBladeAssassin,
        ArtistsTalent,
        AzureBeastbinder,
        BanditsTalent,
        BanishingLight,
        BarkKnuckleBoxer,
        BonecacheOverseer,
        BarkformHarvester,
        BaylenTheHaymaker,
        BellowingCrier,
        BloomingBlast,
        BonebindOrator,
        BuildersTalent,
        BrambleguardCaptain,
        BrambleguardVeteran,
        BrazenCollector,
        BraveKinDuo,
        BrightbladeStoat,
        BurrowguardMentor,
        BushyBodyguard,
        BywayBarterer,
        CinderingCutthroat,
        ClifftopLookout,
        ClementTheWorrywort,
        ConductElectricity,
        CruelclawsHeist,
        CamelliaTheSeedmiser,
        CaretakersTalent,
        CorpseberryCultivator,
        CoruscationMage,
        CrumbAndGetIt,
        CuriousForager,
        DaggerfangDuo,
        DarkstarAugur,
        DazzlingDenial,
        DawnsTruce,
        DireDowndraft,
        Diresight,
        DourPortMage,
        DownwindAmbusher,
        DragonhawkFatesTempest,
        DreamdewEntrancer,
        DruidOfTheSpade,
        DriftgloomCoyote,
        EarlyWinter,
        EmberheartChallenger,
        EddymurkCrab,
        FabledPassage,
        FeedTheCycle,
        Fell,
        FeatherOfFlight,
        FecundGreenshell,
        FireglassMentor,
        FlamecacheGecko,
        FrilledSparkshooter,
        FlowerfootSwordmaster,
        ForTheCommonGood,
        Fountainport,
        FountainportBell,
        GalewindMoose,
        GlidediveDuo,
        GevScaledScorch,
        GossipsTalent,
        HeadOfTheHomestead,
        HazardrootHerbalist,
        HazelsNocturne,
        HeapedHarvest,
        HearthbornBattler,
        HeirloomEpic,
        HelgaSkittishSeer,
        HiddenGrotto,
        HighStride,
        HiredClaw,
        HopToIt,
        HivespineWolverine,
        HoardersOverflow,
        HonoredDreyleader,
        HugsGrislyGuardian,
        IntrepidRabbit,
        IntoTheFloodMaw,
        IridescentVinelasher,
        JackdawSavior,
        JunkbladeBruiser,
        KastralTheWindcrested,
        KindlesparkDuo,
        Kitnap,
        Knightfisher,
        HuntersTalent,
        Mindwhisker,
        MindSpiral,
        LightshellDuo,
        LifecreedDuo,
        LilypadVillage,
        LongRiversPull,
        LongstalkBrawl,
        LunarConvocation,
        LupinflowerVillage,
        MabelsMettle,
        MahaItsFeathersNight,
        ManifoldMouse,
        MightOfTheMeek,
        MoonriseCleric,
        MoonstoneHarbinger,
        MouseTrapper,
        MudflatVillage,
        MuerraTrashTactician,
        NocturnalHunger,
        NettleGuard,
        NightwhorlHermit,
        PawpatchRecruit,
        PatchworkBanner,
        PawpatchFormation,
        PileatedProvisioner,
        Overprotect,
        OakhollowVillage,
        OsteomancerAdept,
        PearlOfWisdom,
        PondProphet,
        PlayfulShove,
        PlumecreedEscort,
        PlumecreedMentor,
        PsychicWhorl,
        SalvationSwan,
        RuthlessNegotiation,
        QuaketuskBoar,
        RaccoonRallier,
        RabbitResponse,
        RabidGnaw,
        RavineRaider,
        RepelCalamity,
        ReptilianRecruiter,
        RockfaceVillage,
        RoughshodDuo,
        RustShieldRampager,
        RunAwayTogether,
        Savor,
        SazacapsBrew,
        ScalesOfShale,
        ScavengersTalent,
        SeasonOfGathering,
        SeasonOfLoss,
        SeasonOfWeaving,
        SeasonedWarrenguard,
        SeedpodSquire,
        SeedglaiveMentor,
        ShortBow,
        ShrikeForce,
        ShoreUp,
        ShorelineLooter,
        SinisterMonolith,
        SonarStrike,
        Spellgyre,
        SkyskipperDuo,
        SplashLasher,
        SplashPortal,
        StickytongueSentinel,
        StockingThePantry,
        SugarCoat,
        StarCharter,
        Stargaze,
        StarscapeCleric,
        SteampathCharger,
        StormcatchMentor,
        StormchasersTalent,
        SunshowerDruid,
        SunspineLynx,
        TakeOutTheTrash,
        TangleTumbler,
        TempestAngler,
        TenderWildguide,
        ThistledownPlayers,
        TidecallerMentor,
        ThornplateIntimidator,
        ThornvaultForager,
        ThoughtShucker,
        ThreeTreeRootweaver,
        ThreeTreeScribe,
        TreeguardDuo,
        ThundertrapTrainer,
        ValleyFloodcaller,
        ValleyMightcaller,
        ValleyQuestcaller,
        ValleyRally,
        ValleyRotcaller,
        VinereapMentor,
        VrenTheRelentless,
        WaterspoutWarden,
        WarSqueak,
        WarrenElder,
        WarrenWarleader,
        WaxWaneWitness,
        WearDown,
        WhiskerquillScribe,
        WhiskervaleForerunner,
        WildfireHowl,
        WickTheWhorledMind,
        WicksPatrol,
        YgraEaterOfAll,
        ZoralineCosmosCaller,

        // Basic lands
    ) + BloomburrowBasicLands
}
