// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mid.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility


/**
 * Join the Dance
 * {G}{W}
 * Sorcery
 * Create two 1/1 white Human creature tokens.
 * Flashback {3}{G}{W} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val JoinTheDance = card("Join the Dance") {
    manaCost = "{G}{W}"
    colorIdentity = "WG"
    typeLine = "Sorcery"
    oracleText = "Create two 1/1 white Human creature tokens.\nFlashback {3}{G}{W} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        effect = Effects.CreateToken(
            power = 1,
            toughness = 1,
            colors = setOf(Color.WHITE),
            creatureTypes = setOf("Human"),
            count = 2
        )
    }
    keywordAbility(KeywordAbility.flashback("{3}{G}{W}"))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "229"
        artist = "Raoul Vitale"
        flavorText = "\"We can go into the dark hand-in-hand or alone. I know which I prefer.\""
        imageUri = "https://cards.scryfall.io/normal/front/5/6/56b30a99-601b-40b9-b012-30fa4be5fd3c.jpg"
    }
}
