// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.hob.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Front Porch Sentries
 * {1}{B}
 * Creature — Goblin Soldier
 * 2/2
 * When this creature dies, target creature an opponent controls gets -1/-1 until end of turn.
 */
val FrontPorchSentries = card("Front Porch Sentries") {
    manaCost = "{1}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Goblin Soldier"
    oracleText = "When this creature dies, target creature an opponent controls gets -1/-1 until end of turn."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.Dies
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.opponentControls()))
        effect = Effects.ModifyStats(-1, -1, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "67"
        artist = "Stanislav Sherbakov"
        flavorText = "It was deep, deep dark, such as only Goblins that have taken to living in the heart of the mountain can see through."
        imageUri = "https://cards.scryfall.io/normal/front/0/7/07bfc803-e11b-47ab-9f25-0ace7e174200.jpg"
    }
}
