// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.hob.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.ModifyStats
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.effects.IfYouDoEffect
import com.wingedsheep.sdk.scripting.effects.MayEffect


/**
 * Ragged Short Spear
 * {1}{R}
 * Artifact — Equipment
 * When this Equipment enters, you may discard a card. If you do, draw two cards.
 * Equipped creature gets +2/+0.
 * Equip {3} ({3}: Attach to target creature you control. Equip only as a sorcery.)
 */
val RaggedShortSpear = card("Ragged Short Spear") {
    manaCost = "{1}{R}"
    colorIdentity = "R"
    typeLine = "Artifact — Equipment"
    oracleText = "When this Equipment enters, you may discard a card. If you do, draw two cards.\nEquipped creature gets +2/+0.\nEquip {3} ({3}: Attach to target creature you control. Equip only as a sorcery.)"
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = MayEffect(effect = IfYouDoEffect(action = Patterns.Hand.discardCards(1), ifYouDo = DrawCardsEffect(2)))
    }
    staticAbility {
        ability = ModifyStats(2, 0)
    }
    equipAbility("{3}")
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "108"
        artist = "Miklós Ligeti"
        flavorText = "Spears served Goblins better than swords or bows—they were quick to make and quiet to use."
        imageUri = "https://cards.scryfall.io/normal/front/7/b/7bf81a8b-52ad-49f5-a3d4-22613cad3a3d.jpg"
    }
}
