// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.hob.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Smaug's Fury
 * {1}{R}
 * Instant
 * Target creature gets +3/+0 and gains reach and first strike until end of turn.
 */
val SmaugsFury = card("Smaug's Fury") {
    manaCost = "{1}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Target creature gets +3/+0 and gains reach and first strike until end of turn."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Composite(
            Effects.ModifyStats(3, 0, t),
            Effects.GrantKeyword(Keyword.REACH, t),
            Effects.GrantKeyword(Keyword.FIRST_STRIKE, t)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "111"
        artist = "Andrea Piparo"
        flavorText = "The Dwarves had barely time to fly back to the tunnel when Smaug came hurtling from the north, licking the mountainsides with flame, beating his great wings with a noise like a roaring wind."
        imageUri = "https://cards.scryfall.io/normal/front/a/1/a16f203a-785e-4c78-9410-fb9f8a0ffa01.jpg"
    }
}
