// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.hob.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Thrór's Map
 * {2}
 * Legendary Artifact
 * When Thrór's Map enters, search your library for a basic land card, reveal it, put it into your hand, then shuffle.
 * {2}, {T}: Draw a card, then discard a card.
 */
val ThrorsMap = card("Thrór's Map") {
    manaCost = "{2}"
    colorIdentity = ""
    typeLine = "Legendary Artifact"
    oracleText = "When Thrór's Map enters, search your library for a basic land card, reveal it, put it into your hand, then shuffle.\n{2}, {T}: Draw a card, then discard a card."
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.BasicLand,
            destination = SearchDestination.HAND,
            reveal = true
        )
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}"), Costs.Tap)
        effect = Effects.Composite(
            DrawCardsEffect(1),
            Patterns.Hand.discardCards(1)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "179"
        artist = "Gaboleps"
        flavorText = "\"Stand by the grey stone when the thrush knocks,\" read Elrond, \"and the setting sun with the last light of Durin's Day will shine upon the keyhole.\""
        imageUri = "https://cards.scryfall.io/normal/front/a/d/ad0dba36-d056-4bc1-987a-391da26ad267.jpg"
    }
}
