// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.hob.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Troll Negotiations
 * {2}{G}{G}
 * Sorcery
 * Put two +1/+1 counters on target creature you control. Then it fights target creature an opponent controls. (Each deals damage equal to its power to the other.)
 */
val TrollNegotiations = card("Troll Negotiations") {
    manaCost = "{2}{G}{G}"
    colorIdentity = "G"
    typeLine = "Sorcery"
    oracleText = "Put two +1/+1 counters on target creature you control. Then it fights target creature an opponent controls. (Each deals damage equal to its power to the other.)"
    spell {
        val t1 = target("t1", TargetCreature(filter = TargetFilter.Creature.youControl()))
        val t2 = target("t2", TargetCreature(filter = TargetFilter.Creature.opponentControls()))
        effect = Effects.Composite(
            AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 2, target = t1),
            Effects.Fight(t1, t2)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "138"
        artist = "Wero Gallo"
        flavorText = "Suddenly they were fighting like dogs, and calling one another all sorts of perfectly true and applicable names in very loud voices."
        imageUri = "https://cards.scryfall.io/normal/front/c/a/ca0f7bf4-b8a2-4ec4-ad7e-b639de9fa76a.jpg"
    }
}
