// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.s99.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Eager Cadet
 * {W}
 * Creature — Human Soldier
 * 1/1
 */
val EagerCadet = card("Eager Cadet") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Soldier"
    power = 1
    toughness = 1
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "15"
        artist = "Scott M. Fischer"
        flavorText = "The enthusiasm of the young, sharpened by the discipline of a soldier."
        imageUri = "https://cards.scryfall.io/normal/front/d/1/d1e1ce2f-d8af-4fd0-975e-9d910d12b883.jpg"
    }
}
