package com.wingedsheep.mtg.sets.definitions.woe.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.effects.ManaRestriction

private val troyanManaRestriction = ManaRestriction.SpellsWithManaValueAtLeast(
    minManaValue = 5,
    orXInCost = true,
)

/**
 * Troyan, Gutsy Explorer
 * {1}{G}{U}
 * Legendary Creature — Vedalken Scout
 * 1/3
 *
 * {T}: Add {G}{U}. Spend this mana only to cast spells with mana value 5 or greater or spells with
 *   {X} in their mana costs.
 * {U}, {T}: Draw a card, then discard a card.
 *
 * Two {G}{U} is two separately restricted mana units, not one lump: the printed ruling says you don't
 * have to spend both on the same spell, which falls out of adding each colour as its own restricted
 * entry in the pool.
 *
 * The restriction is [ManaRestriction.SpellsWithManaValueAtLeast] at threshold 5 with the {X} clause
 * on. An {X} spell qualifies whatever its mana value (X counts as 0 on the stack, CR 202.3b), and the
 * mana may pay *any* part of such a spell's cost, not just the {X} portion — both per the rulings.
 *
 * The two abilities compete for the same tap, so this is deliberately not a Composite: each is its own
 * activated ability with `{T}` in its cost, and only one of them can be used per untap.
 */
val TroyanGutsyExplorer = card("Troyan, Gutsy Explorer") {
    manaCost = "{1}{G}{U}"
    colorIdentity = "GU"
    typeLine = "Legendary Creature — Vedalken Scout"
    power = 1
    toughness = 3
    oracleText = "{T}: Add {G}{U}. Spend this mana only to cast spells with mana value 5 or greater " +
        "or spells with {X} in their mana costs.\n" +
        "{U}, {T}: Draw a card, then discard a card."

    activatedAbility {
        cost = Costs.Tap
        effect = Effects.Composite(
            Effects.AddMana(Color.GREEN, 1, restriction = troyanManaRestriction),
            Effects.AddMana(Color.BLUE, 1, restriction = troyanManaRestriction),
        )
        manaAbility = true
        timing = TimingRule.ManaAbility
    }

    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{U}"), Costs.Tap)
        effect = Patterns.Hand.loot()
        description = "Draw a card, then discard a card."
    }

    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "217"
        artist = "Jesper Ejsing"
        flavorText = "\"The streets of Ravnica were stifling. Eldraine is an endless adventure paved " +
            "in gold.\""
        imageUri = "https://cards.scryfall.io/normal/front/e/a/eadd2a1a-93a0-4257-897d-1aaee279449f.jpg?1783915068"

        ruling("2023-09-01", "You don't have to spend the two mana on the same spell.")
        ruling(
            "2023-09-01",
            "You can spend mana generated by Troyan on any part of the cost of a spell that contains " +
                "{X} in its mana cost. You're not limited to spending it only on the {X} part."
        )
    }
}
