// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mmq.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.RegenerateEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Horned Troll
 * {2}{G}
 * Creature — Troll
 * 2/2
 * {G}: Regenerate this creature.
 */
val HornedTroll = card("Horned Troll") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Troll"
    oracleText = "{G}: Regenerate this creature."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.Mana("{G}")
        effect = RegenerateEffect(EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "251"
        artist = "Heather Hudson"
        flavorText = "\"If I says it's a troll, it's a troll. Goblins is always right in Mercadia.\"\n—Squee"
        imageUri = "https://cards.scryfall.io/normal/front/7/f/7f2a6d10-054e-4d6f-aeb7-4204f02490c7.jpg"
    }
}
