// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mmq.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Primeval Shambler
 * {4}{B}
 * Creature — Horror Mercenary
 * 3/3
 * {B}: This creature gets +1/+1 until end of turn.
 */
val PrimevalShambler = card("Primeval Shambler") {
    manaCost = "{4}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Horror Mercenary"
    oracleText = "{B}: This creature gets +1/+1 until end of turn."
    power = 3
    toughness = 3
    activatedAbility {
        cost = Costs.Mana("{B}")
        effect = Effects.ModifyStats(1, 1, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "152"
        artist = "Chippy"
        flavorText = "His mind, like his body, is made up of the swamp's flotsam."
        imageUri = "https://cards.scryfall.io/normal/front/5/d/5d6ed1fb-2f7d-4a21-bbf3-660cad631975.jpg"
    }
}
