// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mmq.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Vine Trellis
 * {1}{G}
 * Creature — Plant Wall
 * 0/4
 * Defender (This creature can't attack.)
 * {T}: Add {G}.
 */
val VineTrellis = card("Vine Trellis") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Plant Wall"
    oracleText = "Defender (This creature can't attack.)\n{T}: Add {G}."
    power = 0
    toughness = 4
    keywords(Keyword.DEFENDER)
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(Color.GREEN)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "285"
        artist = "DiTerlizzi"
        flavorText = "\"We protect our own with our own.\""
        imageUri = "https://cards.scryfall.io/normal/front/e/6/e660241f-0976-4206-8149-7dac8466a2a3.jpg"
    }
}
