// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dmu.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Bite Down
 * {1}{G}
 * Instant
 * Target creature you control deals damage equal to its power to target creature or planeswalker you don't control.
 */
val BiteDown = card("Bite Down") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Target creature you control deals damage equal to its power to target creature or planeswalker you don't control."
    spell {
        val t1 = target("target creature you control", TargetCreature(filter = TargetFilter.Creature.youControl()))
        val t2 = target(
            "target creature or planeswalker you don't control",
            TargetObject(filter = TargetFilter(GameObjectFilter.CreatureOrPlaneswalker.opponentControls())),
        )
        effect = DealDamageEffect(DynamicAmounts.targetPower(0), t2, damageSource = t1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "155"
        artist = "Kitt Lapeña"
        flavorText = "\"Yavimaya takes care of herself; the kavu are evidence of this. What does your Coalition offer that the forest cannot provide?\"\n—Jenson Carthalion"
        imageUri = "https://cards.scryfall.io/normal/front/0/e/0eacd3de-b803-4322-8d88-d533761aa748.jpg"
    }
}
