// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Blizzard Elemental
 * {5}{U}{U}
 * Creature — Elemental
 * 5/5
 * Flying
 * {3}{U}: Untap this creature.
 */
val BlizzardElemental = card("Blizzard Elemental") {
    manaCost = "{5}{U}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Elemental"
    oracleText = "Flying\n{3}{U}: Untap this creature."
    power = 5
    toughness = 5
    keywords(Keyword.FLYING)
    activatedAbility {
        cost = Costs.Mana("{3}{U}")
        effect = Effects.Untap(EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "27"
        artist = "Thomas M. Baxa"
        flavorText = "Students who had seen Rayne argue with Urza were certain she had summoned it to make him seem warmer by comparison."
        imageUri = "https://cards.scryfall.io/normal/front/5/9/5949c5a7-9656-466a-add8-1800973fefee.jpg"
    }
}
