// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Bloodshot Cyclops
 * {5}{R}
 * Creature — Cyclops Giant
 * 4/4
 * {T}, Sacrifice a creature: This creature deals damage equal to the sacrificed creature's power to any target.
 */
val BloodshotCyclops = card("Bloodshot Cyclops") {
    manaCost = "{5}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Cyclops Giant"
    oracleText = "{T}, Sacrifice a creature: This creature deals damage equal to the sacrificed creature's power to any target."
    power = 4
    toughness = 4
    activatedAbility {
        cost = Costs.Composite(Costs.Tap, Costs.Sacrifice(GameObjectFilter.Creature))
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(DynamicAmounts.sacrificedPower(), t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "77"
        artist = "Ray Lago"
        flavorText = "After their first encounter, the goblins named him Chuck."
        imageUri = "https://cards.scryfall.io/normal/front/9/3/9320f3d8-0e51-43d0-aedb-bfed771101e9.jpg"
    }
}
