// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Capashen Templar
 * {2}{W}
 * Creature — Human Knight
 * 2/2
 * {W}: This creature gets +0/+1 until end of turn.
 */
val CapashenTemplar = card("Capashen Templar") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Knight"
    oracleText = "{W}: This creature gets +0/+1 until end of turn."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.Mana("{W}")
        effect = Effects.ModifyStats(0, 1, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "5"
        artist = "Todd Lockwood"
        flavorText = "Their shields are Benalia's outermost battlements."
        imageUri = "https://cards.scryfall.io/normal/front/0/9/0976a193-463a-4bcb-a951-ca73347a5572.jpg"
    }
}
