// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Elvish Lookout
 * {G}
 * Creature — Elf
 * 1/1
 * Shroud (This creature can't be the target of spells or abilities.)
 */
val ElvishLookout = card("Elvish Lookout") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Creature — Elf"
    oracleText = "Shroud (This creature can't be the target of spells or abilities.)"
    power = 1
    toughness = 1
    keywords(Keyword.SHROUD)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "103"
        artist = "Greg Hildebrandt & Tim Hildebrandt"
        flavorText = "Like a masterful quilter, Yavimaya stitches together patches of color to warn its denizens of threats."
        imageUri = "https://cards.scryfall.io/normal/front/d/9/d9a8a0e2-311a-4627-8a48-43df045c3112.jpg"
    }
}
