// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Fodder Cannon
 * {4}
 * Artifact
 * {4}, {T}, Sacrifice a creature: This artifact deals 4 damage to target creature.
 */
val FodderCannon = card("Fodder Cannon") {
    manaCost = "{4}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{4}, {T}, Sacrifice a creature: This artifact deals 4 damage to target creature."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{4}"), Costs.Tap, Costs.Sacrifice(GameObjectFilter.Creature))
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = DealDamageEffect(4, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "131"
        artist = "DiTerlizzi"
        flavorText = "Step 1: Find your cousin. Step 2: Get your cousin in the cannon. Step 3: Find another cousin."
        imageUri = "https://cards.scryfall.io/normal/front/2/2/229ba320-69c9-4400-a0d7-f0f79e8d9856.jpg"
    }
}
