// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Goblin Masons
 * {1}{R}
 * Creature — Goblin
 * 2/1
 * When this creature dies, destroy target Wall.
 */
val GoblinMasons = card("Goblin Masons") {
    manaCost = "{1}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Goblin"
    oracleText = "When this creature dies, destroy target Wall."
    power = 2
    toughness = 1
    triggeredAbility {
        trigger = Triggers.Dies
        val t = target("target", TargetCreature(filter = TargetFilter(GameObjectFilter.Creature.withSubtype("Wall"))))
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "86"
        artist = "DiTerlizzi"
        flavorText = "\"Goblins build with true zeal—and anything else within arm's reach.\""
        imageUri = "https://cards.scryfall.io/normal/front/1/2/124070d9-c362-4053-a405-9438b1cfac02.jpg"
    }
}
