// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Kingfisher
 * {3}{U}
 * Creature — Bird
 * 2/2
 * Flying
 * When this creature dies, draw a card.
 */
val Kingfisher = card("Kingfisher") {
    manaCost = "{3}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Bird"
    oracleText = "Flying\nWhen this creature dies, draw a card."
    power = 2
    toughness = 2
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.Dies
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "36"
        artist = "Edward P. Beard, Jr."
        flavorText = "It's tastiest when served with the fish it stole."
        imageUri = "https://cards.scryfall.io/normal/front/4/4/442bc3ba-00b3-4616-a5b2-55524ff8a736.jpg"
    }
}
