// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Magnify
 * {G}
 * Instant
 * All creatures get +1/+1 until end of turn.
 */
val Magnify = card("Magnify") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "All creatures get +1/+1 until end of turn."
    spell {
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature),
            Effects.ModifyStats(1, 1, EffectTarget.Self)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "111"
        artist = "Michael Sutfin"
        flavorText = "The seed torches' pollen gives off light, but the elves find it heightens their senses as well."
        imageUri = "https://cards.scryfall.io/normal/front/7/b/7b9bb2c6-f1a6-42c3-a7cb-3a1a46854c9b.jpg"
    }
}
