// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Master Healer
 * {4}{W}
 * Creature — Human Cleric
 * 1/4
 * {T}: Prevent the next 4 damage that would be dealt to any target this turn.
 */
val MasterHealer = card("Master Healer") {
    manaCost = "{4}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Cleric"
    oracleText = "{T}: Prevent the next 4 damage that would be dealt to any target this turn."
    power = 1
    toughness = 4
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", AnyTarget())
        effect = Effects.PreventNextDamage(4, t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "12"
        artist = "Adam Rex"
        flavorText = "Behind his eyes is the pain of every soldier his hands have healed."
        imageUri = "https://cards.scryfall.io/normal/front/e/2/e21a342c-ad80-43e4-8b2d-1c48241c52b1.jpg"
    }
}
