// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Plague Dogs
 * {4}{B}
 * Creature — Phyrexian Zombie Dog
 * 3/3
 * When this creature dies, all creatures get -1/-1 until end of turn.
 * {2}, Sacrifice this creature: Draw a card.
 */
val PlagueDogs = card("Plague Dogs") {
    manaCost = "{4}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Phyrexian Zombie Dog"
    oracleText = "When this creature dies, all creatures get -1/-1 until end of turn.\n{2}, Sacrifice this creature: Draw a card."
    power = 3
    toughness = 3
    triggeredAbility {
        trigger = Triggers.Dies
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature),
            Effects.ModifyStats(-1, -1, EffectTarget.Self)
        )
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}"), Costs.SacrificeSelf)
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "66"
        artist = "Chippy & Matthew D. Wilson"
        flavorText = "They're not just retrievers, they're carriers."
        imageUri = "https://cards.scryfall.io/normal/front/6/b/6b9cebd8-aa3f-4e22-8d15-d4b7bad355e4.jpg"
    }
}
