// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Temporal Adept
 * {1}{U}{U}
 * Creature — Human Wizard
 * 1/1
 * {U}{U}{U}, {T}: Return target permanent to its owner's hand.
 */
val TemporalAdept = card("Temporal Adept") {
    manaCost = "{1}{U}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Human Wizard"
    oracleText = "{U}{U}{U}, {T}: Return target permanent to its owner's hand."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{U}{U}{U}"), Costs.Tap)
        val t = target("target", TargetPermanent())
        effect = Effects.Move(t, Zone.HAND)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "48"
        artist = "Heather Hudson"
        flavorText = "\"Of course she's at the head of her class. All her classmates have disappeared.\"\n—Gatha, Tolarian renegade"
        imageUri = "https://cards.scryfall.io/normal/front/0/7/07bb9695-a8b0-47b4-9a03-11d559412f33.jpg"
    }
}
