// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.ProtectionScope


/**
 * Voice of Reason
 * {3}{W}
 * Creature — Angel
 * 2/2
 * Flying, protection from blue
 */
val VoiceOfReason = card("Voice of Reason") {
    manaCost = "{3}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Angel"
    oracleText = "Flying, protection from blue"
    power = 2
    toughness = 2
    keywords(Keyword.FLYING)
    keywordAbility(KeywordAbility.Protection(ProtectionScope.Color(Color.BLUE)))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "24"
        artist = "Ray Lago"
        flavorText = "\"Next to Grace is Reason, and Reason must be retained. If the web of Reason comes unwoven, madness will escape.\"\n—Song of All, canto 167"
        imageUri = "https://cards.scryfall.io/normal/front/e/d/ed3d5a10-6d4b-4383-b400-7323f2b4670e.jpg"
    }
}
