// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dka.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Mystic Retrieval
 * {3}{U}
 * Sorcery
 * Return target instant or sorcery card from your graveyard to your hand.
 * Flashback {2}{R} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val MysticRetrieval = card("Mystic Retrieval") {
    manaCost = "{3}{U}"
    colorIdentity = "UR"
    typeLine = "Sorcery"
    oracleText = "Return target instant or sorcery card from your graveyard to your hand.\nFlashback {2}{R} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        val t = target(
            "target",
            TargetObject(
                filter = TargetFilter(
                    GameObjectFilter.Instant.ownedByYou().or(GameObjectFilter.Sorcery.ownedByYou()),
                    zone = Zone.GRAVEYARD
                )
            )
        )
        effect = Effects.Move(t, Zone.HAND)
    }
    keywordAbility(KeywordAbility.flashback("{2}{R}"))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "42"
        artist = "Scott Chou"
        imageUri = "https://cards.scryfall.io/normal/front/2/8/281a685a-bd02-43bf-8700-2207c65bbbb1.jpg"
    }
}
