import type { CardSummary } from '../../cardFilter'

/** Tiny but representative catalog used to exercise matchers end-to-end. */
export const CARDS: CardSummary[] = [
  {
    name: 'Lightning Bolt',
    manaCost: '{R}',
    cmc: 1,
    colors: ['RED'],
    colorIdentity: ['RED'],
    cardTypes: ['INSTANT'],
    supertypes: [],
    subtypes: [],
    basicLand: false,
    rarity: 'COMMON',
    setCode: 'LEA',
    collectorNumber: '161',
    oracleText: 'Lightning Bolt deals 3 damage to any target.',
    keywords: [],
    legalFormats: ['MODERN', 'LEGACY', 'VINTAGE'],
  },
  {
    name: 'Counterspell',
    manaCost: '{U}{U}',
    cmc: 2,
    colors: ['BLUE'],
    colorIdentity: ['BLUE'],
    cardTypes: ['INSTANT'],
    supertypes: [],
    subtypes: [],
    basicLand: false,
    rarity: 'COMMON',
    setCode: 'LEA',
    collectorNumber: '55',
    oracleText: 'Counter target spell.',
    keywords: [],
    legalFormats: ['LEGACY', 'VINTAGE'],
  },
  {
    name: 'Llanowar Elves',
    manaCost: '{G}',
    cmc: 1,
    colors: ['GREEN'],
    colorIdentity: ['GREEN'],
    cardTypes: ['CREATURE'],
    supertypes: [],
    subtypes: ['ELF', 'DRUID'],
    basicLand: false,
    rarity: 'COMMON',
    setCode: 'LEA',
    collectorNumber: '202',
    oracleText: '{T}: Add {G}.',
    power: '1',
    toughness: '1',
    keywords: [],
    legalFormats: ['MODERN', 'LEGACY'],
  },
  {
    name: 'Serra Angel',
    manaCost: '{3}{W}{W}',
    cmc: 5,
    colors: ['WHITE'],
    colorIdentity: ['WHITE'],
    cardTypes: ['CREATURE'],
    supertypes: [],
    subtypes: ['ANGEL'],
    basicLand: false,
    rarity: 'UNCOMMON',
    setCode: 'LEA',
    collectorNumber: '36',
    oracleText: 'Flying, vigilance.',
    power: '4',
    toughness: '4',
    keywords: ['FLYING', 'VIGILANCE'],
    legalFormats: ['LEGACY'],
  },
  {
    name: 'Niv-Mizzet, Parun',
    manaCost: '{U}{U}{U}{R}{R}{R}',
    cmc: 6,
    colors: ['BLUE', 'RED'],
    colorIdentity: ['BLUE', 'RED'],
    cardTypes: ['CREATURE'],
    supertypes: ['LEGENDARY'],
    subtypes: ['DRAGON', 'WIZARD'],
    basicLand: false,
    rarity: 'RARE',
    setCode: 'GRN',
    collectorNumber: '192',
    oracleText: 'Flying. Niv-Mizzet, Parun can\'t be countered. Whenever you cast an instant or sorcery spell, Niv-Mizzet deals 1 damage to any target.',
    power: '5',
    toughness: '5',
    keywords: ['FLYING'],
    legalFormats: ['MODERN', 'LEGACY', 'COMMANDER'],
  },
  {
    name: 'Forest',
    manaCost: '',
    cmc: 0,
    colors: [],
    colorIdentity: ['GREEN'],
    cardTypes: ['LAND'],
    supertypes: ['BASIC'],
    subtypes: ['FOREST'],
    basicLand: true,
    rarity: 'COMMON',
    setCode: 'LEA',
    collectorNumber: '294',
    oracleText: '({T}: Add {G}.)',
    keywords: [],
    legalFormats: ['MODERN', 'LEGACY', 'VINTAGE', 'COMMANDER'],
  },
  {
    name: 'Tarmogoyf',
    manaCost: '{1}{G}',
    cmc: 2,
    colors: ['GREEN'],
    colorIdentity: ['GREEN'],
    cardTypes: ['CREATURE'],
    supertypes: [],
    subtypes: ['LHURGOYF'],
    basicLand: false,
    rarity: 'MYTHIC',
    setCode: 'FUT',
    collectorNumber: '153',
    oracleText: 'Tarmogoyf\'s power is equal to the number of card types among cards in all graveyards and its toughness is equal to that number plus 1.',
    power: '*',
    toughness: '1+*',
    keywords: [],
    legalFormats: ['MODERN', 'LEGACY'],
  },
  // Reprint case for the `s:` matcher: canonical printing in BLB, reprinted in EOE.
  // `s:EOE` must surface this card via the reprint even though `setCode` is 'BLB'.
  {
    name: 'Banishing Light',
    manaCost: '{2}{W}',
    cmc: 3,
    colors: ['WHITE'],
    colorIdentity: ['WHITE'],
    cardTypes: ['ENCHANTMENT'],
    supertypes: [],
    subtypes: [],
    basicLand: false,
    rarity: 'UNCOMMON',
    setCode: 'BLB',
    collectorNumber: '4',
    oracleText: 'When Banishing Light enters, exile target nonland permanent an opponent controls until Banishing Light leaves the battlefield.',
    keywords: [],
    legalFormats: ['STANDARD', 'MODERN'],
    printingSetCodes: ['BLB', 'EOE'],
  },
]

export function names(cards: CardSummary[]): string[] {
  return cards.map((c) => c.name).sort()
}

/** Printed-name case, kept out of [CARDS]: Through the Omenpaths prints it as "Ademi of the Silkchutes". */
export const SPECTACULAR_SPIDER_MAN: CardSummary = {
  name: 'Spectacular Spider-Man',
  manaCost: '{1}{W}',
  cmc: 2,
  colors: ['WHITE'],
  colorIdentity: ['WHITE'],
  cardTypes: ['CREATURE'],
  supertypes: ['LEGENDARY'],
  subtypes: [],
  basicLand: false,
  rarity: 'RARE',
  setCode: 'SPM',
  collectorNumber: '14',
  power: '3',
  toughness: '2',
  keywords: [],
  legalFormats: ['STANDARD'],
  printingSetCodes: ['SPM', 'OM1'],
  printedNamePrintings: [
    { name: 'Ademi of the Silkchutes', setCode: 'OM1', collectorNumber: '1', imageUri: 'om1.jpg', backFaceImageUri: null },
  ],
}
