// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.exo.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Merfolk Looter
 * {1}{U}
 * Creature — Merfolk Rogue
 * 1/1
 * {T}: Draw a card, then discard a card.
 */
val MerfolkLooter = card("Merfolk Looter") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Merfolk Rogue"
    oracleText = "{T}: Draw a card, then discard a card."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.Composite(
            DrawCardsEffect(1),
            Patterns.Hand.discardCards(1)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "39"
        artist = "Ron Spencer"
        flavorText = "In the depths of Rootwater, salvage and sewage differ only in texture."
        imageUri = "https://cards.scryfall.io/normal/front/0/f/0fbb1c41-388f-4ff2-af37-ad64a0f4618e.jpg"
    }
}
