// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.exo.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GrantKeyword


/**
 * Robe of Mirrors
 * {U}
 * Enchantment — Aura
 * Enchant creature (Target a creature as you cast this. This card enters attached to that creature.)
 * Enchanted creature has shroud. (It can't be the target of spells or abilities.)
 */
val RobeOfMirrors = card("Robe of Mirrors") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Enchantment — Aura"
    oracleText = "Enchant creature (Target a creature as you cast this. This card enters attached to that creature.)\nEnchanted creature has shroud. (It can't be the target of spells or abilities.)"
    auraTarget = Targets.Creature
    staticAbility {
        ability = GrantKeyword(Keyword.SHROUD)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "43"
        artist = "John Matson"
        flavorText = "\"Does this make me look fat?\""
        imageUri = "https://cards.scryfall.io/normal/front/3/7/371720a2-ec3f-43a5-9551-c018e164e79f.jpg"
    }
}
