// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.exo.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Treasure Trove
 * {2}{U}{U}
 * Enchantment
 * {2}{U}{U}: Draw a card.
 */
val TreasureTrove = card("Treasure Trove") {
    manaCost = "{2}{U}{U}"
    colorIdentity = "U"
    typeLine = "Enchantment"
    oracleText = "{2}{U}{U}: Draw a card."
    activatedAbility {
        cost = Costs.Mana("{2}{U}{U}")
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "50"
        artist = "Michael Sutfin"
        flavorText = "Karn and Hanna stood over the recovered Legacy artifacts like loving parents over sleeping children."
        imageUri = "https://cards.scryfall.io/normal/front/f/2/f23ce909-e744-47ca-943d-62d97e97b1ea.jpg"
    }
}
