// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.drk.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect


/**
 * Fountain of Youth
 * {0}
 * Artifact
 * {2}, {T}: You gain 1 life.
 */
val FountainOfYouth = card("Fountain of Youth") {
    manaCost = "{0}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{2}, {T}: You gain 1 life."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}"), Costs.Tap)
        effect = GainLifeEffect(1)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "103"
        artist = "Daniel Gelon"
        flavorText = "The Fountain had stood in the town square for centuries, but only the pigeons knew its secret."
        imageUri = "https://cards.scryfall.io/normal/front/2/b/2b60eb23-cb9a-4203-86fb-60e47dbd870b.jpg"
    }
}
