-- Replays get a single durable home and a format that survives deploys.
--
-- Storage: this table used to be one of three places a replay lived (alongside an in-memory ring
-- buffer of recent games and, for games still in progress, the Redis session blob). It is now the
-- only one, so it has to hold in-flight recordings too — hence `status` and `resume_fingerprint`,
-- and hence the seat index that makes "replays I played in" a join instead of a scan of the
-- in-memory cache.
--
-- Durability: `data` (the compact input log) only reproduces a game while the engine that folds it
-- behaves as it did on the day — and cards here are data the engine folds through, so editing a card
-- rewrites the past. `presentation` is the frames that log produced when the recording build folded
-- it, kept as a fallback for exactly the case where re-simulation no longer agrees with history.
ALTER TABLE game_replays
    ADD COLUMN tournament_round  INT,
    ADD COLUMN status            TEXT NOT NULL DEFAULT 'FINISHED',
    ADD COLUMN engine_version    TEXT,
    ADD COLUMN resume_fingerprint TEXT,
    ADD COLUMN presentation      TEXT;

CREATE INDEX idx_game_replays_status ON game_replays (status);

-- Seat roster. Owned child of game_replays (Spring Data JDBC @MappedCollection), so it is rewritten
-- wholesale whenever the parent is saved. Rows written before this migration have no children and
-- cannot get them retroactively (seat ids live inside the gzipped payload, not in a column), so they
-- stay reachable by game id / share link but drop out of a player's own replay list.
CREATE TABLE game_replay_players (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    replay_id   BIGINT NOT NULL REFERENCES game_replays (id) ON DELETE CASCADE,
    seat        INT    NOT NULL,
    player_id   TEXT   NOT NULL,
    player_name TEXT   NOT NULL
);
CREATE INDEX idx_game_replay_players_player_id ON game_replay_players (player_id);
CREATE INDEX idx_game_replay_players_replay_id ON game_replay_players (replay_id);
