-- Account-owned cubes (hand-curated singleton card pools used as a limited pack source).
--
-- Same shape and rationale as the `decks` table: `data` holds the cube JSON verbatim (the client's
-- SharedCube shape: name, card names + counts, basic-land art set, pack size) and `name` /
-- `card_count` are denormalized so the cube browser can list without parsing every blob.
--
-- Cubes are per-account and private; the lobby never reads this table (a cube reaches a lobby as a
-- full card-name list over `UpdateLobbySettings.cubeCards`), which is what keeps guests and unsaved
-- cubes working. Runs only when accounts are enabled.

CREATE TABLE cubes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name       TEXT        NOT NULL,
    -- Total physical cards (sum of entry counts), not distinct names.
    card_count INT         NOT NULL DEFAULT 0,
    data       TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_cubes_user ON cubes (user_id);
