// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Aven Fisher
 * {3}{U}
 * Creature — Bird Soldier
 * 2/2
 * Flying (This creature can't be blocked except by creatures with flying or reach.)
 * When this creature dies, you may draw a card.
 */
val AvenFisher = card("Aven Fisher") {
    manaCost = "{3}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Bird Soldier"
    oracleText = "Flying (This creature can't be blocked except by creatures with flying or reach.)\nWhen this creature dies, you may draw a card."
    power = 2
    toughness = 2
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.Dies
        optional = true
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "63"
        artist = "Christopher Moeller"
        flavorText = "The same spears that catch their food today will defend their homes tomorrow."
        imageUri = "https://cards.scryfall.io/normal/front/5/b/5b27130d-2296-4076-9829-15ab63081896.jpg"
    }
}
