// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ice.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Balduvian Barbarians
 * {1}{R}{R}
 * Creature — Human Barbarian
 * 3/2
 */
val BalduvianBarbarians = card("Balduvian Barbarians") {
    manaCost = "{1}{R}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Human Barbarian"
    power = 3
    toughness = 2
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "172"
        artist = "Mark Poole"
        flavorText = "\"Barbarian raids were a concern to those living in the northwest provinces, but the Skyknights never dealt with the problem in a systematic way. They thought of the Balduvians as an 'amusing model' of their forebears' culture.\"\n—Kjeldor: Ice Civilization"
        imageUri = "https://cards.scryfall.io/normal/front/e/f/efeabe8e-8107-4d19-8a43-362aa79cdd92.jpg"
    }
}
