package com.wingedsheep.mtg.sets.definitions.frf.cards

import com.wingedsheep.sdk.core.CardType
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.effects.ManaRestriction
import com.wingedsheep.sdk.scripting.effects.SearchDestination
import com.wingedsheep.sdk.scripting.predicates.CardPredicate

/**
 * Renowned Weaponsmith — Fate Reforged #48
 * {1}{U} · Creature — Human Artificer · 1/3 · Uncommon
 *
 * {T}: Add {C}{C}. Spend this mana only to cast artifact spells or activate abilities of artifacts.
 * {U}, {T}: Search your library for a card named Heart-Piercer Bow or Vial of Dragonfire, reveal it,
 * put it into your hand, then shuffle.
 *
 * The mana ability is Vedalken Engineer's restriction on two colorless mana. The tutor is Dragonstorm
 * Forecaster's shape: an OR of two [CardPredicate.NameEquals] — one card, either name, and a search
 * may always fail to find.
 */
val RenownedWeaponsmith = card("Renowned Weaponsmith") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Human Artificer"
    power = 1
    toughness = 3
    oracleText = "{T}: Add {C}{C}. Spend this mana only to cast artifact spells or activate abilities of artifacts.\n" +
        "{U}, {T}: Search your library for a card named Heart-Piercer Bow or Vial of Dragonfire, reveal it, " +
        "put it into your hand, then shuffle."

    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddColorlessMana(
            2,
            restriction = ManaRestriction.CardTypeSpellsOrAbilitiesOnly(
                cardType = CardType.ARTIFACT,
                allowSpells = true,
                allowAbilities = true,
            )
        )
        manaAbility = true
        timing = TimingRule.ManaAbility
    }

    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{U}"), Costs.Tap)
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Any.copy(
                cardPredicates = listOf(
                    CardPredicate.Or(
                        listOf(
                            CardPredicate.NameEquals("Heart-Piercer Bow"),
                            CardPredicate.NameEquals("Vial of Dragonfire")
                        )
                    )
                )
            ),
            count = 1,
            destination = SearchDestination.HAND,
            shuffleAfter = true,
            reveal = true
        )
        description = "{U}, {T}: Search your library for a card named Heart-Piercer Bow or Vial of Dragonfire, " +
            "reveal it, put it into your hand, then shuffle."
    }

    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "48"
        artist = "Eric Deschamps"
        imageUri = "https://cards.scryfall.io/normal/front/5/0/500f72e0-2de2-4c02-bda0-8a61aa9b37fc.jpg?1783938703"
        ruling(
            "2019-07-12",
            "You can't spend mana added by this ability to pay costs of triggered abilities of artifacts " +
                "such as the first ability of Chandra's Regulator."
        )
        ruling(
            "2019-07-12",
            "The mana generated by Renowned Weaponsmith's first ability can't be spent to activate abilities " +
                "of artifact sources that aren't on the battlefield."
        )
    }
}
