// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.CantBeBlocked
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Cloak of Mists
 * {1}{U}
 * Enchantment — Aura
 * Enchant creature
 * Enchanted creature can't be blocked.
 */
val CloakOfMists = card("Cloak of Mists") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Enchantment — Aura"
    oracleText = "Enchant creature\nEnchanted creature can't be blocked."
    auraTarget = Targets.Creature
    staticAbility {
        // A card-level `flags(AbilityFlag.CANT_BE_BLOCKED)` would land the evasion on this
        // Aura itself, which never blocks or is blocked — the printed line is about the
        // enchanted creature, so the evasion is a static scoped to what this is attached to.
        ability = CantBeBlocked(GroupFilter.attachedCreature())
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "65"
        artist = "John Matson"
        flavorText = "\"All we could lose, we did. All we could keep, we do. And both are shrouded by mists.\"\n—Barrin, master wizard"
        imageUri = "https://cards.scryfall.io/normal/front/d/d/dd54251c-5a2e-48e4-9790-a64dcc44eb8e.jpg"
    }
}
