package com.wingedsheep.engine.scenarios

import com.wingedsheep.engine.core.ChooseTargetsDecision
import com.wingedsheep.engine.support.GameTestDriver
import com.wingedsheep.engine.support.TestCards
import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Step
import com.wingedsheep.sdk.model.Deck
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldContainExactly
import io.kotest.matchers.shouldBe
import io.kotest.matchers.types.shouldBeInstanceOf

/**
 * Affectionate Indrik (GRN #121, reprinted in FDN) — {5}{G} Creature — Beast 4/4.
 *
 * "When this creature enters, you may have it fight target creature you don't control."
 *
 * The card was generated by mtgish-tooling, whose target recovery read the IR's
 * `ControlledByAPlayer(Other(You))` ("a player other than you") as a bare `You` and rendered
 * `.youControl()` — inverting the restriction, so the enters trigger offered your OWN creatures and
 * none of the opponent's. The first test pins the offered target set, which is what actually
 * regressed; the second proves the fight itself still trades damage both ways.
 */
class AffectionateIndrikScenarioTest : FunSpec({

    fun newDriver(): GameTestDriver {
        val driver = GameTestDriver()
        driver.registerCards(TestCards.all)
        driver.initMirrorMatch(Deck.of("Forest" to 40), skipMulligans = true, startingPlayer = 0)
        driver.passPriorityUntil(Step.PRECOMBAT_MAIN)
        return driver
    }

    test("the enters trigger offers only creatures you don't control") {
        val driver = newDriver()
        val yours = driver.putCreatureOnBattlefield(driver.player1, "Grizzly Bears") // 2/2, yours
        val theirs = driver.putCreatureOnBattlefield(driver.player2, "Minotaur Warrior") // 2/3, theirs

        val indrik = driver.putCardInHand(driver.player1, "Affectionate Indrik")
        driver.giveMana(driver.player1, Color.GREEN, 6)
        driver.castSpell(driver.player1, indrik).isSuccess shouldBe true
        driver.bothPass() // resolve the Indrik; its enters trigger asks for a target

        val decision = driver.pendingDecision.shouldBeInstanceOf<ChooseTargetsDecision>()
        // The Indrik itself is a creature you control, and so is Grizzly Bears — neither may be
        // offered. Only the opponent's Minotaur Warrior is a legal fight target.
        decision.legalTargets.getValue(0) shouldContainExactly listOf(theirs)
        decision.legalTargets.getValue(0).contains(yours) shouldBe false
    }

    test("the fight trades damage: the 4/4 Indrik kills the 2/3, and takes 2 back") {
        val driver = newDriver()
        val theirs = driver.putCreatureOnBattlefield(driver.player2, "Minotaur Warrior") // 2/3

        val indrik = driver.putCardInHand(driver.player1, "Affectionate Indrik")
        driver.giveMana(driver.player1, Color.GREEN, 6)
        driver.castSpell(driver.player1, indrik).isSuccess shouldBe true
        driver.bothPass()

        driver.submitTargetSelection(driver.player1, listOf(theirs))
        driver.bothPass() // resolve the triggered ability

        // 4 damage to a toughness-3 creature is lethal; the Indrik survives the 2 back.
        driver.findPermanent(driver.player2, "Minotaur Warrior") shouldBe null
        (driver.findPermanent(driver.player1, "Affectionate Indrik") != null) shouldBe true
    }
})
