// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.core.AbilityFlag
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.effects.GrantKeywordEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Apocalypse Runner
 * {2}{B}{R}
 * Artifact — Vehicle
 * 6/5
 * {T}: Target creature you control with power 2 or less gains lifelink until end of turn and can't be blocked this turn.
 * Crew 3 (Tap any number of creatures you control with total power 3 or more: This Vehicle becomes an artifact creature until end of turn.)
 */
val ApocalypseRunner = card("Apocalypse Runner") {
    manaCost = "{2}{B}{R}"
    colorIdentity = "BR"
    typeLine = "Artifact — Vehicle"
    oracleText = "{T}: Target creature you control with power 2 or less gains lifelink until end of turn and can't be blocked this turn.\nCrew 3 (Tap any number of creatures you control with total power 3 or more: This Vehicle becomes an artifact creature until end of turn.)"
    power = 6
    toughness = 5
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.powerAtMost(2).youControl()))
        effect = Effects.Composite(
            Effects.GrantKeyword(Keyword.LIFELINK, t),
            GrantKeywordEffect(AbilityFlag.CANT_BE_BLOCKED.name, t)
        )
    }
    keywordAbility(KeywordAbility.crew(3))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "188"
        artist = "Aaron J. Riley"
        flavorText = "\"Don't avoid the wreck. Survive it.\"\n—Far Fortune"
        imageUri = "https://cards.scryfall.io/normal/front/9/7/971286f5-77ea-4824-91de-f0ac88c46238.jpg"
    }
}
