// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Bestow Greatness
 * {2}{G}
 * Instant
 * Target creature gets +4/+4 and gains trample until end of turn.
 */
val BestowGreatness = card("Bestow Greatness") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Target creature gets +4/+4 and gains trample until end of turn."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Composite(
            Effects.ModifyStats(4, 4, t),
            Effects.GrantKeyword(Keyword.TRAMPLE, t)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "155"
        artist = "Jeff Carpenter"
        flavorText = "Exercise kindness, for nothing remains small forever.\n—Alacrian proverb"
        imageUri = "https://cards.scryfall.io/normal/front/b/6/b6a5adee-3482-4c5b-9260-58efa8fec5ba.jpg"
    }
}
