// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Brightfield Glider
 * {W}
 * Creature — Possum Mount
 * 1/1
 * Vigilance
 * Whenever this creature attacks while saddled, it gets +1/+2 and gains flying until end of turn.
 * Saddle 3 (Tap any number of other creatures you control with total power 3 or more: This Mount becomes saddled until end of turn. Saddle only as a sorcery.)
 */
val BrightfieldGlider = card("Brightfield Glider") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Creature — Possum Mount"
    oracleText = "Vigilance\nWhenever this creature attacks while saddled, it gets +1/+2 and gains flying until end of turn.\nSaddle 3 (Tap any number of other creatures you control with total power 3 or more: This Mount becomes saddled until end of turn. Saddle only as a sorcery.)"
    power = 1
    toughness = 1
    keywords(Keyword.VIGILANCE)
    triggeredAbility {
        trigger = Triggers.Attacks
        triggerCondition = Conditions.SourceIsSaddled
        effect = Effects.Composite(
            Effects.ModifyStats(1, 2, EffectTarget.Self),
            Effects.GrantKeyword(Keyword.FLYING, EffectTarget.Self)
        )
    }
    keywordAbility(KeywordAbility.saddle(3))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "4"
        artist = "Andreia Ugrai"
        imageUri = "https://cards.scryfall.io/normal/front/7/e/7eb819eb-ba5c-4449-87b5-3894380558bc.jpg"
    }
}
