// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Broodheart Engine
 * {B}{G}
 * Artifact
 * At the beginning of your upkeep, surveil 1.
 * {2}{B}{G}, {T}, Sacrifice this artifact: Return target creature or Vehicle card from your graveyard to the battlefield. Activate only as a sorcery.
 */
val BroodheartEngine = card("Broodheart Engine") {
    manaCost = "{B}{G}"
    colorIdentity = "BG"
    typeLine = "Artifact"
    oracleText = "At the beginning of your upkeep, surveil 1.\n{2}{B}{G}, {T}, Sacrifice this artifact: Return target creature or Vehicle card from your graveyard to the battlefield. Activate only as a sorcery."
    triggeredAbility {
        trigger = Triggers.YourUpkeep
        effect = Patterns.Library.surveil(1)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}{B}{G}"), Costs.Tap, Costs.SacrificeSelf)
        val t = target("target", TargetObject(filter = TargetFilter.CreatureInYourGraveyard))
        effect = Effects.Move(t, Zone.BATTLEFIELD)
        timing = TimingRule.SorcerySpeed
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "193"
        artist = "Rémi Jacquot"
        flavorText = "The only honor greater than piloting a Speedbrood vehicle is becoming one yourself."
        imageUri = "https://cards.scryfall.io/normal/front/e/d/ed09139b-a66e-4cd1-b45a-23a4648d3401.jpg"
    }
}
