// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Caelorna, Coral Tyrant
 * {1}{U}
 * Legendary Creature — Octopus
 * 0/8
 */
val CaelornaCoralTyrant = card("Caelorna, Coral Tyrant") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Legendary Creature — Octopus"
    power = 0
    toughness = 8
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "40"
        artist = "Deruchenko Alexander"
        flavorText = "For centuries, she grew in her benthic home, safe from Muraganda's moonfalls, feeding on the raw leylines that run below the water. When she emerged, the coral depths she called home came with her."
        imageUri = "https://cards.scryfall.io/normal/front/e/8/e8654e38-4230-4094-b815-778bfb5d06f2.jpg"
    }
}
