// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Dracosaur Auxiliary
 * {4}{R}{R}
 * Creature — Dinosaur Dragon Mount
 * 4/4
 * Flying, haste
 * Whenever this creature attacks while saddled, it deals 2 damage to any target.
 * Saddle 3 (Tap any number of other creatures you control with total power 3 or more: This Mount becomes saddled until end of turn. Saddle only as a sorcery.)
 */
val DracosaurAuxiliary = card("Dracosaur Auxiliary") {
    manaCost = "{4}{R}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Dinosaur Dragon Mount"
    oracleText = "Flying, haste\nWhenever this creature attacks while saddled, it deals 2 damage to any target.\nSaddle 3 (Tap any number of other creatures you control with total power 3 or more: This Mount becomes saddled until end of turn. Saddle only as a sorcery.)"
    power = 4
    toughness = 4
    keywords(Keyword.FLYING, Keyword.HASTE)
    triggeredAbility {
        trigger = Triggers.Attacks
        triggerCondition = Conditions.SourceIsSaddled
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(2, t)
    }
    keywordAbility(KeywordAbility.saddle(3))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "122"
        artist = "Brian Valeza"
        imageUri = "https://cards.scryfall.io/normal/front/c/f/cf800b8c-d08e-4644-8ed2-11b839153861.jpg"
    }
}
