// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Grim Bauble
 * {B}
 * Artifact
 * When this artifact enters, target creature an opponent controls gets -2/-2 until end of turn.
 * {2}{B}, {T}, Sacrifice this artifact: Surveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)
 */
val GrimBauble = card("Grim Bauble") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Artifact"
    oracleText = "When this artifact enters, target creature an opponent controls gets -2/-2 until end of turn.\n{2}{B}, {T}, Sacrifice this artifact: Surveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)"
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.opponentControls()))
        effect = Effects.ModifyStats(-2, -2, t)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}{B}"), Costs.Tap, Costs.SacrificeSelf)
        effect = Patterns.Library.surveil(2)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "88"
        artist = "Wero Gallo"
        imageUri = "https://cards.scryfall.io/normal/front/9/b/9bfdf60a-6f67-4872-8961-d63776b192c3.jpg"
    }
}
