// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.GrantDynamicStatsEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Guidelight Synergist
 * {3}{W}
 * Artifact Creature — Robot Artificer
 * 0/4
 * Flying
 * This creature gets +1/+0 for each artifact you control.
 */
val GuidelightSynergist = card("Guidelight Synergist") {
    manaCost = "{3}{W}"
    colorIdentity = "W"
    typeLine = "Artifact Creature — Robot Artificer"
    oracleText = "Flying\nThis creature gets +1/+0 for each artifact you control."
    power = 0
    toughness = 4
    keywords(Keyword.FLYING)
    staticAbility {
        ability = GrantDynamicStatsEffect(
            filter = GroupFilter.source(),
            powerBonus = DynamicAmount.Count(Player.You, Zone.BATTLEFIELD, GameObjectFilter.Artifact),
            toughnessBonus = DynamicAmount.Multiply(
                DynamicAmount.Count(Player.You, Zone.BATTLEFIELD, GameObjectFilter.Artifact),
                0
            )
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "16"
        artist = "Camille Alquier"
        flavorText = "\"Declarative: A unit is only as strong as its network.\""
        imageUri = "https://cards.scryfall.io/normal/front/f/d/fdaeea2c-d8aa-416f-95d6-6af888591fdf.jpg"
    }
}
