// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Locust Spray
 * {B}
 * Instant
 * Target creature gets -1/-1 until end of turn.
 * Cycling {B} ({B}, Discard this card: Draw a card.)
 */
val LocustSpray = card("Locust Spray") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Instant"
    oracleText = "Target creature gets -1/-1 until end of turn.\nCycling {B} ({B}, Discard this card: Draw a card.)"
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ModifyStats(-1, -1, t)
    }
    keywordAbility(KeywordAbility.cycling("{B}"))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "95"
        artist = "Caio Monteiro"
        flavorText = "\"Captain, the cowards are throwing bugs at us!\"\n—Sphyr, Keelhauler lookout"
        imageUri = "https://cards.scryfall.io/normal/front/5/4/54b3a547-6f74-4cb4-ad98-7e1b75f1a120.jpg"
    }
}
