// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Risky Shortcut
 * {2}{B}
 * Sorcery
 * Draw two cards. Each player loses 2 life.
 */
val RiskyShortcut = card("Risky Shortcut") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Sorcery"
    oracleText = "Draw two cards. Each player loses 2 life."
    spell {
        effect = Effects.Composite(
            DrawCardsEffect(2),
            Effects.LoseLife(2, EffectTarget.PlayerRef(Player.Each))
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "103"
        artist = "Ignatius Budi"
        flavorText = "\"Don't think of it as cheating, think of it as track they forgot to lay out for us.\"\n—Rido, Endrider"
        imageUri = "https://cards.scryfall.io/normal/front/c/8/c80aa587-4445-43d7-abc0-654d94ff4cda.jpg"
    }
}
