// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Sundial, Dawn Tyrant
 * {1}{W}
 * Legendary Artifact Creature — Construct
 * 3/3
 */
val SundialDawnTyrant = card("Sundial, Dawn Tyrant") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Legendary Artifact Creature — Construct"
    power = 3
    toughness = 3
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "31"
        artist = "Bruce Brenneise"
        flavorText = "\"We follow as it walks at the head of the ever-breaking day. Is it leading the dawn, or does it march to some forgotten celestial order? It does not answer our questions, so faith must sustain us.\"\n—Chakshi, Dawnchaser pilgrim"
        imageUri = "https://cards.scryfall.io/normal/front/b/2/b2e5435c-52f3-42d7-bcee-5aa13afd6626.jpg"
    }
}
