// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Syphon Fuel
 * {4}{B}
 * Instant
 * Target creature gets -6/-6 until end of turn. You gain 2 life.
 */
val SyphonFuel = card("Syphon Fuel") {
    manaCost = "{4}{B}"
    colorIdentity = "B"
    typeLine = "Instant"
    oracleText = "Target creature gets -6/-6 until end of turn. You gain 2 life."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Composite(
            Effects.ModifyStats(-6, -6, t),
            GainLifeEffect(2)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "108"
        artist = "Mathias Kollros"
        flavorText = "After years of hunger, the oil-thirsting vampires of Gastal finally had their fill."
        imageUri = "https://cards.scryfall.io/normal/front/4/a/4af17ae0-1035-4cb2-8974-98b377bfaa48.jpg"
    }
}
