// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Tyrox, Saurid Tyrant
 * {1}{R}
 * Legendary Creature — Dinosaur Warrior
 * 4/1
 */
val TyroxSauridTyrant = card("Tyrox, Saurid Tyrant") {
    manaCost = "{1}{R}"
    colorIdentity = "R"
    typeLine = "Legendary Creature — Dinosaur Warrior"
    power = 4
    toughness = 1
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "149"
        artist = "John Tedrick"
        flavorText = "The Avishkari delegation considered their treaties with the Saurid Autocracy settled, but that was a crucial misunderstanding. To the Autocracy, diplomacy is a matter of power, not paper; testing the Grand Prix's defenses is merely their way of making a counteroffer."
        imageUri = "https://cards.scryfall.io/normal/front/1/5/159dc5a8-5cba-4c20-8c07-28a3d86c8411.jpg"
    }
}
