// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Venomsac Lagac
 * {1}{G}
 * Creature — Lizard Mount
 * 2/1
 * Deathtouch
 * Whenever this creature attacks while saddled, it gets +0/+3 until end of turn.
 * Saddle 2 (Tap any number of other creatures you control with total power 2 or more: This Mount becomes saddled until end of turn. Saddle only as a sorcery.)
 */
val VenomsacLagac = card("Venomsac Lagac") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Lizard Mount"
    oracleText = "Deathtouch\nWhenever this creature attacks while saddled, it gets +0/+3 until end of turn.\nSaddle 2 (Tap any number of other creatures you control with total power 2 or more: This Mount becomes saddled until end of turn. Saddle only as a sorcery.)"
    power = 2
    toughness = 1
    keywords(Keyword.DEATHTOUCH)
    triggeredAbility {
        trigger = Triggers.Attacks
        triggerCondition = Conditions.SourceIsSaddled
        effect = Effects.ModifyStats(0, 3, EffectTarget.Self)
    }
    keywordAbility(KeywordAbility.saddle(2))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "185"
        artist = "Andrey Kuzinskiy"
        imageUri = "https://cards.scryfall.io/normal/front/9/1/9142b1c9-09d7-42e4-8138-6c15d31f2470.jpg"
    }
}
