// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.CostModification
import com.wingedsheep.sdk.scripting.CostReductionSource
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.ModifySpellCost
import com.wingedsheep.sdk.scripting.SpellCostTarget
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect


/**
 * Voyage Home
 * {5}{W}{U}
 * Sorcery
 * Affinity for artifacts (This spell costs {1} less to cast for each artifact you control.)
 * You draw three cards and gain 3 life.
 */
val VoyageHome = card("Voyage Home") {
    manaCost = "{5}{W}{U}"
    colorIdentity = "WU"
    typeLine = "Sorcery"
    oracleText = "Affinity for artifacts (This spell costs {1} less to cast for each artifact you control.)\nYou draw three cards and gain 3 life."
    staticAbility {
        ability = ModifySpellCost(
            target = SpellCostTarget.SelfCast,
            modification = CostModification.ReduceGenericBy(
                CostReductionSource.PermanentsYouControlMatching(GameObjectFilter.Artifact)
            )
        )
    }
    spell {
        effect = Effects.Composite(
            DrawCardsEffect(3),
            GainLifeEffect(3)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "227"
        artist = "Hardy Fowler"
        flavorText = "\"Observation: At current rate of travel, eventual rediscovery of home is a mathematical inevitability. Firm imperative: Let's go.\""
        imageUri = "https://cards.scryfall.io/normal/front/4/b/4ba835da-0247-4716-9079-1b605297f6d5.jpg"
    }
}
