// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.vis.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.CanOnlyBlockCreaturesWith
import com.wingedsheep.sdk.scripting.GameObjectFilter


/**
 * Cloud Elemental
 * {2}{U}
 * Creature — Elemental
 * 2/3
 * Flying
 * This creature can block only creatures with flying.
 */
val CloudElemental = card("Cloud Elemental") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Elemental"
    oracleText = "Flying\nThis creature can block only creatures with flying."
    power = 2
    toughness = 3
    keywords(Keyword.FLYING)
    staticAbility {
        ability = CanOnlyBlockCreaturesWith(blockerFilter = GameObjectFilter.Creature.withKeyword(Keyword.FLYING))
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "29"
        artist = "Adam Rex"
        flavorText = "\"You know you've angered the gods when the clouds turn against you.\"\n—Sisay, Captain of the Weatherlight"
        imageUri = "https://cards.scryfall.io/normal/front/4/f/4f2a5146-cf2e-40c0-b498-06e611343196.jpg"
    }
}
