// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tmp.cards

import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Boil
 * {3}{R}
 * Instant
 * Destroy all Islands.
 */
val Boil = card("Boil") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Destroy all Islands."
    spell {
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Land.withSubtype(Subtype.ISLAND)),
            Effects.Move(EffectTarget.Self, Zone.GRAVEYARD, byDestruction = true),
            noRegenerate = false
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "165"
        artist = "Jason Alexander Behnke"
        flavorText = "\"The fishers will throw out their nets and draw them back filled with dust.\"\n—Oracle en-Vec"
        imageUri = "https://cards.scryfall.io/normal/front/2/f/2fa1c529-44e5-41b6-9704-ae2319f31f13.jpg"
    }
}
