// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tmp.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect


/**
 * Bottle Gnomes
 * {3}
 * Artifact Creature — Gnome
 * 1/3
 * Sacrifice this creature: You gain 3 life.
 */
val BottleGnomes = card("Bottle Gnomes") {
    manaCost = "{3}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Gnome"
    oracleText = "Sacrifice this creature: You gain 3 life."
    power = 1
    toughness = 3
    activatedAbility {
        cost = Costs.SacrificeSelf
        effect = GainLifeEffect(3)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "278"
        artist = "Kaja Foglio"
        flavorText = "\"I am reminded of the fable of the silver egg. Its owner cracks it open to see what jewels it holds, only to discover a simple yellow yolk.\"\n—Karn, silver golem"
        imageUri = "https://cards.scryfall.io/normal/front/6/4/645297d1-ee77-4879-83eb-8114fbabb9a4.jpg"
    }
}
