// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tmp.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Master Decoy
 * {1}{W}
 * Creature — Human Soldier
 * 1/2
 * {W}, {T}: Tap target creature.
 */
val MasterDecoy = card("Master Decoy") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Soldier"
    oracleText = "{W}, {T}: Tap target creature."
    power = 1
    toughness = 2
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{W}"), Costs.Tap)
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Tap(t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "29"
        artist = "Phil Foglio"
        flavorText = "\"A skilled decoy can throw your enemies off your trail. A master decoy can survive to do it again.\"\n—Gerrard of the Weatherlight"
        imageUri = "https://cards.scryfall.io/normal/front/f/3/f3e11097-1ace-4ae8-a9e8-d00b9f709e54.jpg"
    }
}
