// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tmp.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Phyrexian Hulk
 * {6}
 * Artifact Creature — Phyrexian Golem
 * 5/4
 */
val PhyrexianHulk = card("Phyrexian Hulk") {
    manaCost = "{6}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Phyrexian Golem"
    power = 5
    toughness = 4
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "302"
        artist = "Matthew D. Wilson"
        flavorText = "\"They are convenient in having no souls, but less so in having no spirit.\"\n—Volrath"
        imageUri = "https://cards.scryfall.io/normal/front/3/0/307f5d5e-3a4b-430e-8769-fb553216befa.jpg"
    }
}
