// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tmp.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.effects.MayEffect


/**
 * Skyshroud Ranger
 * {G}
 * Creature — Elf Ranger
 * 1/1
 * {T}: You may put a land card from your hand onto the battlefield. Activate only as a sorcery.
 */
val SkyshroudRanger = card("Skyshroud Ranger") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Creature — Elf Ranger"
    oracleText = "{T}: You may put a land card from your hand onto the battlefield. Activate only as a sorcery."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Tap
        effect = MayEffect(Patterns.Hand.putFromHand(filter = GameObjectFilter.Land))
        timing = TimingRule.SorcerySpeed
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "256"
        artist = "Steve Luke"
        flavorText = "\"Just as you see the grave and remember the friend, I see this forest and remember Llanowar.\"\n—Mirri of the Weatherlight"
        imageUri = "https://cards.scryfall.io/normal/front/e/f/efe01296-2b8b-4cdf-a041-a08bebea9c29.jpg"
    }
}
