// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tmp.cards

import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect


/**
 * Staunch Defenders
 * {3}{W}{W}
 * Creature — Human Soldier
 * 3/4
 * When this creature enters, you gain 4 life.
 */
val StaunchDefenders = card("Staunch Defenders") {
    manaCost = "{3}{W}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Soldier"
    oracleText = "When this creature enters, you gain 4 life."
    power = 3
    toughness = 4
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = GainLifeEffect(4)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "49"
        artist = "Mark Poole"
        flavorText = "\"Hold your position! Leave doubt for the dying!\"\n—Tahngarth of the Weatherlight"
        imageUri = "https://cards.scryfall.io/normal/front/8/8/88ed7210-17a4-4750-a003-617ba75bff3e.jpg"
    }
}
