// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.m21.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Village Rites
 * {B}
 * Instant
 * As an additional cost to cast this spell, sacrifice a creature.
 * Draw two cards.
 */
val VillageRites = card("Village Rites") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Instant"
    oracleText = "As an additional cost to cast this spell, sacrifice a creature.\nDraw two cards."
    additionalCost(Costs.additional.SacrificePermanent(GameObjectFilter.Creature))
    spell {
        effect = DrawCardsEffect(2)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "126"
        artist = "Bud Cook"
        flavorText = "\"You were so eager to take and consume. Yet when asked to give, you refuse?\""
        imageUri = "https://cards.scryfall.io/normal/front/9/c/9c0f60a6-b5c8-4704-8b61-94e8fc463e5d.jpg"
    }
}
