// Enums
export {
  Phase,
  PhaseDisplayNames,
  Step,
  StepDisplayNames,
  isMainPhaseStep,
  Color,
  ColorSymbols,
  ColorDisplayNames,
  Keyword,
  KeywordDisplayNames,
  ZoneType,
  isPublicZone,
  isHiddenZone,
  isSharedZone,
  CounterType,
  CounterTypeDisplayNames,
  ErrorCode,
  GameOverReason,
  CombatDamageStep,
} from './enums'

// Entities
export type { EntityId, ZoneId } from './entities'
export {
  entityId,
  sharedZone,
  playerZone,
  battlefield,
  stack,
  exile,
  command,
  library,
  hand,
  graveyard,
  zoneIdEquals,
  zoneIdToString,
  parseZoneId,
} from './entities'

// Game State
export type {
  ClientGameState,
  ClientCard,
  ClientZone,
  ClientPlayer,
  ClientPlayerEffect,
  ClientManaPool,
  ClientCombatState,
  ClientAttacker,
  ClientCombatTarget,
  ClientBlocker,
  ClientChosenTarget,
} from './gameState'
export {
  totalMana,
  isManaPoolEmpty,
  isCreature,
  isLand,
  isInstant,
  isSorcery,
  remainingToughness,
  findZone,
  getViewingPlayer,
  getOpponent,
  isMyTurn,
  hasPriority,
} from './gameState'

// Events
export type {
  ClientEvent,
  LifeChangedEvent,
  DamageDealtEvent,
  StatsModifiedEvent,
  CardDrawnEvent,
  CardDiscardedEvent,
  PermanentEnteredEvent,
  PermanentLeftEvent,
  CreatureAttackedEvent,
  CreatureBlockedEvent,
  CreatureDiedEvent,
  SpellCastEvent,
  SpellResolvedEvent,
  SpellCounteredEvent,
  AbilityTriggeredEvent,
  AbilityActivatedEvent,
  PermanentTappedEvent,
  PermanentUntappedEvent,
  CounterAddedEvent,
  CounterRemovedEvent,
  ManaAddedEvent,
  PlayerLostEvent,
  GameEndedEvent,
  HandLookedAtEvent,
} from './events'
export {
  isLifeChangedEvent,
  isDamageDealtEvent,
  isStatsModifiedEvent,
  isCardDrawnEvent,
  isPermanentEnteredEvent,
  isCreatureDiedEvent,
  isSpellCastEvent,
  isPermanentTappedEvent,
  isPermanentUntappedEvent,
  isHandLookedAtEvent,
} from './events'

// Actions
export type {
  GameAction,
  PassPriorityAction,
  CastSpellAction,
  ActivateAbilityAction,
  PlayLandAction,
  DeclareAttackersAction,
  DeclareBlockersAction,
  OrderBlockersAction,
  MakeChoiceAction,
  SelectTargetsAction,
  ChooseManaColorAction,
  SubmitDecisionAction,
  TakeMulliganAction,
  KeepHandAction,
  BottomCardsAction,
  ConcedeAction,
  ChosenTarget,
  PaymentStrategy,
  DecisionResponse,
} from './actions'
export {
  getActionDisplayName,
  actionRequiresTargets,
  getActionSubject,
} from './actions'

// Messages
export type {
  ServerMessage,
  ConnectedMessage,
  GameCreatedMessage,
  GameStartedMessage,
  StateUpdateMessage,
  LegalActionInfo,
  MulliganDecisionMessage,
  ChooseBottomCardsMessage,
  MulliganCompleteMessage,
  GameOverMessage,
  ErrorMessage,
  ClientMessage,
  ConnectMessage,
  CreateGameMessage,
  JoinGameMessage,
  SubmitActionMessage,
  KeepHandMessage,
  MulliganMessage,
  ClientChooseBottomCardsMessage,
  ConcedeMessage,
  // Pending Decision types
  PendingDecision,
  PendingDecisionBase,
  DecisionContext,
  DecisionPhase,
  SelectCardsDecision,
  YesNoDecision,
  ChooseTargetsDecision,
  TargetRequirementInfo,
  SearchLibraryDecision,
  SearchCardInfo,
  ReorderLibraryDecision,
  OrderObjectsDecision,
} from './messages'
export {
  isConnectedMessage,
  isGameCreatedMessage,
  isGameStartedMessage,
  isStateUpdateMessage,
  isMulliganDecisionMessage,
  isChooseBottomCardsMessage,
  isMulliganCompleteMessage,
  isGameOverMessage,
  isErrorMessage,
  createConnectMessage,
  createCreateGameMessage,
  createJoinGameMessage,
  createSubmitActionMessage,
  createKeepHandMessage,
  createMulliganMessage,
  createChooseBottomCardsMessage,
  createConcedeMessage,
} from './messages'
