// Enums
export {
  Phase,
  PhaseDisplayNames,
  Step,
  StepDisplayNames,
  isMainPhaseStep,
  Color,
  ColorSymbols,
  ColorDisplayNames,
  Keyword,
  KeywordDisplayNames,
  ZoneType,
  isPublicZone,
  isHiddenZone,
  isSharedZone,
  CounterType,
  CounterTypeDisplayNames,
  ErrorCode,
  GameOverReason,
  CombatDamageStep,
} from './enums'

// Entities
export type { EntityId, ZoneId } from './entities'
export {
  entityId,
  sharedZone,
  playerZone,
  BATTLEFIELD,
  STACK,
  EXILE,
  COMMAND,
  library,
  hand,
  graveyard,
  zoneIdEquals,
  zoneIdToString,
  parseZoneId,
} from './entities'

// Game State
export type {
  ClientGameState,
  ClientCard,
  ClientZone,
  ClientPlayer,
  ClientManaPool,
  ClientCombatState,
  ClientAttacker,
  ClientCombatTarget,
  ClientBlocker,
} from './gameState'
export {
  totalMana,
  isManaPoolEmpty,
  isCreature,
  isLand,
  isInstant,
  isSorcery,
  remainingToughness,
  findZone,
  getViewingPlayer,
  getOpponent,
  isMyTurn,
  hasPriority,
} from './gameState'

// Events
export type {
  ClientEvent,
  LifeChangedEvent,
  DamageDealtEvent,
  CardDrawnEvent,
  CardDiscardedEvent,
  PermanentEnteredEvent,
  PermanentLeftEvent,
  CreatureAttackedEvent,
  CreatureBlockedEvent,
  CreatureDiedEvent,
  SpellCastEvent,
  SpellResolvedEvent,
  SpellCounteredEvent,
  AbilityTriggeredEvent,
  AbilityActivatedEvent,
  PermanentTappedEvent,
  PermanentUntappedEvent,
  CounterAddedEvent,
  CounterRemovedEvent,
  ManaAddedEvent,
  PlayerLostEvent,
  GameEndedEvent,
} from './events'
export {
  isLifeChangedEvent,
  isDamageDealtEvent,
  isCardDrawnEvent,
  isPermanentEnteredEvent,
  isCreatureDiedEvent,
  isSpellCastEvent,
  isPermanentTappedEvent,
  isPermanentUntappedEvent,
} from './events'

// Actions
export type {
  GameAction,
  GainLifeAction,
  LoseLifeAction,
  SetLifeAction,
  DealDamageToPlayerAction,
  DealDamageToCreatureAction,
  AddManaAction,
  AddColorlessManaAction,
  EmptyManaPoolAction,
  ActivateManaAbilityAction,
  DrawCardAction,
  DiscardCardAction,
  MoveEntityAction,
  PutOntoBattlefieldAction,
  DestroyPermanentAction,
  SacrificePermanentAction,
  ExilePermanentAction,
  ReturnToHandAction,
  TapAction,
  UntapAction,
  UntapAllAction,
  AddCountersAction,
  RemoveCountersAction,
  AddPoisonCountersAction,
  RemoveSummoningSicknessAction,
  RemoveAllSummoningSicknessAction,
  PlayLandAction,
  ResetLandsPlayedAction,
  ShuffleLibraryAction,
  BeginCombatAction,
  DeclareAttackerAction,
  DeclareBlockerAction,
  EndCombatAction,
  OrderBlockersAction,
  ResolveCombatDamageAction,
  PassPriorityAction,
  EndGameAction,
  PlayerLosesAction,
  ResolveLegendRuleAction,
  ResolveTopOfStackAction,
  CastSpellAction,
  ChosenTarget,
  AttachAction,
  DetachAction,
  CheckStateBasedActionsAction,
  ClearDamageAction,
  PerformCleanupStepAction,
  ExpireEndOfCombatEffectsAction,
  ExpireEffectsForPermanentAction,
  ResolveCleanupDiscardAction,
  DecisionResponse,
  SubmitDecisionAction,
} from './actions'
export {
  getActionDisplayName,
  actionRequiresTargets,
  getActionSubject,
} from './actions'

// Messages
export type {
  ServerMessage,
  ConnectedMessage,
  GameCreatedMessage,
  GameStartedMessage,
  StateUpdateMessage,
  LegalActionInfo,
  MulliganDecisionMessage,
  ChooseBottomCardsMessage,
  MulliganCompleteMessage,
  GameOverMessage,
  ErrorMessage,
  ClientMessage,
  ConnectMessage,
  CreateGameMessage,
  JoinGameMessage,
  SubmitActionMessage,
  KeepHandMessage,
  MulliganMessage,
  ClientChooseBottomCardsMessage,
  ConcedeMessage,
} from './messages'
export {
  isConnectedMessage,
  isGameCreatedMessage,
  isGameStartedMessage,
  isStateUpdateMessage,
  isMulliganDecisionMessage,
  isChooseBottomCardsMessage,
  isMulliganCompleteMessage,
  isGameOverMessage,
  isErrorMessage,
  createConnectMessage,
  createCreateGameMessage,
  createJoinGameMessage,
  createSubmitActionMessage,
  createKeepHandMessage,
  createMulliganMessage,
  createChooseBottomCardsMessage,
  createConcedeMessage,
} from './messages'
