// Enums
export {
  Phase,
  PhaseDisplayNames,
  Step,
  StepDisplayNames,
  StepShortNames,
  getNextStep,
  isMainPhaseStep,
  Color,
  ColorSymbols,
  ColorDisplayNames,
  Keyword,
  KeywordDisplayNames,
  ZoneType,
  isPublicZone,
  isHiddenZone,
  isSharedZone,
  CounterType,
  CounterTypeDisplayNames,
  ErrorCode,
  GameOverReason,
  CombatDamageStep,
} from './enums'

// Entities
export type { EntityId, ZoneId } from './entities'
export {
  entityId,
  sharedZone,
  playerZone,
  battlefield,
  stack,
  exile,
  command,
  library,
  hand,
  graveyard,
  zoneIdEquals,
  zoneIdToString,
  parseZoneId,
} from './entities'

// Game State
export type {
  ClientGameState,
  ClientCard,
  ClientZone,
  ClientPlayer,
  ClientPlayerEffect,
  ClientCardEffect,
  ClientRuling,
  ClientManaPool,
  ClientCombatState,
  ClientAttacker,
  ClientCombatTarget,
  ClientBlocker,
  ClientChosenTarget,
} from './gameState'
export {
  totalMana,
  isManaPoolEmpty,
  isCreature,
  isLand,
  isInstant,
  isSorcery,
  remainingToughness,
  findZone,
  getViewingPlayer,
  getOpponent,
  isMyTurn,
  hasPriority,
} from './gameState'

// Events
export type {
  ClientEvent,
  LifeChangedEvent,
  DamageDealtEvent,
  StatsModifiedEvent,
  CardDrawnEvent,
  CardDiscardedEvent,
  PermanentEnteredEvent,
  PermanentLeftEvent,
  CreatureAttackedEvent,
  CreatureBlockedEvent,
  CreatureDiedEvent,
  SpellCastEvent,
  SpellResolvedEvent,
  SpellCounteredEvent,
  AbilityTriggeredEvent,
  AbilityActivatedEvent,
  PermanentTappedEvent,
  PermanentUntappedEvent,
  CounterAddedEvent,
  CounterRemovedEvent,
  ManaAddedEvent,
  PlayerLostEvent,
  GameEndedEvent,
  HandLookedAtEvent,
} from './events'
export {
  isLifeChangedEvent,
  isDamageDealtEvent,
  isStatsModifiedEvent,
  isCardDrawnEvent,
  isPermanentEnteredEvent,
  isCreatureDiedEvent,
  isSpellCastEvent,
  isPermanentTappedEvent,
  isPermanentUntappedEvent,
  isHandLookedAtEvent,
} from './events'

// Actions
export type {
  GameAction,
  PassPriorityAction,
  CastSpellAction,
  ActivateAbilityAction,
  PlayLandAction,
  DeclareAttackersAction,
  DeclareBlockersAction,
  OrderBlockersAction,
  MakeChoiceAction,
  SelectTargetsAction,
  ChooseManaColorAction,
  SubmitDecisionAction,
  TakeMulliganAction,
  KeepHandAction,
  BottomCardsAction,
  ConcedeAction,
  ChosenTarget,
  PaymentStrategy,
  DecisionResponse,
} from './actions'
export {
  getActionDisplayName,
  actionRequiresTargets,
  getActionSubject,
} from './actions'

// Messages
export type {
  ServerMessage,
  ConnectedMessage,
  GameCreatedMessage,
  GameStartedMessage,
  StateUpdateMessage,
  LegalActionInfo,
  ConvokeCreatureInfo,
  MulliganDecisionMessage,
  ChooseBottomCardsMessage,
  MulliganCompleteMessage,
  GameOverMessage,
  ErrorMessage,
  ClientMessage,
  ConnectMessage,
  CreateGameMessage,
  JoinGameMessage,
  SubmitActionMessage,
  KeepHandMessage,
  MulliganMessage,
  ClientChooseBottomCardsMessage,
  ConcedeMessage,
  CancelGameMessage,
  GameCancelledMessage,
  // Pending Decision types
  PendingDecision,
  PendingDecisionBase,
  DecisionContext,
  DecisionPhase,
  OpponentDecisionStatus,
  SelectCardsDecision,
  YesNoDecision,
  ChooseTargetsDecision,
  TargetRequirementInfo,
  SearchLibraryDecision,
  SearchCardInfo,
  ReorderLibraryDecision,
  OrderObjectsDecision,
  ChooseNumberDecision,
  ChooseOptionDecision,
  DistributeDecision,
  AssignDamageDecision,
  ChooseColorDecision,
  ManaSourceOption,
  SelectManaSourcesDecision,
  SplitPilesDecision,
  // Sealed Draft types
  SealedCardInfo,
  SealedGameCreatedMessage,
  SealedPoolGeneratedMessage,
  OpponentDeckSubmittedMessage,
  WaitingForOpponentMessage,
  DeckSubmittedMessage,
  CreateSealedGameMessage,
  JoinSealedGameMessage,
  SubmitSealedDeckMessage,
  // Reconnect types
  ReconnectedMessage,
  // Lobby types
  LobbyPlayerInfo,
  LobbySettings,
  LobbyCreatedMessage,
  LobbyUpdateMessage,
  LobbyStoppedMessage,
  CreateTournamentLobbyMessage,
  JoinLobbyMessage,
  StartTournamentLobbyMessage,
  MakePickMessage,
  LeaveLobbyMessage,
  StopLobbyMessage,
  UnsubmitDeckMessage,
  UpdateLobbySettingsMessage,
  // Draft types
  DraftPackReceivedMessage,
  DraftPickMadeMessage,
  DraftPickConfirmedMessage,
  DraftCompleteMessage,
  DraftTimerUpdateMessage,
  // Tournament types
  PlayerStandingInfo,
  MatchResultInfo,
  TournamentStartedMessage,
  TournamentMatchStartingMessage,
  TournamentByeMessage,
  RoundCompleteMessage,
  PlayerReadyForRoundMessage,
  TournamentCompleteMessage,
  ReadyForNextRoundMessage,
  // Spectating types
  ActiveMatchInfo,
  ActiveMatchesMessage,
  SpectatorCardInfo,
  SpectatorPlayerState,
  SpectatorStateUpdateMessage,
  SpectatorDecisionStatus,
  SpectatingStartedMessage,
  SpectatingStoppedMessage,
  SpectateGameMessage,
  StopSpectatingMessage,
  // Combat UI types
  OpponentBlockerAssignmentsMessage,
  UpdateBlockerAssignmentsMessage,
  // Disconnect types
  OpponentDisconnectedMessage,
  OpponentReconnectedMessage,
  TournamentPlayerDisconnectedMessage,
  TournamentPlayerReconnectedMessage,
  AddDisconnectTimeMessage,
  KickPlayerMessage,
  // Game Settings types
  SetFullControlMessage,
  SetStopOverridesMessage,
  StopOverrideInfo,
} from './messages'
export {
  isConnectedMessage,
  isGameCreatedMessage,
  isGameStartedMessage,
  isGameCancelledMessage,
  isStateUpdateMessage,
  isMulliganDecisionMessage,
  isChooseBottomCardsMessage,
  isMulliganCompleteMessage,
  isGameOverMessage,
  isErrorMessage,
  createConnectMessage,
  createCreateGameMessage,
  createJoinGameMessage,
  createSubmitActionMessage,
  createKeepHandMessage,
  createMulliganMessage,
  createChooseBottomCardsMessage,
  createConcedeMessage,
  createCancelGameMessage,
  // Sealed Draft message factories
  createCreateSealedGameMessage,
  createJoinSealedGameMessage,
  createSubmitSealedDeckMessage,
  // Sealed Draft type guards
  isSealedGameCreatedMessage,
  isSealedPoolGeneratedMessage,
  isOpponentDeckSubmittedMessage,
  isWaitingForOpponentMessage,
  isDeckSubmittedMessage,
  // Reconnect
  isReconnectedMessage,
  // Lobby message factories & guards
  createCreateTournamentLobbyMessage,
  createCreateSealedLobbyMessage,
  createJoinLobbyMessage,
  createStartTournamentLobbyMessage,
  createStartSealedLobbyMessage,
  createMakePickMessage,
  createLeaveLobbyMessage,
  createStopLobbyMessage,
  createUnsubmitDeckMessage,
  createUpdateLobbySettingsMessage,
  isLobbyCreatedMessage,
  isLobbyUpdateMessage,
  isLobbyStoppedMessage,
  // Draft message type guards
  isDraftPackReceivedMessage,
  isDraftPickMadeMessage,
  isDraftPickConfirmedMessage,
  isDraftCompleteMessage,
  isDraftTimerUpdateMessage,
  // Tournament message factories & guards
  createReadyForNextRoundMessage,
  isTournamentStartedMessage,
  isTournamentMatchStartingMessage,
  isTournamentByeMessage,
  isRoundCompleteMessage,
  isTournamentCompleteMessage,
  // Spectating factories & guards
  createSpectateGameMessage,
  createStopSpectatingMessage,
  createAddDisconnectTimeMessage,
  createKickPlayerMessage,
  isActiveMatchesMessage,
  isSpectatorStateUpdateMessage,
  isSpectatingStartedMessage,
  isSpectatingStoppedMessage,
  // Combat UI factories
  createUpdateBlockerAssignmentsMessage,
  // Game Settings factories
  createSetFullControlMessage,
  createSetStopOverridesMessage,
  createRequestUndoMessage,
} from './messages'
