package com.wingedsheep.mtg.sets.definitions.lorwyneclipsed

import com.wingedsheep.mtg.sets.definitions.lorwyneclipsed.cards.*
import com.wingedsheep.mtg.sets.definitions.onslaught.OnslaughtSet

/**
 * Lorwyn Eclipsed Set (2026)
 *
 * A return to the Lorwyn/Shadowmoor plane featuring tribal themes
 * with Elves, Kithkin, Merfolk, Goblins, and Elementals.
 *
 * Set Code: ECL
 * Release Date: January 23, 2026
 * Card Count: 273
 */
object LorwynEclipsedSet {

    const val SET_CODE = "ECL"
    const val SET_NAME = "Lorwyn Eclipsed"

    val allCards = listOf(
        AdeptWatershaper,
        AjaniOutlandChaperone,
        AppealToEirdu,
        AquitectsDefenses,
        AssertPerfection,
        AuntiesSentence,
        AuroraAwakener,
        BarbedBloodletter,
        BarkOfDoran,
        BileVialBoggart,
        BitterbloomBearer,
        BlightRot,
        BloodCrypt,
        BloodlineBidding,
        BloomTender,
        Blossombind,
        BoggartMischief,
        BoggartPrankster,
        BogslithersEmbrace,
        BoldwyrAggressor,
        BoulderDash,
        BramblebackBrute,
        BrigidClachansHeart,
        BrigidsCommand,
        BurdenedStoneback,
        BurningCuriosity,
        Catharsis,
        CelestialReunion,
        ChampionOfTheWeird,
        ChampionsOfThePerfect,
        ChampionsOfTheShoal,
        ChaosSpewer,
        ChitinousGraspling,
        ChompingChangeling,
        ChronicleOfVictory,
        CinderStrike,
        ClachanFestival,
        CreakwoodSafewright,
        CribSwap,
        DarknessDescends,
        DawnhandDissident,
        DawnhandEulogist,
        DawnsLightArcher,
        DeepchannelDuelist,
        DoseOfDawnglow,
        DreamHarvest,
        DreamSeizer,
        EclipsedElf,
        EclipsedFlamekin,
        EclipsedKithkin,
        EclipsedMerrow,
        EclipsedRealms,
        EirduCarrierOfDawn,
        Emptiness,
        EndBlazeEpiphany,
        EnragedFlamecaster,
        EvershrikesGift,
        EvolvingWilds,
        FeedTheFlames,
        FeistySpikeling,
        FigureOfFable,
        FirdochCore,
        FlameChainMauler,
        FlamekinGildweaver,
        FlaringCinder,
        FlitterwingNuisance,
        ForagingWickermaw,
        GallantFowlknight,
        GanglyStompling,
        Giantfall,
        GiltLeafsEmbrace,
        GlamerGifter,
        Glamermite,
        GlenElendraGuardian,
        GlenElendrasAnswer,
        GloomRipper,
        Goatnap,
        GoldmeadowNomad,
        Graveshifter,
        GreatForestDruid,
        GrubStoriedMatriarch,
        GrubsCommand,
        GristleGlutton,
        GutsplitterGang,
        HallowedFountain,
        HarmonizedCrescendo,
        HeirloomAuntie,
        HexingSquelcher,
        HighPerfectMorcant,
        HovelHurler,
        ImpoliteEntrance,
        IronShieldElf,
        KeepOut,
        Kinbinding,
        KinsbaileAspirant,
        KirolAttentiveFirstYear,
        KindleTheInnerFlame,
        Kithkeeper,
        KulrathMystic,
        KulrathZealot,
        LastingTarfire,
        Lavaleaper,
        LiminalHold,
        LluwenImperfectNaturalist,
        LochMare,
        Luminollusk,
        LysAlanaDignitary,
        LysAlanaInformant,
        MaralenFaeAscendant,
        MeandersGuide,
        MeekAttack,
        MerrowSkyswimmer,
        Mirrorform,
        MirrormindCrown,
        MischievousSneakling,
        MoongloveExtractor,
        MoonVigilAdherents,
        MorcantsEyes,
        MorcantsLoyalist,
        Moonshadow,
        MorningtidesLight,
        MornsongAria,
        MudbuttonCursetosser,
        MutableExplorer,
        NamelessInversion,
        NoggleRobber,
        NoggleTheMind,
        OkoLorwynLiege,
        OmniChangeling,
        Personify,
        PesteredWellguard,
        PitilessFists,
        PridefulFeastling,
        ProtectiveResponse,
        PrismaticUndercurrents,
        PucasEye,
        PummelerForHire,
        PyrrhicStrike,
        RaidingSchemes,
        ReapingWillow,
        RecklessRansacking,
        RimeChill,
        RimefireTorque,
        RiverguardsReflexes,
        RunAwayTogether,
        SaplingNursery,
        ScarbladesMalice,
        Sear,
        ShadowUrchin,
        Shimmercreep,
        ShimmerwildsGrowth,
        Shinestriker,
        ShoreLurker,
        SilvergillPeddler,
        SoulbrightSeeker,
        SourbreadAuntie,
        SpringleafDrum,
        SpryAndMighty,
        Squawkroaster,
        StalactiteDagger,
        SteamVents,
        SpiralIntoSolitude,
        StoicGroveGuide,
        Stratosoarer,
        SunDappledCelebrant,
        SurlyFarrier,
        SwatAway,
        SyggsCommand,
        TanufelRimespeaker,
        TasterOfWares,
        TempleGarden,
        TemporalCleansing,
        ThirstForIdentity,
        ThoughtweftCharge,
        ThoughtweftLieutenant,
        TimidShieldbearer,
        TributaryVaulter,
        TrystansCommand,
        TwilightDiviner,
        Tweeze,
        UnexpectedAssistance,
        UnforgivingAim,
        UnwelcomeSprite,
        Vibrance,
        VinebredBrawler,
        VirulentEmissary,
        VoraciousTomeSkimmer,
        WanderbrinePreacher,
        WanderwineDistracter,
        WanderwineFarewell,
        WildUnraveling,
        WildvinePummeler,
        Winnowing,
        Wistfulness,

        // Basic lands
    ) + LorwynEclipsedBasicLands

    val basicLands = LorwynEclipsedBasicLands.map { it.copy(setCode = OnslaughtSet.SET_CODE) }
}
