package com.wingedsheep.rulesengine.sets.ecl

import com.wingedsheep.rulesengine.sets.BaseCardRegistry
import com.wingedsheep.rulesengine.sets.ecl.cards.AdeptWatershaper
import com.wingedsheep.rulesengine.sets.ecl.cards.AjaniOutlandChaperone
import com.wingedsheep.rulesengine.sets.ecl.cards.AquitectsDefenses
import com.wingedsheep.rulesengine.sets.ecl.cards.AppealToEirdu
import com.wingedsheep.rulesengine.sets.ecl.cards.BarkOfDoran
import com.wingedsheep.rulesengine.sets.ecl.cards.BileVialBoggart
import com.wingedsheep.rulesengine.sets.ecl.cards.BlightedBlackthorn
import com.wingedsheep.rulesengine.sets.ecl.cards.Blossombind
import com.wingedsheep.rulesengine.sets.ecl.cards.BlossomingDefense
import com.wingedsheep.rulesengine.sets.ecl.cards.BoggartCursecrafter
import com.wingedsheep.rulesengine.sets.ecl.cards.BoggartPrankster
import com.wingedsheep.rulesengine.sets.ecl.cards.BoneclubBerserker
import com.wingedsheep.rulesengine.sets.ecl.cards.BrigidClachansHeart
import com.wingedsheep.rulesengine.sets.ecl.cards.BurdenedStoneback
import com.wingedsheep.rulesengine.sets.ecl.cards.ChangelingWayfinder
import com.wingedsheep.rulesengine.sets.ecl.cards.ChitinousGraspling
import com.wingedsheep.rulesengine.sets.ecl.cards.ClachanFestival
import com.wingedsheep.rulesengine.sets.ecl.cards.CribSwap
import com.wingedsheep.rulesengine.sets.ecl.cards.CrossroadsWatcher
import com.wingedsheep.rulesengine.sets.ecl.cards.CuriousColossus
import com.wingedsheep.rulesengine.sets.ecl.cards.DawnhandEulogist
import com.wingedsheep.rulesengine.sets.ecl.cards.DawnsLightArcher
import com.wingedsheep.rulesengine.sets.ecl.cards.DisruptorOfCurrents
import com.wingedsheep.rulesengine.sets.ecl.cards.ElderAuntie
import com.wingedsheep.rulesengine.sets.ecl.cards.EncumberedReejerey
import com.wingedsheep.rulesengine.sets.ecl.cards.FeedTheFlames
import com.wingedsheep.rulesengine.sets.ecl.cards.FlamekinGildweaver
import com.wingedsheep.rulesengine.sets.ecl.cards.FlockImpostor
import com.wingedsheep.rulesengine.sets.ecl.cards.GallantFowlknight
import com.wingedsheep.rulesengine.sets.ecl.cards.Glamermite
import com.wingedsheep.rulesengine.sets.ecl.cards.GoldmeadowNomad
import com.wingedsheep.rulesengine.sets.ecl.cards.GravelgillScoundrel
import com.wingedsheep.rulesengine.sets.ecl.cards.Graveshifter
import com.wingedsheep.rulesengine.sets.ecl.cards.GreatForestDruid
import com.wingedsheep.rulesengine.sets.ecl.cards.GristleGlutton
import com.wingedsheep.rulesengine.sets.ecl.cards.ImpoliteEntrance
import com.wingedsheep.rulesengine.sets.ecl.cards.KeepOut
import com.wingedsheep.rulesengine.sets.ecl.cards.Kinbinding
import com.wingedsheep.rulesengine.sets.ecl.cards.KinscaerSentry
import com.wingedsheep.rulesengine.sets.ecl.cards.KulrathMystic
import com.wingedsheep.rulesengine.sets.ecl.cards.LiminalHold
import com.wingedsheep.rulesengine.sets.ecl.cards.LysAlanaInformant
import com.wingedsheep.rulesengine.sets.ecl.cards.MoongloveExtractor
import com.wingedsheep.rulesengine.sets.ecl.cards.NamelessInversion
import com.wingedsheep.rulesengine.sets.ecl.cards.RiverguardsReflexes
import com.wingedsheep.rulesengine.sets.ecl.cards.RecklessRansacking
import com.wingedsheep.rulesengine.sets.ecl.cards.RooftopPercher
import com.wingedsheep.rulesengine.sets.ecl.cards.RunAwayTogether
import com.wingedsheep.rulesengine.sets.ecl.cards.SafewrightCavalry
import com.wingedsheep.rulesengine.sets.ecl.cards.ScarbladeScout
import com.wingedsheep.rulesengine.sets.ecl.cards.Sear
import com.wingedsheep.rulesengine.sets.ecl.cards.ShoreLurker
import com.wingedsheep.rulesengine.sets.ecl.cards.SurlyFarrier
import com.wingedsheep.rulesengine.sets.ecl.cards.SilvergillPeddler
import com.wingedsheep.rulesengine.sets.ecl.cards.SpellSnare
import com.wingedsheep.rulesengine.sets.ecl.cards.Stratosoarer
import com.wingedsheep.rulesengine.sets.ecl.cards.SunDappledCelebrant
import com.wingedsheep.rulesengine.sets.ecl.cards.TimidShieldbearer
import com.wingedsheep.rulesengine.sets.ecl.cards.TributaryVaulter
import com.wingedsheep.rulesengine.sets.ecl.cards.UnforgivingAim
import com.wingedsheep.rulesengine.sets.ecl.cards.VirulentEmissary
import com.wingedsheep.rulesengine.sets.ecl.cards.WanderbrinePreacher
import com.wingedsheep.rulesengine.sets.ecl.cards.WildvinePummeler
import com.wingedsheep.rulesengine.sets.ecl.cards.WanderbrineTrapper

object LorwynEclipsedSet : BaseCardRegistry() {
    override val setCode: String = "ECL"
    override val setName: String = "Lorwyn Eclipsed"

    init {
        register(AdeptWatershaper.definition, AdeptWatershaper.script)
        register(AjaniOutlandChaperone.definition, AjaniOutlandChaperone.script)
        register(AquitectsDefenses.definition, AquitectsDefenses.script)
        register(AppealToEirdu.definition, AppealToEirdu.script)
        register(BarkOfDoran.definition, BarkOfDoran.script)
        register(BileVialBoggart.definition, BileVialBoggart.script)
        register(BlightedBlackthorn.definition, BlightedBlackthorn.script)
        register(Blossombind.definition, Blossombind.script)
        register(BlossomingDefense.definition, BlossomingDefense.script)
        register(BoggartCursecrafter.definition, BoggartCursecrafter.script)
        register(BoggartPrankster.definition, BoggartPrankster.script)
        register(BoneclubBerserker.definition, BoneclubBerserker.script)
        register(BrigidClachansHeart.definition, BrigidClachansHeart.script)
        // Also register back face script for Brigid
        registerScript(BrigidClachansHeart.backScript)
        register(BurdenedStoneback.definition, BurdenedStoneback.script)
        register(ChangelingWayfinder.definition, ChangelingWayfinder.script)
        register(ChitinousGraspling.definition, ChitinousGraspling.script)
        register(ClachanFestival.definition, ClachanFestival.script)
        register(CribSwap.definition, CribSwap.script)
        register(CrossroadsWatcher.definition, CrossroadsWatcher.script)
        register(CuriousColossus.definition, CuriousColossus.script)
        register(DawnhandEulogist.definition, DawnhandEulogist.script)
        register(DawnsLightArcher.definition, DawnsLightArcher.script)
        register(DisruptorOfCurrents.definition, DisruptorOfCurrents.script)
        register(ElderAuntie.definition, ElderAuntie.script)
        register(EncumberedReejerey.definition, EncumberedReejerey.script)
        register(FeedTheFlames.definition, FeedTheFlames.script)
        register(FlamekinGildweaver.definition, FlamekinGildweaver.script)
        register(FlockImpostor.definition, FlockImpostor.script)
        register(GallantFowlknight.definition, GallantFowlknight.script)
        register(Glamermite.definition, Glamermite.script)
        register(GoldmeadowNomad.definition, GoldmeadowNomad.script)
        register(GravelgillScoundrel.definition, GravelgillScoundrel.script)
        register(Graveshifter.definition, Graveshifter.script)
        register(GreatForestDruid.definition, GreatForestDruid.script)
        register(GristleGlutton.definition, GristleGlutton.script)
        register(ImpoliteEntrance.definition, ImpoliteEntrance.script)
        register(KeepOut.definition, KeepOut.script)
        register(Kinbinding.definition, Kinbinding.script)
        register(KinscaerSentry.definition, KinscaerSentry.script)
        register(KulrathMystic.definition, KulrathMystic.script)
        register(LiminalHold.definition, LiminalHold.script)
        register(LysAlanaInformant.definition, LysAlanaInformant.script)
        register(MoongloveExtractor.definition, MoongloveExtractor.script)
        register(NamelessInversion.definition, NamelessInversion.script)
        register(RiverguardsReflexes.definition, RiverguardsReflexes.script)
        register(RecklessRansacking.definition, RecklessRansacking.script)
        register(RooftopPercher.definition, RooftopPercher.script)
        register(RunAwayTogether.definition, RunAwayTogether.script)
        register(SafewrightCavalry.definition, SafewrightCavalry.script)
        register(ScarbladeScout.definition, ScarbladeScout.script)
        register(Sear.definition, Sear.script)
        register(ShoreLurker.definition, ShoreLurker.script)
        register(SurlyFarrier.definition, SurlyFarrier.script)
        register(SilvergillPeddler.definition, SilvergillPeddler.script)
        register(SpellSnare.definition, SpellSnare.script)
        register(Stratosoarer.definition, Stratosoarer.script)
        register(SunDappledCelebrant.definition, SunDappledCelebrant.script)
        register(TimidShieldbearer.definition, TimidShieldbearer.script)
        register(TributaryVaulter.definition, TributaryVaulter.script)
        register(UnforgivingAim.definition, UnforgivingAim.script)
        register(VirulentEmissary.definition, VirulentEmissary.script)
        register(WanderbrinePreacher.definition, WanderbrinePreacher.script)
        register(WanderbrineTrapper.definition, WanderbrineTrapper.script)
        register(WildvinePummeler.definition, WildvinePummeler.script)
    }
}
