// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.emn.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Subjugator Angel
 * {4}{W}{W}
 * Creature — Angel
 * 4/3
 * Flying
 * When this creature enters, tap all creatures your opponents control.
 */
val SubjugatorAngel = card("Subjugator Angel") {
    manaCost = "{4}{W}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Angel"
    oracleText = "Flying\nWhen this creature enters, tap all creatures your opponents control."
    power = 4
    toughness = 3
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature.opponentControls()),
            Effects.Tap(EffectTarget.Self)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "45"
        artist = "Lius Lasahido"
        flavorText = "The remnants of Innistrad's corrupted angelic hosts collapsed to form the Flight of Nightmares."
        imageUri = "https://cards.scryfall.io/normal/front/a/f/af01371c-cd09-4882-9caf-04426dd4c965.jpg"
    }
}
