// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.nem.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.ModifyStats
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Ascendant Evincar
 * {4}{B}{B}
 * Legendary Creature — Phyrexian Vampire Noble
 * 3/3
 * Flying (This creature can't be blocked except by creatures with flying or reach.)
 * Other black creatures get +1/+1.
 * Nonblack creatures get -1/-1.
 */
val AscendantEvincar = card("Ascendant Evincar") {
    manaCost = "{4}{B}{B}"
    colorIdentity = "B"
    typeLine = "Legendary Creature — Phyrexian Vampire Noble"
    oracleText = "Flying (This creature can't be blocked except by creatures with flying or reach.)\nOther black creatures get +1/+1.\nNonblack creatures get -1/-1."
    power = 3
    toughness = 3
    keywords(Keyword.FLYING)
    staticAbility {
        ability = ModifyStats(
            powerBonus = 1,
            toughnessBonus = 1,
            filter = GroupFilter(GameObjectFilter.Creature.withColor(Color.BLACK), excludeSelf = true)
        )
    }
    staticAbility {
        ability = ModifyStats(
            powerBonus = -1,
            toughnessBonus = -1,
            filter = GroupFilter(GameObjectFilter.Creature.notColor(Color.BLACK))
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "51"
        artist = "Mark Zug"
        flavorText = "\"Things are going to change around here.\"\n—Crovax"
        imageUri = "https://cards.scryfall.io/normal/front/e/5/e5c87c93-8cf4-4d1a-9bb8-349600da55bc.jpg"
    }
}
