// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.nem.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.CanOnlyBlockCreaturesWith
import com.wingedsheep.sdk.scripting.GameObjectFilter


/**
 * Belbe's Percher
 * {2}{B}
 * Creature — Bird
 * 2/2
 * Flying
 * This creature can block only creatures with flying.
 */
val BelbesPercher = card("Belbe's Percher") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Bird"
    oracleText = "Flying\nThis creature can block only creatures with flying."
    power = 2
    toughness = 2
    keywords(Keyword.FLYING)
    staticAbility {
        ability = CanOnlyBlockCreaturesWith(blockerFilter = GameObjectFilter.Creature.withKeyword(Keyword.FLYING))
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "53"
        artist = "Edward P. Beard, Jr."
        flavorText = "Long and powerful, these birds were used to carry messages to and from the evincar."
        imageUri = "https://cards.scryfall.io/normal/front/d/9/d95dcb2e-8945-47dd-ad40-b5bdcc3ea742.jpg"
    }
}
