// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.nem.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Flowstone Overseer
 * {2}{R}{R}{R}
 * Creature — Beast
 * 4/4
 * {R}{R}: Target creature gets +1/-1 until end of turn.
 */
val FlowstoneOverseer = card("Flowstone Overseer") {
    manaCost = "{2}{R}{R}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Beast"
    oracleText = "{R}{R}: Target creature gets +1/-1 until end of turn."
    power = 4
    toughness = 4
    activatedAbility {
        cost = Costs.Mana("{R}{R}")
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ModifyStats(1, -1, t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "82"
        artist = "Andrew Goldhawk"
        flavorText = "The rebels couldn't see where the roar was coming from. Then they saw it was coming from everywhere."
        imageUri = "https://cards.scryfall.io/normal/front/3/e/3e644ab8-3cc3-413d-a918-44fc636087ae.jpg"
    }
}
