// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.nem.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Pack Hunt
 * {3}{G}
 * Sorcery
 * Search your library for up to three cards with the same name as target creature, reveal them, put them into your hand, then shuffle.
 */
val PackHunt = card("Pack Hunt") {
    manaCost = "{3}{G}"
    colorIdentity = "G"
    typeLine = "Sorcery"
    oracleText = "Search your library for up to three cards with the same name as target creature, reveal them, put them into your hand, then shuffle."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Creature,
            count = 3,
            destination = SearchDestination.HAND,
            reveal = true
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "109"
        artist = "Sam Wood"
        flavorText = "The one you see is just a diversion."
        imageUri = "https://cards.scryfall.io/normal/front/1/c/1c46caa8-efc0-4b72-b122-61e5d86a5b86.jpg"
    }
}
