// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.nem.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Plague Witch
 * {1}{B}
 * Creature — Elf Spellshaper
 * 1/1
 * {B}, {T}, Discard a card: Target creature gets -1/-1 until end of turn.
 */
val PlagueWitch = card("Plague Witch") {
    manaCost = "{1}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Elf Spellshaper"
    oracleText = "{B}, {T}, Discard a card: Target creature gets -1/-1 until end of turn."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{B}"), Costs.Tap, Costs.DiscardCard)
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ModifyStats(-1, -1, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "66"
        artist = "Nelson DeCastro"
        flavorText = "\"I can ail what cures you.\""
        imageUri = "https://cards.scryfall.io/normal/front/c/a/ca3614c2-39b4-4f67-adab-373dcb9e4553.jpg"
    }
}
