// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.nem.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Seal of Fire
 * {R}
 * Enchantment
 * Sacrifice this enchantment: It deals 2 damage to any target.
 */
val SealOfFire = card("Seal of Fire") {
    manaCost = "{R}"
    colorIdentity = "R"
    typeLine = "Enchantment"
    oracleText = "Sacrifice this enchantment: It deals 2 damage to any target."
    activatedAbility {
        cost = Costs.SacrificeSelf
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(2, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "98"
        artist = "Christopher Moeller"
        flavorText = "\"I am the romancer, the passion that consumes the flesh.\"\n—Seal inscription"
        imageUri = "https://cards.scryfall.io/normal/front/3/7/37eaf1f6-4bdc-4669-9a15-50b65e016ccf.jpg"
    }
}
