// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.nem.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Seal of Cleansing
 * {1}{W}
 * Enchantment
 * Sacrifice this enchantment: Destroy target artifact or enchantment.
 */
val SealOfCleansing = card("Seal of Cleansing") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Enchantment"
    oracleText = "Sacrifice this enchantment: Destroy target artifact or enchantment."
    activatedAbility {
        cost = Costs.SacrificeSelf
        val t = target("target", TargetPermanent(filter = TargetFilter.ArtifactOrEnchantment))
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "18"
        artist = "Christopher Moeller"
        flavorText = "\"I am the purifier, the light that clears all shadows.\"\n—Seal inscription"
        imageUri = "https://cards.scryfall.io/normal/front/a/f/af6c921e-1b82-412c-9979-adfdf83440f7.jpg"
    }
}
