// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.nem.cards

import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Spiteful Bully
 * {1}{B}
 * Creature — Phyrexian Zombie Mercenary
 * 3/3
 * At the beginning of your upkeep, this creature deals 3 damage to target creature you control.
 */
val SpitefulBully = card("Spiteful Bully") {
    manaCost = "{1}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Phyrexian Zombie Mercenary"
    oracleText = "At the beginning of your upkeep, this creature deals 3 damage to target creature you control."
    power = 3
    toughness = 3
    triggeredAbility {
        trigger = Triggers.YourUpkeep
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.youControl()))
        effect = DealDamageEffect(3, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "72"
        artist = "Chippy"
        flavorText = "Like most creatures bent on total destruction, they rarely bother to double-check their targets."
        imageUri = "https://cards.scryfall.io/normal/front/5/5/5535d14a-7126-4a94-96a0-e17ad5c72070.jpg"
    }
}
