// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.nem.cards

import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Viseling
 * {4}
 * Artifact Creature — Phyrexian Construct
 * 2/2
 * At the beginning of each opponent's upkeep, this creature deals X damage to that player, where X is the number of cards in their hand minus 4.
 */
val Viseling = card("Viseling") {
    manaCost = "{4}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Phyrexian Construct"
    oracleText = "At the beginning of each opponent's upkeep, this creature deals X damage to that player, where X is the number of cards in their hand minus 4."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.EachOpponentUpkeep
        effect = DealDamageEffect(4, EffectTarget.PlayerRef(Player.TriggeringPlayer))
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "140"
        artist = "Kev Walker"
        flavorText = "\"This may hurt a lot.\""
        imageUri = "https://cards.scryfall.io/normal/front/a/3/a3eb86c5-d6fe-4dde-ad07-c3109b3a1611.jpg"
    }
}
