// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.hml.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Merchant Scroll
 * {1}{U}
 * Sorcery
 * Search your library for a blue instant card, reveal that card, put it into your hand, then shuffle.
 */
val MerchantScroll = card("Merchant Scroll") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Search your library for a blue instant card, reveal that card, put it into your hand, then shuffle."
    spell {
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Instant,
            destination = SearchDestination.HAND,
            reveal = true
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "33"
        artist = "Liz Danforth"
        flavorText = "\"There's no trade without trust.\"\n—Eron the Relentless"
        imageUri = "https://cards.scryfall.io/normal/front/d/4/d4133ceb-6176-411a-9eb8-51721c1bb435.jpg"
    }
}
