// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dst.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Darksteel Pendant
 * {2}
 * Artifact
 * Indestructible (Effects that say "destroy" don't destroy this artifact.)
 * {1}, {T}: Scry 1. (Look at the top card of your library. You may put that card on the bottom.)
 */
val DarksteelPendant = card("Darksteel Pendant") {
    manaCost = "{2}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "Indestructible (Effects that say \"destroy\" don't destroy this artifact.)\n{1}, {T}: Scry 1. (Look at the top card of your library. You may put that card on the bottom.)"
    keywords(Keyword.INDESTRUCTIBLE)
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}"), Costs.Tap)
        effect = Patterns.Library.scry(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "113"
        artist = "Terese Nielsen"
        imageUri = "https://cards.scryfall.io/normal/front/9/c/9c1bac5f-c41a-49f0-94b0-79653b6fa67a.jpg"
    }
}
