// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dst.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.GrantKeyword
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Darksteel Forge
 * {9}
 * Artifact
 * Artifacts you control have indestructible. (Effects that say "destroy" don't destroy them. Artifact creatures with indestructible can't be destroyed by damage.)
 */
val DarksteelForge = card("Darksteel Forge") {
    manaCost = "{9}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "Artifacts you control have indestructible. (Effects that say \"destroy\" don't destroy them. Artifact creatures with indestructible can't be destroyed by damage.)"
    staticAbility {
        ability = GrantKeyword(Keyword.INDESTRUCTIBLE, GroupFilter(GameObjectFilter.Artifact.youControl()))
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "110"
        artist = "Martina Pilcerova"
        flavorText = "\"Did it have this shape upon Mirrodin's creation, or did some inconceivable force shape the unshapable?\"\n—Pontifex, elder researcher"
        imageUri = "https://cards.scryfall.io/normal/front/9/9/99078ecc-f50a-43e0-93c1-63240cd97bf7.jpg"
    }
}
