// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dst.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Echoing Courage
 * {1}{G}
 * Instant
 * Target creature and all other creatures with the same name as that creature get +2/+2 until end of turn.
 */
val EchoingCourage = card("Echoing Courage") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Target creature and all other creatures with the same name as that creature get +2/+2 until end of turn."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature, excludeSelf = true),
            Effects.ModifyStats(2, 2, EffectTarget.Self)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "74"
        artist = "Greg Staples"
        flavorText = "A single seed unleashes a flurry of growth."
        imageUri = "https://cards.scryfall.io/normal/front/6/f/6f37bf33-f340-44eb-a092-1cb9385c8981.jpg"
    }
}
