// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dst.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Metal Fatigue
 * {2}{W}
 * Instant
 * Tap all artifacts.
 */
val MetalFatigue = card("Metal Fatigue") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Instant"
    oracleText = "Tap all artifacts."
    spell {
        effect = Effects.ForEachInGroup(GroupFilter(GameObjectFilter.Artifact), Effects.Tap(EffectTarget.Self))
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "8"
        artist = "Arnie Swekel"
        flavorText = "The Auriok have fought the metal hordes for so long now that knowing how to cripple them has become an instinct."
        imageUri = "https://cards.scryfall.io/normal/front/9/f/9fa32494-24bc-44c7-81d4-7285bd1fe3c8.jpg"
    }
}
