// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dst.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Purge
 * {1}{W}
 * Instant
 * Destroy target artifact creature or black creature. It can't be regenerated.
 */
val Purge = card("Purge") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Instant"
    oracleText = "Destroy target artifact creature or black creature. It can't be regenerated."
    spell {
        val t = target("target", TargetPermanent(filter = TargetFilter.CreatureOrArtifact))
        effect = Effects.Destroy(t, noRegenerate = true)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "12"
        artist = "Pete Venters"
        flavorText = "For the first and last time, the horrific creature experienced terror."
        imageUri = "https://cards.scryfall.io/normal/front/b/d/bdcbe727-81f0-469e-92f1-0dd9acdb54ea.jpg"
    }
}
