// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dst.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Ritual of Restoration
 * {W}
 * Sorcery
 * Return target artifact card from your graveyard to your hand.
 */
val RitualOfRestoration = card("Ritual of Restoration") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Sorcery"
    oracleText = "Return target artifact card from your graveyard to your hand."
    spell {
        val t = target(
            "target",
            TargetObject(filter = TargetFilter(GameObjectFilter.Artifact.ownedByYou(), zone = Zone.GRAVEYARD))
        )
        effect = Effects.Move(t, Zone.HAND)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "13"
        artist = "Dany Orizio"
        flavorText = "Leonin raising ceremonies take place at the white sun's dawn, the rebirth of artifacts mirroring the birth of a new day."
        imageUri = "https://cards.scryfall.io/normal/front/7/3/73142844-de7c-4427-8183-c2281bde6449.jpg"
    }
}
