// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dst.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.CantBlock


/**
 * Scavenging Scarab
 * {3}{B}
 * Creature — Insect
 * 3/3
 * This creature can't block.
 */
val ScavengingScarab = card("Scavenging Scarab") {
    manaCost = "{3}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Insect"
    oracleText = "This creature can't block."
    power = 3
    toughness = 3
    staticAbility {
        ability = CantBlock()
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "51"
        artist = "Jeff Easley"
        flavorText = "The beetles feed not on the flesh of corpses but on the metal, grinding out the iron and steel to add to their own bulky shells."
        imageUri = "https://cards.scryfall.io/normal/front/0/2/023603c1-3f1e-42d1-81e1-535547ef6ee0.jpg"
    }
}
