// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dst.cards

import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.CostModification
import com.wingedsheep.sdk.scripting.CostReductionSource
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.ModifySpellCost
import com.wingedsheep.sdk.scripting.SpellCostTarget


/**
 * Tangle Golem
 * {7}
 * Artifact Creature — Golem
 * 5/4
 * Affinity for Forests (This spell costs {1} less to cast for each Forest you control.)
 */
val TangleGolem = card("Tangle Golem") {
    manaCost = "{7}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Golem"
    oracleText = "Affinity for Forests (This spell costs {1} less to cast for each Forest you control.)"
    power = 5
    toughness = 4
    staticAbility {
        ability = ModifySpellCost(
            target = SpellCostTarget.SelfCast,
            modification = CostModification.ReduceGenericBy(
                CostReductionSource.PermanentsYouControlMatching(GameObjectFilter.Land.withSubtype(Subtype.FOREST))
            )
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "151"
        artist = "Arnie Swekel"
        flavorText = "The longer it weaves through the twisted vines of the Tangle, the more it adopts their hidden strength."
        imageUri = "https://cards.scryfall.io/normal/front/e/9/e9915977-bd6b-477a-a495-f7ddbbeb82eb.jpg"
    }
}
