// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dst.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Ur-Golem's Eye
 * {4}
 * Artifact
 * {T}: Add {C}{C}.
 */
val UrGolemsEye = card("Ur-Golem's Eye") {
    manaCost = "{4}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{T}: Add {C}{C}."
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddColorlessMana(2)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "155"
        artist = "Heather Hudson"
        flavorText = "It still stares accusingly at Memnarch, though millennia have passed since he separated the eye from its body."
        imageUri = "https://cards.scryfall.io/normal/front/0/0/00cd61eb-a526-46db-8675-334663e0d63a.jpg"
    }
}
