// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.`5dn`.cards

import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect


/**
 * Anodet Lurker
 * {5}
 * Artifact Creature — Construct
 * 3/3
 * When this creature dies, you gain 3 life.
 */
val AnodetLurker = card("Anodet Lurker") {
    manaCost = "{5}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Construct"
    oracleText = "When this creature dies, you gain 3 life."
    power = 3
    toughness = 3
    triggeredAbility {
        trigger = Triggers.Dies
        effect = GainLifeEffect(3)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "101"
        artist = "Jeff Easley"
        flavorText = "These machines build fearsome visages out of scrap metal to scare off predators who would otherwise be eager to consume them."
        imageUri = "https://cards.scryfall.io/normal/front/c/9/c97773f5-548a-4107-b29c-56b5428d5ddb.jpg"
    }
}
