// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.`5dn`.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Blind Creeper
 * {1}{B}
 * Creature — Zombie Beast
 * 3/3
 * Whenever a player casts a spell, this creature gets -1/-1 until end of turn.
 */
val BlindCreeper = card("Blind Creeper") {
    manaCost = "{1}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Zombie Beast"
    oracleText = "Whenever a player casts a spell, this creature gets -1/-1 until end of turn."
    power = 3
    toughness = 3
    triggeredAbility {
        trigger = Triggers.AnyPlayerCastsSpell
        effect = Effects.ModifyStats(-1, -1, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "42"
        artist = "Carl Critchlow"
        flavorText = "It shuns everything except its next meal."
        imageUri = "https://cards.scryfall.io/normal/front/8/6/86d5440a-7460-4b4f-a167-a6c4fb2d855e.jpg"
    }
}
