// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.`5dn`.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Early Frost
 * {1}{U}
 * Instant
 * Tap up to three target lands.
 */
val EarlyFrost = card("Early Frost") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Tap up to three target lands."
    spell {
        val t = target("target", TargetPermanent(optional = true, count = 3, filter = TargetFilter.Land))
        effect = Effects.TapEachTarget()
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "29"
        artist = "Ben Thompson"
        flavorText = "Under its mists, the earth sleeps."
        imageUri = "https://cards.scryfall.io/normal/front/5/9/5989d4c4-bfa4-4b07-ab64-65a3aee6144e.jpg"
    }
}
