// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.`5dn`.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.TargetPlayer


/**
 * Fill with Fright
 * {3}{B}
 * Sorcery
 * Target player discards two cards. Scry 2. (Look at the top two cards of your library, then put any number of them on the bottom and the rest on top in any order.)
 */
val FillWithFright = card("Fill with Fright") {
    manaCost = "{3}{B}"
    colorIdentity = "B"
    typeLine = "Sorcery"
    oracleText = "Target player discards two cards. Scry 2. (Look at the top two cards of your library, then put any number of them on the bottom and the rest on top in any order.)"
    spell {
        val t = target("target", TargetPlayer())
        effect = Effects.Composite(
            Patterns.Hand.discardCards(2, t),
            Patterns.Library.scry(2)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "50"
        artist = "Luca Zontini"
        imageUri = "https://cards.scryfall.io/normal/front/e/6/e682bbd3-9f52-452d-b886-a6a8def35f27.jpg"
    }
}
