// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.`5dn`.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Furnace Whelp
 * {2}{R}{R}
 * Creature — Dragon
 * 2/2
 * Flying
 * {R}: This creature gets +1/+0 until end of turn.
 */
val FurnaceWhelp = card("Furnace Whelp") {
    manaCost = "{2}{R}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Dragon"
    oracleText = "Flying\n{R}: This creature gets +1/+0 until end of turn."
    power = 2
    toughness = 2
    keywords(Keyword.FLYING)
    activatedAbility {
        cost = Costs.Mana("{R}")
        effect = Effects.ModifyStats(1, 0, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "65"
        artist = "Matt Cavotta"
        flavorText = "Baby dragons can't figure out humans—if they didn't want to be killed, why were they made of meat and treasure?"
        imageUri = "https://cards.scryfall.io/normal/front/a/1/a1726eba-c471-40bd-a487-40d910b75d64.jpg"
    }
}
