// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.`5dn`.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Skyhunter Skirmisher
 * {1}{W}{W}
 * Creature — Cat Knight
 * 1/1
 * Flying, double strike
 */
val SkyhunterSkirmisher = card("Skyhunter Skirmisher") {
    manaCost = "{1}{W}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Cat Knight"
    oracleText = "Flying, double strike"
    power = 1
    toughness = 1
    keywords(Keyword.FLYING, Keyword.DOUBLE_STRIKE)
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "16"
        artist = "Greg Staples"
        flavorText = "\"Like dawn's first light, blind the unprepared and banish the shadows.\"\n—Skyhunter creed"
        imageUri = "https://cards.scryfall.io/normal/front/9/7/975d0549-e6b6-456b-8693-227591e4db91.jpg"
    }
}
