package com.wingedsheep.mtg.sets.definitions.onslaught

import com.wingedsheep.mtg.sets.definitions.onslaught.cards.*

/**
 * Onslaught Set (2002)
 *
 * Onslaught was the first set in the Onslaught block, featuring tribal themes
 * and introducing mechanics like Morph and Cycling.
 *
 * Set Code: ONS
 * Release Date: October 7, 2002
 * Card Count: 350
 */
object OnslaughtSet {

    const val SET_CODE = "ONS"
    const val SET_NAME = "Onslaught"

    /**
     * All cards implemented from this set.
     */
    val allCards = listOf(
        // White creatures and spells
        BattlefieldMedic,
        AvenBrigadier,
        AvenSoulgazer,
        AkromasBlessing,
        DoubtlessOne,
        AkromasVengeance,
        AncestorsProphet,
        AstralSlide,
        AuraExtraction,
        Aurification,
        CatapultMaster,
        CatapultSquad,
        CrowdFavorites,
        CrownOfAwe,
        CrudeRampart,
        Demystify,
        DiveBomber,
        ExaltedAngel,
        FoothillGuide,
        GrasslandCrusader,
        GravelSlinger,
        GustcloakHarrier,
        GustcloakRunner,
        GustcloakSentinel,
        GustcloakSkirmisher,
        GustcloakSavior,
        ImprovisedArmor,
        Inspirit,
        Pacifism,
        Sandskin,
        PietyCharm,
        RenewedFaith,
        RighteousCause,
        SunfireBalm,
        DawningPurist,
        DauntingDefender,
        DefensiveManeuvers,
        DaruCavalier,
        DaruHealer,
        DaruLancer,
        DiscipleOfGrace,
        GlorySeeker,
        IronfistCrusher,
        JarethLeonineTitan,
        NovaCleric,
        Oblation,
        PearlspearCourier,
        UnifiedStrike,
        Whipcorder,
        Mobilization,
        SharedTriumph,
        TrueBeliever,
        ConvalescentCare,
        SigilOfTheNewDawn,
        WeatheredWayfarer,

        // Blue creatures and spells
        AirborneAid,
        Annex,
        CallousOppressor,
        Clone,
        CrownOfAscension,
        AvenFateshaper,
        Backslide,
        BlatantThievery,
        CraftyPathmage,
        Discombobulate,
        DisruptivePitmage,
        FleetingAven,
        GhosthelmCourier,
        Graxiplon,
        InformationDealer,
        MagesGuile,
        ThoughtboundPrimoc,
        NamelessOne,
        AphettoAlchemist,
        AphettoGrifter,
        ArcanisTheOmnipotent,
        ArtificialEvolution,
        AscendingAven,
        ChokingTethers,
        Complicate,
        SageAven,
        ScreamingSeahawk,
        SlipstreamEel,
        TrickeryCharm,
        EssenceFracture,
        Imagecrafter,
        IxidorRealitySculptor,
        MistformDreamer,
        MistformShrieker,
        MistformSkyreaver,
        MistformWall,
        Reminisce,
        RiptideBiologist,
        SeasClaim,
        Standardize,
        RummagingWizard,
        VoidmageProdigy,
        ChainOfVapor,

        // Black creatures and spells
        AccursedCentaur,
        Blackmail,
        Boneknitter,
        AphettoDredging,
        CrownOfSuspicion,
        DirgeOfDread,
        FrightshroudCourier,
        HauntedCadaver,
        Headhunter,
        AphettoVulture,
        AnuridMurkdiver,
        CabalArchon,
        CabalExecutioner,
        CabalSlaver,
        CoverOfDarkness,
        CruelRevival,
        DeathPulse,
        DoomedNecromancer,
        EndemicPlague,
        DiscipleOfMalice,
        EbonbladeReaper,
        EntrailsFeaster,
        FallenCleric,
        FadeFromMemory,
        FeedingFrenzy,
        FesteringGoblin,
        GangrenousGoliath,
        GluttonousZombie,
        GravespawnSovereign,
        GrinningDemon,
        Infest,
        MiseryCharm,
        ProfanePrayers,
        ShepherdOfRot,
        SpinedBasher,
        NantukoHusk,
        OversoldCemetery,
        ProwlingPangolin,
        RotlungReanimator,
        SoullessOne,
        ScreechingBuzzard,
        SeveredLegion,
        SilentSpecter,
        Smother,
        Swat,
        StrongarmTactics,
        SyphonMind,
        SyphonSoul,
        UndeadGladiator,
        VisaraTheDreadful,
        WretchedAnurid,
        ThrashingMudspawn,
        WalkingDesecration,

        // Red creatures and spells
        AetherCharge,
        Avarax,
        BlisteringFirecat,
        ButcherOrgg,
        BreakOpen,
        BrightstoneRitual,
        CommandoRaid,
        CustodyBattle,
        CrownOfFury,
        SkirkCommando,
        AggravatedAssault,
        AirdropCondor,
        BatteringCraghorn,
        ChargingSlateback,
        DragonRoost,
        DwarvenBlastminer,
        EmbermageGoblin,
        ErraticExplosion,
        FeverCharm,
        FlamestickCourier,
        GratuitousViolence,
        GoblinMachinist,
        GoblinPiledriver,
        GoblinPyromancer,
        GoblinSharpshooter,
        GoblinSkyRaider,
        GoblinSledder,
        GoblinTaskmaster,
        NosyGoblin,
        LavamancersSkill,
        LayWaste,
        LightningRift,
        PinpointAvalanche,
        RecklessOne,
        RorixBladewing,
        SearingFlesh,
        Shock,
        SliceAndDice,
        SolarBlast,
        Starstorm,
        Sparksmith,
        SpitfireHandler,
        SkirkFireMarshal,
        SkirkProspector,
        ShaleskinBruiser,
        SnappingThragg,
        SpurredWolverine,
        Threaten,
        Tephraderm,
        ThunderOfHooves,
        WaveOfIndifference,

        // Green creatures and spells
        CrownOfVigor,
        AnimalMagnetism,
        BirchloreRangers,
        BloodlineShaman,
        Biorhythm,
        BroodhatchNantuko,
        ElvenRiders,
        ElvishPioneer,
        ElvishScrapper,
        EvergloveCourier,
        ExplosiveVegetation,
        InvigoratingBoon,
        KrosanColossus,
        KrosanGroundshaker,
        LeeryFogbeast,
        KrosanTusker,
        MythicProportions,
        Naturalize,
        RavenousBaloth,
        SnarlingUndorak,
        VenomspoutBrackus,
        BarkhideMauler,
        ElvishVanguard,
        ElvishWarrior,
        HeedlessOne,
        Hystrodon,
        SilklashSpider,
        SilvosRogueElemental,
        SpittingGourna,
        SymbioticBeast,
        TauntingElf,
        SymbioticElf,
        SymbioticWurm,
        ToweringBaloth,
        TreespringLorian,
        Wellwisher,
        ElvishPathcutter,
        SerpentineBasilisk,
        StagBeetle,
        WirewoodElf,
        WirewoodHerald,
        WirewoodSavage,
        WirewoodPride,
        VitalityCharm,
        OverwhelmingInstinct,
        PrimalBoost,
        CentaurGlade,
        ChainOfAcid,
        Gigapede,
        RunWild,
        WallOfMulch,
        TribalUnity,
        VoiceOfTheWoods,
        TemptingWurm,

        // Artifacts
        DoomCannon,
        DreamChisel,
        SlateOfAncestry,

        // Lands
        BloodstainedMire,
        PollutedDelta,
        BarrenMoor,
        ForgottenCave,
        ContestedCliffs,
        DaruEncampment,
        GoblinBurrows,
        LonelySandbar,
        SeasideHaven,
        StarlitSanctum,
        WirewoodLodge,
        RiptideLaboratory,
        UnholyGrotto,
        SecludedSteppe,
        TranquilThicket,

        // Basic lands
    ) + OnslaughtBasicLands
}
