package com.wingedsheep.mtg.sets.definitions.onslaught

import com.wingedsheep.mtg.sets.definitions.onslaught.cards.*

/**
 * Onslaught Set (2002)
 *
 * Onslaught was the first set in the Onslaught block, featuring tribal themes
 * and introducing mechanics like Morph and Cycling.
 *
 * Set Code: ONS
 * Release Date: October 7, 2002
 * Card Count: 350
 */
object OnslaughtSet {

    const val SET_CODE = "ONS"
    const val SET_NAME = "Onslaught"

    /**
     * All cards implemented from this set.
     */
    val allCards = listOf(
        // White creatures and spells
        BattlefieldMedic,
        AvenBrigadier,
        AvenSoulgazer,
        AkromasBlessing,
        DoubtlessOne,
        AkromasVengeance,
        AncestorsProphet,
        AstralSlide,
        AuraExtraction,
        Aurification,
        CatapultMaster,
        CatapultSquad,
        CrownOfAwe,
        CrudeRampart,
        Demystify,
        DiveBomber,
        ExaltedAngel,
        FoothillGuide,
        GrasslandCrusader,
        GravelSlinger,
        GustcloakHarrier,
        GustcloakRunner,
        GustcloakSentinel,
        GustcloakSkirmisher,
        ImprovisedArmor,
        Inspirit,
        Pacifism,
        PietyCharm,
        RenewedFaith,
        RighteousCause,
        DawningPurist,
        DauntingDefender,
        DefensiveManeuvers,
        DaruCavalier,
        DaruHealer,
        DaruLancer,
        DiscipleOfGrace,
        GlorySeeker,
        IronfistCrusher,
        NovaCleric,
        Oblation,
        PearlspearCourier,
        UnifiedStrike,
        Whipcorder,
        Mobilization,
        SharedTriumph,

        CoverOfDarkness,

        // Blue creatures and spells
        AirborneAid,
        Annex,
        Clone,
        CrownOfAscension,
        AvenFateshaper,
        Backslide,
        BlatantThievery,
        CraftyPathmage,
        Discombobulate,
        DisruptivePitmage,
        FleetingAven,
        GhosthelmCourier,
        Graxiplon,
        InformationDealer,
        MagesGuile,
        ThoughtboundPrimoc,
        NamelessOne,
        AphettoAlchemist,
        AphettoGrifter,
        ArcanisTheOmnipotent,
        ArtificialEvolution,
        AscendingAven,
        ChokingTethers,
        Complicate,
        SageAven,
        ScreamingSeahawk,
        SlipstreamEel,
        TrickeryCharm,
        EssenceFracture,
        Imagecrafter,
        IxidorRealitySculptor,
        MistformDreamer,
        Reminisce,

        // Black creatures and spells
        AccursedCentaur,
        Blackmail,
        Boneknitter,
        AphettoDredging,
        CrownOfSuspicion,
        DirgeOfDread,
        FrightshroudCourier,
        HauntedCadaver,
        Headhunter,
        AphettoVulture,
        AnuridMurkdiver,
        CabalArchon,
        CabalExecutioner,
        CruelRevival,
        DeathPulse,
        DoomedNecromancer,
        DiscipleOfMalice,
        EntrailsFeaster,
        FallenCleric,
        FadeFromMemory,
        FeedingFrenzy,
        FesteringGoblin,
        GluttonousZombie,
        GrinningDemon,
        Infest,
        MiseryCharm,
        ProfanePrayers,
        ShepherdOfRot,
        SpinedBasher,
        NantukoHusk,
        OversoldCemetery,
        ProwlingPangolin,
        RotlungReanimator,
        SoullessOne,
        ScreechingBuzzard,
        SeveredLegion,
        Smother,
        Swat,
        SyphonMind,
        SyphonSoul,
        UndeadGladiator,
        VisaraTheDreadful,
        WretchedAnurid,
        ThrashingMudspawn,

        // Red creatures and spells
        AetherCharge,
        Avarax,
        BlisteringFirecat,
        ButcherOrgg,
        BreakOpen,
        BrightstoneRitual,
        CommandoRaid,
        CrownOfFury,
        SkirkCommando,
        AggravatedAssault,
        AirdropCondor,
        BatteringCraghorn,
        ChargingSlateback,
        DragonRoost,
        DwarvenBlastminer,
        EmbermageGoblin,
        ErraticExplosion,
        FeverCharm,
        FlamestickCourier,
        GoblinPiledriver,
        GoblinPyromancer,
        GoblinSharpshooter,
        GoblinSkyRaider,
        GoblinSledder,
        GoblinTaskmaster,
        NosyGoblin,
        LavamancersSkill,
        LayWaste,
        LightningRift,
        PinpointAvalanche,
        RecklessOne,
        RorixBladewing,
        SearingFlesh,
        Shock,
        SliceAndDice,
        SolarBlast,
        Starstorm,
        Sparksmith,
        SpitfireHandler,
        SkirkProspector,
        ShaleskinBruiser,
        SnappingThragg,
        SpurredWolverine,
        Threaten,
        ThunderOfHooves,
        WaveOfIndifference,

        // Green creatures and spells
        CrownOfVigor,
        AnimalMagnetism,
        BirchloreRangers,
        BloodlineShaman,
        Biorhythm,
        BroodhatchNantuko,
        ElvenRiders,
        ElvishPioneer,
        ElvishScrapper,
        EvergloveCourier,
        ExplosiveVegetation,
        InvigoratingBoon,
        KrosanColossus,
        KrosanGroundshaker,
        LeeryFogbeast,
        KrosanTusker,
        MythicProportions,
        Naturalize,
        RavenousBaloth,
        SnarlingUndorak,
        VenomspoutBrackus,
        BarkhideMauler,
        ElvishVanguard,
        ElvishWarrior,
        HeedlessOne,
        Hystrodon,
        SilklashSpider,
        SilvosRogueElemental,
        SpittingGourna,
        SymbioticBeast,
        TauntingElf,
        SymbioticElf,
        SymbioticWurm,
        ToweringBaloth,
        TreespringLorian,
        Wellwisher,
        ElvishPathcutter,
        SerpentineBasilisk,
        StagBeetle,
        WirewoodElf,
        WirewoodHerald,
        WirewoodSavage,
        WirewoodPride,
        VitalityCharm,
        OverwhelmingInstinct,
        PrimalBoost,
        CentaurGlade,
        WallOfMulch,

        // Artifacts
        DoomCannon,

        // Lands
        BloodstainedMire,
        BarrenMoor,
        ForgottenCave,
        GoblinBurrows,
        LonelySandbar,
        WirewoodLodge,
        SecludedSteppe,
        TranquilThicket,

        // Basic lands
    ) + OnslaughtBasicLands
}
