// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ulg.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Burst of Energy
 * {W}
 * Instant
 * Untap target permanent.
 */
val BurstOfEnergy = card("Burst of Energy") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Instant"
    oracleText = "Untap target permanent."
    spell {
        val t = target("target", TargetPermanent())
        effect = Effects.Untap(t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "3"
        artist = "Mark Brill"
        flavorText = "\"I stand ready to die for our world. Who will stand with me?\"\n—Radiant, archangel"
        imageUri = "https://cards.scryfall.io/normal/front/4/3/43d590d2-cfa3-43d1-9e65-bc68b5a2a3ee.jpg"
    }
}
