// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ulg.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Ghitu Fire-Eater
 * {2}{R}
 * Creature — Human Nomad
 * 2/2
 * {T}, Sacrifice this creature: It deals damage equal to its power to any target.
 */
val GhituFireEater = card("Ghitu Fire-Eater") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Human Nomad"
    oracleText = "{T}, Sacrifice this creature: It deals damage equal to its power to any target."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.Composite(Costs.Tap, Costs.SacrificeSelf)
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(DynamicAmounts.sourcePower(), t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "76"
        artist = "Melissa A. Benson"
        flavorText = "\"They are called 'Mi'uto,' which means 'one use.'\"\n—Jhoira, artificer"
        imageUri = "https://cards.scryfall.io/normal/front/1/3/131dce1c-e9c8-437a-b7aa-36a47049d2d2.jpg"
    }
}
