// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ulg.cards

import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Iron Maiden
 * {3}
 * Artifact
 * At the beginning of each opponent's upkeep, this artifact deals X damage to that player, where X is the number of cards in their hand minus 4.
 */
val IronMaiden = card("Iron Maiden") {
    manaCost = "{3}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "At the beginning of each opponent's upkeep, this artifact deals X damage to that player, where X is the number of cards in their hand minus 4."
    triggeredAbility {
        trigger = Triggers.EachOpponentUpkeep
        effect = DealDamageEffect(4, EffectTarget.PlayerRef(Player.TriggeringPlayer))
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "127"
        artist = "Tom Wänerstrand"
        flavorText = "The maiden is a jealous lover."
        imageUri = "https://cards.scryfall.io/normal/front/a/d/ad925fb0-1d5c-44a0-8347-202a38c23107.jpg"
    }
}
