// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ulg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.GrantKeyword
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Levitation
 * {2}{U}{U}
 * Enchantment
 * Creatures you control have flying.
 */
val Levitation = card("Levitation") {
    manaCost = "{2}{U}{U}"
    colorIdentity = "U"
    typeLine = "Enchantment"
    oracleText = "Creatures you control have flying."
    staticAbility {
        ability = GrantKeyword(Keyword.FLYING, GroupFilter(GameObjectFilter.Creature.youControl()))
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "35"
        artist = "Heather Hudson"
        flavorText = "Barrin's pride in his apprentice was diminished somewhat when he had to get the others back down."
        imageUri = "https://cards.scryfall.io/normal/front/c/a/ca18a2e7-6b01-4d10-82b5-0c1cb6ba0d2b.jpg"
    }
}
