// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ulg.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Might of Oaks
 * {3}{G}
 * Instant
 * Target creature gets +7/+7 until end of turn.
 */
val MightOfOaks = card("Might of Oaks") {
    manaCost = "{3}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Target creature gets +7/+7 until end of turn."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ModifyStats(7, 7, t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "106"
        artist = "Ron Spencer"
        flavorText = "Suddenly, she couldn't see the acorns for the trees."
        imageUri = "https://cards.scryfall.io/normal/front/5/e/5e48b989-bb64-4c71-9921-0a230fed5b11.jpg"
    }
}
