// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ulg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Shivan Phoenix
 * {4}{R}{R}
 * Creature — Phoenix
 * 3/4
 * Flying
 * When this creature dies, return it to its owner's hand.
 */
val ShivanPhoenix = card("Shivan Phoenix") {
    manaCost = "{4}{R}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Phoenix"
    oracleText = "Flying\nWhen this creature dies, return it to its owner's hand."
    power = 3
    toughness = 4
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.Dies
        effect = Effects.Move(EffectTarget.Self, Zone.HAND)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "91"
        artist = "Daren Bader"
        flavorText = "To strike down the phoenix is to slash at the flame."
        imageUri = "https://cards.scryfall.io/normal/front/1/1/112aa0e2-7e4a-4ae8-bedb-d84b4116df5e.jpg"
    }
}
