// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ulg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Silk Net
 * {G}
 * Instant
 * Target creature gets +1/+1 and gains reach until end of turn. (It can block creatures with flying.)
 */
val SilkNet = card("Silk Net") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Target creature gets +1/+1 and gains reach until end of turn. (It can block creatures with flying.)"
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Composite(
            Effects.ModifyStats(1, 1, t),
            Effects.GrantKeyword(Keyword.REACH, t)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "112"
        artist = "Rob Alexander"
        flavorText = "Sometimes it's possible to pull a meal out of thin air."
        imageUri = "https://cards.scryfall.io/normal/front/9/4/9498a97a-0e32-4eb8-9cb4-0698ff3a7ded.jpg"
    }
}
