// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ulg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Sustainer of the Realm
 * {2}{W}{W}
 * Creature — Angel
 * 2/3
 * Flying
 * Whenever this creature blocks, it gets +0/+2 until end of turn.
 */
val SustainerOfTheRealm = card("Sustainer of the Realm") {
    manaCost = "{2}{W}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Angel"
    oracleText = "Flying\nWhenever this creature blocks, it gets +0/+2 until end of turn."
    power = 2
    toughness = 3
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.Blocks
        effect = Effects.ModifyStats(0, 2, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "23"
        artist = "Greg Staples"
        flavorText = "\"The harder you push, the stronger we become.\"\n—Radiant, to Urza"
        imageUri = "https://cards.scryfall.io/normal/front/c/a/ca280e1e-4231-48e5-be1b-965480822c46.jpg"
    }
}
