// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ulg.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Tragic Poet
 * {W}
 * Creature — Human
 * 1/1
 * {T}, Sacrifice this creature: Return target enchantment card from your graveyard to your hand.
 */
val TragicPoet = card("Tragic Poet") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human"
    oracleText = "{T}, Sacrifice this creature: Return target enchantment card from your graveyard to your hand."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Composite(Costs.Tap, Costs.SacrificeSelf)
        val t = target(
            "target",
            TargetObject(filter = TargetFilter(GameObjectFilter.Enchantment.ownedByYou(), zone = Zone.GRAVEYARD))
        )
        effect = Effects.Move(t, Zone.HAND)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "24"
        artist = "Quinton Hoover"
        flavorText = "\"I would weep, but my tears have been stolen; I would shout, but my voice has been taken. Thus, I write.\""
        imageUri = "https://cards.scryfall.io/normal/front/2/9/294aa7fc-12be-4722-b288-de14a28919b2.jpg"
    }
}
