// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ulg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Weatherseed Treefolk
 * {2}{G}{G}{G}
 * Creature — Treefolk
 * 5/3
 * Trample
 * When this creature dies, return it to its owner's hand.
 */
val WeatherseedTreefolk = card("Weatherseed Treefolk") {
    manaCost = "{2}{G}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Treefolk"
    oracleText = "Trample\nWhen this creature dies, return it to its owner's hand."
    power = 5
    toughness = 3
    keywords(Keyword.TRAMPLE)
    triggeredAbility {
        trigger = Triggers.Dies
        effect = Effects.Move(EffectTarget.Self, Zone.HAND)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "116"
        artist = "Heather Hudson"
        imageUri = "https://cards.scryfall.io/normal/front/f/4/f42cce45-3b6a-43e2-8329-68c30135c5c1.jpg"
    }
}
