// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ulg.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Wing Snare
 * {2}{G}
 * Sorcery
 * Destroy target creature with flying.
 */
val WingSnare = card("Wing Snare") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Sorcery"
    oracleText = "Destroy target creature with flying."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "117"
        artist = "Henry Van Der Linde"
        flavorText = "\"Argoth's doom rained from a clear sky. Yavimaya will not share that fate.\"\n—Multani, maro-sorcerer"
        imageUri = "https://cards.scryfall.io/normal/front/1/9/19116d5d-8f2d-4e85-849d-1fbaa67e8cfd.jpg"
    }
}
