package com.wingedsheep.mtg.sets.definitions.dominaria

import com.wingedsheep.mtg.sets.definitions.dominaria.cards.*

/**
 * Dominaria Set (2018)
 *
 * Dominaria was a standalone expansion set that returned to Magic's home plane,
 * featuring historic and legendary themes.
 *
 * Set Code: DOM
 * Release Date: April 27, 2018
 * Card Count: 280
 */
object DominariaSet {

    const val SET_CODE = "DOM"
    const val SET_NAME = "Dominaria"

    /**
     * All cards implemented from this set.
     */
    val allCards = listOf(
        AcademyDrake,
        AcademyJourneymage,
        AdventurousImpulse,
        AdelizTheCinderWind,
        AmaranthineWall,
        ArcaneFlight,
        AesthirGlider,
        AdamantWill,
        ArborArmament,
        AvenSentry,
        ArvadTheCursed,
        BalothGorger,
        BenalishHonorGuard,
        BenalishMarshal,
        Befuddle,
        BlinkOfAnEye,
        BlessedLight,
        BloodtallowCandle,
        BrokenBond,
        CaligoSkinWitch,
        CallTheCavalry,
        CabalPaladin,
        CabalEvangel,
        CastDown,
        Charge,
        CloudreaderSphinx,
        ColdWaterSnapper,
        DAvenantTrapper,
        DarigaazReincarnated,
        DaringArchaeologist,
        DarkBargain,
        DeathbloomThallid,
        DeepFreeze,
        DiligentExcavator,
        DemonicVigor,
        DemonlordBelzenlok,
        DreadShade,
        Divest,
        Divination,
        Dub,
        DrudgeSentinel,
        Eviscerate,
        ExcavationElephant,
        FeralAbomination,
        FieryIntervention,
        FightWithFire,
        FerventStrike,
        FirefistAdept,
        FireElemental,
        FrenziedRage,
        FungalInfection,
        GhituJourneymage,
        GhituChronicler,
        GhituLavarunner,
        GideonsReproach,
        GoblinChainwhirler,
        GoblinWarchief,
        GarnaTheBloodflame,
        GildedLotus,
        GrandWarlordRadha,
        GiftOfGrowth,
        IcyManipulator,
        InvokeTheDivine,
        JhoiraWeatherlightCaptain,
        JosuVessLichKnight,
        JoustingLance,
        Juggernaut,
        HowlingGolem,
        HomaridExplorer,
        KrosanDruid,
        KwendePrideOfFemeref,
        KnightOfNewBenalia,
        KeldonOverseer,
        KeldonRaider,
        LlanowarEnvoy,
        LlanowarElves,
        LlanowarScout,
        LyraDawnbringer,
        MammothSpider,
        MarwynTheNurturer,
        MemorialToFolly,
        MemorialToGenius,
        MemorialToGlory,
        MemorialToWar,
        MerfolkTrickster,
        MesaUnicorn,
        MultaniYavimayasAvatar,
        NaturesSpiral,
        Opt,
        OrcishVandal,
        PardicWanderer,
        PegasusCourser,
        PierceTheSky,
        PrimordialWurm,
        RaffCapashenShipsMage,
        RadiatingLightning,
        RampagingCyclops,
        RatColony,
        Rescue,
        RunAmok,
        SageOfLatNam,
        SealAway,
        SaprolingMigration,
        SergeantAtArms,
        SerraAngel,
        SerraDisciple,
        SiegeGangCommander,
        ShannaSisaysLegacy,
        ShivanFire,
        Skizzik,
        ShortSword,
        SkirkProspector,
        SlimefootTheStowaway,
        SlinnVodaTheRisingDeep,
        SkitteringSurveyor,
        SoulSalvage,
        SporecrownThallid,
        SporeSwarm,
        SparringConstruct,
        SteelLeafChampion,
        StrongholdConfessor,
        Syncopate,
        TatyovaBenthicDruid,
        TempestDjinn,
        TesharAncestorsApostle,
        TerritorialAllosaurus,
        TetsukoUmezawaFugitive,
        ThallidSoothsayer,
        TolarianScholar,
        TraxosScourgeOfKroog,
        TragicPoet,
        UntamedKavu,
        VerdantForce,
        VerixBladewing,
        ViciousOffering,
        VoltaicServant,
        WarlordsFury,
        WeightOfMemory,
        WhisperBloodLiturgist,
        WindgraceAcolyte,
        WizardsRetort,
        YargleGluttonOfUrborg,
        YavimayaSapherd,
        ZhalfirinVoid,
    )
}
