// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.sos.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Charging Strifeknight
 * {2}{R}
 * Creature — Spirit Knight
 * 3/3
 * Haste
 * {T}, Discard a card: Draw a card.
 */
val ChargingStrifeknight = card("Charging Strifeknight") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Spirit Knight"
    oracleText = "Haste\n{T}, Discard a card: Draw a card."
    power = 3
    toughness = 3
    keywords(Keyword.HASTE)
    activatedAbility {
        cost = Costs.Composite(Costs.Tap, Costs.DiscardCard)
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "110"
        artist = "Antonio José Manzanedo"
        flavorText = "His spirit has led this charge for centuries, unaware—or perhaps uncaring—of the way the fields have changed."
        imageUri = "https://cards.scryfall.io/normal/front/9/9/9940d992-1ba1-40ec-9b93-17d773452c4b.jpg"
    }
}
