// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.sos.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.effects.LoseLifeEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature
import com.wingedsheep.sdk.scripting.targets.TargetPlayer


/**
 * Cost of Brilliance
 * {2}{B}
 * Sorcery
 * Target player draws two cards and loses 2 life. Put a +1/+1 counter on up to one target creature.
 */
val CostOfBrilliance = card("Cost of Brilliance") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Sorcery"
    oracleText = "Target player draws two cards and loses 2 life. Put a +1/+1 counter on up to one target creature."
    spell {
        val t1 = target("t1", TargetPlayer())
        val t2 = target("t2", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Composite(
            DrawCardsEffect(2, t1),
            LoseLifeEffect(2, t1),
            AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = t2)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "77"
        artist = "Darren Tan"
        flavorText = "\"There will be moments when you are exhausted, with nothing left to give. Remember them when you finally succeed.\"\n—Embrose, dean of shadow"
        imageUri = "https://cards.scryfall.io/normal/front/3/a/3a46816b-9f75-4c72-9ec6-cded6a4a0d01.jpg"
    }
}
