// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.sos.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.effects.MayEffect


/**
 * Embrace the Paradox
 * {3}{G}{U}
 * Instant
 * Draw three cards. You may put a land card from your hand onto the battlefield tapped.
 */
val EmbraceTheParadox = card("Embrace the Paradox") {
    manaCost = "{3}{G}{U}"
    colorIdentity = "UG"
    typeLine = "Instant"
    oracleText = "Draw three cards. You may put a land card from your hand onto the battlefield tapped."
    spell {
        effect = Effects.Composite(
            DrawCardsEffect(3),
            MayEffect(Patterns.Hand.putFromHand(filter = GameObjectFilter.Land, entersTapped = true))
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "186"
        artist = "Julian Kok Joon Wen"
        flavorText = "\"Every lecture you attended—every theorem you memorized and equation you solved—has led to this first step into uncertainty.\"\n—Professor Deekah"
        imageUri = "https://cards.scryfall.io/normal/front/c/0/c0cf5e0f-3668-46f2-850d-d91a538e8ead.jpg"
    }
}
