// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.sos.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Muse's Encouragement
 * {4}{U}
 * Instant
 * Create a 3/3 blue and red Elemental creature token with flying.
 * Surveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)
 */
val MusesEncouragement = card("Muse's Encouragement") {
    manaCost = "{4}{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Create a 3/3 blue and red Elemental creature token with flying.\nSurveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)"
    spell {
        effect = Effects.Composite(
            Effects.CreateToken(
                power = 3,
                toughness = 3,
                colors = setOf(Color.BLUE, Color.RED),
                creatureTypes = setOf("Elemental"),
                keywords = setOf(Keyword.FLYING),
                imageUri = "https://cards.scryfall.io/normal/front/b/5/b5b2df9c-228f-4441-a962-46b335bb356e.jpg?1782723481"
            ),
            Patterns.Library.surveil(2)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "61"
        artist = "Oriana Menendez"
        flavorText = "Many Prismari students find their best ideas while under the gaze of the Muse."
        imageUri = "https://cards.scryfall.io/normal/front/c/5/c59e0004-1d6a-42a1-8ce4-31da2af2e1bf.jpg"
    }
}
