// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.sos.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.EntersWithDynamicCounters
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Pterafractyl
 * {X}{G}{U}
 * Creature — Dinosaur Fractal
 * 1/0
 * Flying
 * This creature enters with X +1/+1 counters on it.
 * When this creature enters, you gain 2 life.
 */
val Pterafractyl = card("Pterafractyl") {
    manaCost = "{X}{G}{U}"
    colorIdentity = "UG"
    typeLine = "Creature — Dinosaur Fractal"
    oracleText = "Flying\nThis creature enters with X +1/+1 counters on it.\nWhen this creature enters, you gain 2 life."
    power = 1
    toughness = 0
    keywords(Keyword.FLYING)
    replacementEffect(EntersWithDynamicCounters(count = DynamicAmount.XValue))
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = GainLifeEffect(2)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "215"
        artist = "Andrew Mar"
        flavorText = "\"Be careful when traversing the Paradox Gardens. Not all experiments are perfectly contained.\"\n—Professor Berta"
        imageUri = "https://cards.scryfall.io/normal/front/e/c/ecd33152-e290-4505-addd-a8d08cefdddd.jpg"
    }
}
