// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.sos.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.ConditionalEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Withering Curse
 * {1}{B}{B}
 * Sorcery
 * All creatures get -2/-2 until end of turn.
 * Infusion — If you gained life this turn, destroy all creatures instead.
 */
val WitheringCurse = card("Withering Curse") {
    manaCost = "{1}{B}{B}"
    colorIdentity = "B"
    typeLine = "Sorcery"
    oracleText = "All creatures get -2/-2 until end of turn.\nInfusion — If you gained life this turn, destroy all creatures instead."
    spell {
        effect = ConditionalEffect(
            condition = Conditions.YouGainedLifeThisTurn,
            effect = Effects.ForEachInGroup(
                GroupFilter(GameObjectFilter.Creature),
                Effects.Move(EffectTarget.Self, Zone.GRAVEYARD, byDestruction = true),
                noRegenerate = false
            ),
            elseEffect = Effects.ForEachInGroup(
                GroupFilter(GameObjectFilter.Creature),
                Effects.ModifyStats(-2, -2, EffectTarget.Self)
            )
        )
    }
    metadata {
        rarity = Rarity.MYTHIC
        collectorNumber = "105"
        artist = "Tuan Duong Chu"
        flavorText = "Although lumarets are small magical creatures, they can gather to eliminate larger threats."
        imageUri = "https://cards.scryfall.io/normal/front/5/0/50aaf618-dddb-4cbe-8231-d634b4498563.jpg"
    }
}
