// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tla.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Cat-Owl
 * {3}{W/U}
 * Creature — Cat Bird
 * 3/3
 * Flying
 * Whenever this creature attacks, untap target artifact or creature.
 */
val CatOwl = card("Cat-Owl") {
    manaCost = "{3}{W/U}"
    colorIdentity = "WU"
    typeLine = "Creature — Cat Bird"
    oracleText = "Flying\nWhenever this creature attacks, untap target artifact or creature."
    power = 3
    toughness = 3
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.self.attacks()
        val t = target(TargetFilter(GameObjectFilter.Artifact or GameObjectFilter.Creature))
        effect = Effects.Untap(t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "212"
        artist = "Thomas Chamberlain-Keen"
        flavorText = "When it's feeling bored, it chases itself."
        imageUri = "https://cards.scryfall.io/normal/front/d/7/d7df3391-dbe5-4eb4-85c1-037c5f3ea971.jpg"
    }
}
