// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.core.Step
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.conditions.YouWereAttackedThisStep


/**
 * Deep Wood
 * {1}{G}
 * Instant
 * Cast this spell only during the declare attackers step and only if you've been attacked this step.
 * Prevent all damage that would be dealt to you this turn by attacking creatures.
 */
val DeepWood = card("Deep Wood") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    spell {
        castOnlyDuring(Step.DECLARE_ATTACKERS)
        castOnlyIf(YouWereAttackedThisStep)
        effect = Effects.PreventDamageFromAttackingCreatures()
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "162"
        artist = "Paolo Parente"
        imageUri = "https://cards.scryfall.io/normal/front/4/2/4216c5aa-9df0-4e7c-b3e9-a3f712b17ce7.jpg"
    }
}
