// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.SkipUntapEffect
import com.wingedsheep.sdk.scripting.targets.TargetOpponent


/**
 * Exhaustion
 * {2}{U}
 * Sorcery
 * Creatures and lands target opponent controls don't untap during their next untap step.
 */
val Exhaustion = card("Exhaustion") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    spell {
        val t = target("target", TargetOpponent())
        effect = SkipUntapEffect(t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "54"
        artist = "DiTerlizzi"
        imageUri = "https://cards.scryfall.io/normal/front/9/d/9d6a5c33-cf74-4cec-a4f4-1aac9e7b8f79.jpg"
    }
}
