// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Rowan Treefolk
 * {3}{G}
 * Creature — Treefolk
 * 3/4
 */
val RowanTreefolk = card("Rowan Treefolk") {
    manaCost = "{3}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Treefolk"
    power = 3
    toughness = 4
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "184"
        artist = "Gerry Grace"
        flavorText = "One of the forest's best protectors is the forest itself."
        imageUri = "https://cards.scryfall.io/normal/front/8/5/852a0956-8558-4754-ab57-6f1cc4de740e.jpg"
    }
}
