// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.TargetOpponent
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Theft of Dreams
 * {2}{U}
 * Sorcery
 * Draw a card for each tapped creature target opponent controls.
 */
val TheftOfDreams = card("Theft of Dreams") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    spell {
        val t = target("target", TargetOpponent())
        effect = DrawCardsEffect(DynamicAmount.AggregateBattlefield(Player.TargetOpponent, GameObjectFilter.Creature.tapped()))
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "72"
        artist = "Adam Rex"
        flavorText = "Energy is never lost, only transformed."
        imageUri = "https://cards.scryfall.io/normal/front/2/9/29019e28-4ef8-4732-9972-0a47305fe303.jpg"
    }
}
