// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Volcanic Hammer
 * {1}{R}
 * Sorcery
 * Volcanic Hammer deals 3 damage to any target.
 */
val VolcanicHammer = card("Volcanic Hammer") {
    manaCost = "{1}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    spell {
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(3, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "154"
        artist = "Christopher Rush"
        flavorText = "Cast the weight as though it were a die, to see a rival's fate."
        imageUri = "https://cards.scryfall.io/normal/front/9/5/9563d7c1-4ed1-4919-b0b8-ea1ec9d4bbf6.jpg"
    }
}
