// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Wall of Granite
 * {2}{R}
 * Creature — Wall
 * 0/7
 * Defender (This creature can't attack.)
 */
val WallOfGranite = card("Wall of Granite") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Wall"
    power = 0
    toughness = 7
    keywords(Keyword.DEFENDER)
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "155"
        artist = "Kev Walker"
        flavorText = "The wisest man builds his house behind the rock."
        imageUri = "https://cards.scryfall.io/normal/front/7/0/70c5ac71-bf45-4b99-8184-36ce88dd728a.jpg"
    }
}
