// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Suntail Hawk
 * {W}
 * Creature — Bird
 * 1/1
 * Flying
 */
val SuntailHawk = card("Suntail Hawk") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Creature — Bird"
    oracleText = "Flying"
    power = 1
    toughness = 1
    keywords(Keyword.FLYING)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "28"
        artist = "Heather Hudson"
        flavorText = "\"Our forebears once flew like this—carefree, needing nothing but a warm nest and a full belly. Our intellect may be more burden than blessing.\"\n—Commander Eesha"
        imageUri = "https://cards.scryfall.io/normal/front/5/f/5fbdae0b-b4aa-40ff-9017-b4349bd6b627.jpg"
    }
}
