package com.wingedsheep.engine.mechanics.mana

import com.wingedsheep.engine.core.GameEvent
import com.wingedsheep.engine.core.tap
import com.wingedsheep.engine.core.ZoneChangeEvent
import com.wingedsheep.engine.mechanics.HarmonizeGrants
import com.wingedsheep.engine.state.GameState
import com.wingedsheep.engine.state.ZoneKey
import com.wingedsheep.engine.state.components.battlefield.TappedComponent
import com.wingedsheep.engine.state.components.identity.CardComponent
import com.wingedsheep.engine.state.components.identity.ControllerComponent
import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.ManaCost
import com.wingedsheep.sdk.core.ManaSymbol
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.model.CardDefinition
import com.wingedsheep.sdk.model.EntityId
import com.wingedsheep.sdk.scripting.AlternativePaymentChoice
import com.wingedsheep.sdk.scripting.KeywordAbility

/**
 * Result of applying alternative payment.
 *
 * @property reducedCost The mana cost after alternative payment reductions
 * @property newState The game state after applying the payment (e.g., exiled cards, tapped creatures)
 * @property events Events generated by the payment (exile, tap events)
 */
data class AlternativePaymentResult(
    val reducedCost: ManaCost,
    val newState: GameState,
    val events: List<GameEvent>
)

/**
 * Handles alternative payment methods like Delve and Convoke.
 *
 * **Delve**: Exile cards from your graveyard. Each card exiled this way pays for {1}.
 * **Convoke**: Tap untapped creatures you control. Each creature tapped this way pays for
 *             {1} or one mana of that creature's color.
 *
 * Alternative payments are applied AFTER cost reductions (like Ghalta/Affinity) but BEFORE
 * normal mana payment. Keyword checks go through [GrantedKeywordResolver] so both intrinsic
 * (printed) and granted (static-ability) convoke/delve resolve through one code path.
 */
class AlternativePaymentHandler(
    private val resolver: GrantedKeywordResolver? = null
) {

    /**
     * Apply alternative payment choices to reduce the effective cost.
     *
     * @param state The current game state
     * @param cost The cost to pay (after cost reductions)
     * @param payment The player's alternative payment choices
     * @param playerId The player making the payment
     * @param cardDef The card being cast (to verify it has Delve/Convoke)
     * @param cardId The spell's entity id, used to honor a runtime-granted Harmonize
     *   (Songcrafter Mage) keyed to that entity. Null falls back to the printed keyword only.
     * @return Result containing reduced cost, updated state, and generated events
     */
    fun apply(
        state: GameState,
        cost: ManaCost,
        payment: AlternativePaymentChoice,
        playerId: EntityId,
        cardDef: CardDefinition,
        cardId: EntityId? = null
    ): AlternativePaymentResult {
        var currentState = state
        var reducedCost = cost
        val events = mutableListOf<GameEvent>()

        // Handle Delve
        if (payment.delvedCards.isNotEmpty()) {
            val hasDelve = effectivelyHasKeyword(state, playerId, cardDef, Keyword.DELVE)
            if (hasDelve) {
                val delveResult = applyDelve(currentState, reducedCost, payment.delvedCards, playerId)
                currentState = delveResult.newState
                reducedCost = delveResult.reducedCost
                events.addAll(delveResult.events)
            }
        }

        // Handle Convoke
        if (payment.convokedCreatures.isNotEmpty()) {
            val hasConvoke = effectivelyHasKeyword(state, playerId, cardDef, Keyword.CONVOKE)
            if (hasConvoke) {
                val convokeResult = applyConvoke(currentState, reducedCost, payment.convokedCreatures, playerId)
                currentState = convokeResult.newState
                reducedCost = convokeResult.reducedCost
                events.addAll(convokeResult.events)
            }
        }

        // Handle Harmonize — tap one creature you control to reduce the generic cost by its power.
        val harmonizeCreature = payment.harmonizeCreature
        if (harmonizeCreature != null && hasHarmonize(state, cardId, cardDef)) {
            val harmonizeResult = applyHarmonize(currentState, reducedCost, harmonizeCreature, playerId)
            currentState = harmonizeResult.newState
            reducedCost = harmonizeResult.reducedCost
            events.addAll(harmonizeResult.events)
        }

        return AlternativePaymentResult(reducedCost, currentState, events)
    }

    /**
     * Apply Delve payment by exiling cards from graveyard.
     */
    private fun applyDelve(
        state: GameState,
        cost: ManaCost,
        delvedCards: List<EntityId>,
        playerId: EntityId
    ): AlternativePaymentResult {
        var currentState = state
        val events = mutableListOf<GameEvent>()
        var genericReduction = 0

        val graveyardZone = ZoneKey(playerId, Zone.GRAVEYARD)
        val exileZone = ZoneKey(playerId, Zone.EXILE)

        for (cardId in delvedCards) {
            // Verify card is in player's graveyard
            if (cardId !in currentState.getZone(graveyardZone)) {
                continue // Skip invalid cards
            }

            val cardComponent = currentState.getEntity(cardId)?.get<CardComponent>()
                ?: continue

            // Move card from graveyard to exile
            currentState = currentState.removeFromZone(graveyardZone, cardId)
            currentState = currentState.addToZone(exileZone, cardId)

            events.add(
                ZoneChangeEvent(
                    entityId = cardId,
                    entityName = cardComponent.name,
                    fromZone = Zone.GRAVEYARD,
                    toZone = Zone.EXILE,
                    ownerId = playerId
                )
            )

            genericReduction++
        }

        val reducedCost = reduceGenericCost(cost, genericReduction)
        return AlternativePaymentResult(reducedCost, currentState, events)
    }

    /**
     * Apply Convoke payment by tapping creatures.
     */
    private fun applyConvoke(
        state: GameState,
        cost: ManaCost,
        convokedCreatures: Map<EntityId, com.wingedsheep.sdk.scripting.ConvokePayment>,
        playerId: EntityId
    ): AlternativePaymentResult {
        var currentState = state
        var reducedCost = cost
        val events = mutableListOf<GameEvent>()

        val battlefieldZone = ZoneKey(playerId, Zone.BATTLEFIELD)

        for ((creatureId, payment) in convokedCreatures) {
            // Verify creature is on player's battlefield and is untapped
            if (creatureId !in currentState.getZone(battlefieldZone)) {
                continue // Skip invalid creatures
            }

            val container = currentState.getEntity(creatureId) ?: continue
            val cardComponent = container.get<CardComponent>() ?: continue

            // Must be a creature
            if (!cardComponent.typeLine.isCreature) {
                continue
            }

            // Must be untapped
            if (container.has<TappedComponent>()) {
                continue
            }

            // Must be controlled by the player
            val controller = container.get<ControllerComponent>()?.playerId
            if (controller != playerId) {
                continue
            }

            // Tap the creature
            val (tappedState, tapEvent) = tap(currentState, creatureId)
            currentState = tappedState
            tapEvent?.let(events::add)

            // Apply the payment
            val paymentColor = payment.color
            if (paymentColor != null) {
                // Pay for colored mana
                reducedCost = reduceColoredCost(reducedCost, paymentColor)
            } else {
                // Pay for generic mana
                reducedCost = reduceGenericCost(reducedCost, 1)
            }
        }

        return AlternativePaymentResult(reducedCost, currentState, events)
    }

    /**
     * Apply Harmonize payment by tapping a single creature you control, reducing the
     * generic portion of the cost by that creature's (projected) power. Invalid choices
     * (creature missing, tapped, not controlled, not a creature) are silently ignored —
     * the enumerator and handler validation gate the legal choices.
     */
    private fun applyHarmonize(
        state: GameState,
        cost: ManaCost,
        creatureId: EntityId,
        playerId: EntityId
    ): AlternativePaymentResult {
        val battlefieldZone = ZoneKey(playerId, Zone.BATTLEFIELD)
        if (creatureId !in state.getZone(battlefieldZone)) {
            return AlternativePaymentResult(cost, state, emptyList())
        }
        val container = state.getEntity(creatureId)
            ?: return AlternativePaymentResult(cost, state, emptyList())
        val cardComponent = container.get<CardComponent>()
            ?: return AlternativePaymentResult(cost, state, emptyList())
        val projected = state.projectedState
        if (!projected.isCreature(creatureId)) return AlternativePaymentResult(cost, state, emptyList())
        if (container.has<TappedComponent>()) return AlternativePaymentResult(cost, state, emptyList())
        if (container.get<ControllerComponent>()?.playerId != playerId) {
            return AlternativePaymentResult(cost, state, emptyList())
        }

        // Use projected power so continuous effects / +1/+1 counters are honored. A
        // negative power reduces the cost by nothing (you can't add to it).
        val power = (projected.getPower(creatureId) ?: 0).coerceAtLeast(0)
        val (newState, tapEvent) = tap(state, creatureId)
        val events = listOfNotNull<GameEvent>(tapEvent)
        val reducedCost = if (power > 0) reduceGenericCost(cost, power) else cost
        return AlternativePaymentResult(reducedCost, newState, events)
    }

    /**
     * True when the card effectively has Harmonize — printed on [cardDef] or granted at runtime
     * to [cardId] (Songcrafter Mage). Falls back to the printed keyword when state/cardId are
     * unavailable.
     */
    private fun hasHarmonize(state: GameState?, cardId: EntityId?, cardDef: CardDefinition): Boolean {
        if (cardDef.keywordAbilities.any { it is KeywordAbility.Harmonize }) return true
        if (state == null || cardId == null) return false
        return HarmonizeGrants.effectiveHarmonize(state, cardId, cardDef) != null
    }

    /**
     * Reduce generic mana cost by specified amount.
     */
    private fun reduceGenericCost(cost: ManaCost, reduction: Int): ManaCost {
        return cost.reduceGeneric(reduction)
    }

    /**
     * Reduce colored mana cost by one of the specified color.
     *
     * Under CR 107.4e a hybrid symbol like {W/U} is itself a colored mana symbol of both
     * colors, and CR 702.51a lets convoke pay "colored mana" by tapping a creature of that
     * color — so a white creature paying convoke can cover a {W/U} pip (choosing its white
     * half). A monocolored hybrid pip like {2/B} is also a colored symbol of its color, so a
     * black creature can pay its colored side. Prefer an exact colored match first so we don't
     * waste a hybrid pip when a plain colored pip is available.
     */
    private fun reduceColoredCost(cost: ManaCost, color: Color): ManaCost {
        val mutableSymbols = cost.symbols.toMutableList()
        val coloredSymbol = ManaSymbol.Colored(color)

        val exactIndex = mutableSymbols.indexOfFirst { it == coloredSymbol }
        if (exactIndex >= 0) {
            mutableSymbols.removeAt(exactIndex)
            return ManaCost(mutableSymbols)
        }

        val hybridIndex = mutableSymbols.indexOfFirst { symbol ->
            (symbol is ManaSymbol.Hybrid && (symbol.color1 == color || symbol.color2 == color)) ||
                (symbol is ManaSymbol.MonocolorHybrid && symbol.color == color)
        }
        if (hybridIndex >= 0) {
            mutableSymbols.removeAt(hybridIndex)
        }

        return ManaCost(mutableSymbols)
    }

    /**
     * Calculate the reduced cost after alternative payment without mutating state.
     * Used during validation to check if the player can afford the spell.
     *
     * [state] and [playerId] are used to detect keywords granted by battlefield permanents
     * (e.g., Eirdu: "Creature spells you cast have convoke."). Pass null to keep the legacy
     * behaviour that only consults the card's printed keywords.
     */
    fun calculateReducedCost(
        cost: ManaCost,
        payment: AlternativePaymentChoice,
        cardDef: CardDefinition,
        state: GameState? = null,
        playerId: EntityId? = null,
        cardId: EntityId? = null
    ): ManaCost {
        var reducedCost = cost

        val hasDelve = effectivelyHasKeyword(state, playerId, cardDef, Keyword.DELVE)
        if (payment.delvedCards.isNotEmpty() && hasDelve) {
            reducedCost = reduceGenericCost(reducedCost, payment.delvedCards.size)
        }

        val hasConvoke = effectivelyHasKeyword(state, playerId, cardDef, Keyword.CONVOKE)
        if (payment.convokedCreatures.isNotEmpty() && hasConvoke) {
            for ((_, convokePayment) in payment.convokedCreatures) {
                val paymentColor = convokePayment.color
                reducedCost = if (paymentColor != null) {
                    reduceColoredCost(reducedCost, paymentColor)
                } else {
                    reduceGenericCost(reducedCost, 1)
                }
            }
        }

        val harmonizeCreature = payment.harmonizeCreature
        if (harmonizeCreature != null && state != null && hasHarmonize(state, cardId, cardDef)) {
            val power = (state.projectedState.getPower(harmonizeCreature) ?: 0).coerceAtLeast(0)
            if (power > 0) reducedCost = reduceGenericCost(reducedCost, power)
        }

        return reducedCost
    }

    /**
     * True when [cardDef] effectively has [keyword] — either printed on the card or granted by
     * a battlefield permanent [playerId] controls. Returns the printed check when
     * state/playerId/resolver aren't available.
     */
    private fun effectivelyHasKeyword(
        state: GameState?,
        playerId: EntityId?,
        cardDef: CardDefinition,
        keyword: Keyword
    ): Boolean {
        if (cardDef.keywords.contains(keyword)) return true
        if (state == null || playerId == null || resolver == null) return false
        return resolver.hasKeyword(state, playerId, cardDef, keyword)
    }

    /**
     * Apply convoke payment for an activated ability that has its own convoke mechanic.
     * Unlike spell-level convoke (which checks the CONVOKE keyword on the card), this is used
     * when the ability itself grants convoke-like behavior (e.g., Heirloom Epic).
     *
     * @param state The current game state
     * @param cost The mana cost to pay
     * @param payment The player's convoke choices
     * @param playerId The player making the payment
     * @return Result containing reduced cost, updated state, and generated events
     */
    fun applyConvokeForAbility(
        state: GameState,
        cost: ManaCost,
        payment: AlternativePaymentChoice,
        playerId: EntityId
    ): AlternativePaymentResult {
        if (payment.convokedCreatures.isEmpty()) {
            return AlternativePaymentResult(cost, state, emptyList())
        }
        return applyConvoke(state, cost, payment.convokedCreatures, playerId)
    }

    /**
     * Calculate the reduced cost after convoke payment for an activated ability,
     * without mutating state. Used during validation.
     */
    fun calculateReducedCostForAbility(
        cost: ManaCost,
        payment: AlternativePaymentChoice
    ): ManaCost {
        var reducedCost = cost
        if (payment.convokedCreatures.isNotEmpty()) {
            for ((_, convokePayment) in payment.convokedCreatures) {
                val paymentColor = convokePayment.color
                reducedCost = if (paymentColor != null) {
                    reduceColoredCost(reducedCost, paymentColor)
                } else {
                    reduceGenericCost(reducedCost, 1)
                }
            }
        }
        return reducedCost
    }

    /**
     * Apply a waterbend payment for an activated ability (Avatar: The Last Airbender).
     *
     * Waterbend is "Pay [cost]. For each generic mana in that cost, you may tap an untapped
     * artifact or creature you control rather than pay that mana." One case of the shared
     * [applyTapForGeneric] rail: eligibility [TapForGeneric.WATERBEND], and no cap beyond the
     * generic mana remaining in the cost (the whole cost *is* the waterbend cost).
     */
    fun applyWaterbendForAbility(
        state: GameState,
        cost: ManaCost,
        payment: AlternativePaymentChoice,
        playerId: EntityId
    ): AlternativePaymentResult =
        applyTapForGeneric(state, cost, payment, playerId, TapForGeneric.WATERBEND)

    /**
     * Apply a waterbend payment for a **spell's** additional waterbend cost (Avatar: The Last
     * Airbender — "As an additional cost to cast this spell, waterbend {N}"). Identical to the
     * ability variant but the reduction is bounded by [maxGenericReduction] — the waterbend amount
     * N — so the taps pay only the waterbend portion of the cost and never the spell's own generic
     * mana. The caller adds {N} generic to the spell's cost first, so capping at N leaves at least
     * the spell's printed generic to be paid with real mana (CR: "for each generic mana in that
     * cost").
     */
    fun applyWaterbendForSpell(
        state: GameState,
        cost: ManaCost,
        payment: AlternativePaymentChoice,
        playerId: EntityId,
        maxGenericReduction: Int
    ): AlternativePaymentResult =
        applyTapForGeneric(state, cost, payment, playerId, TapForGeneric.WATERBEND, maxGenericReduction)

    /**
     * Apply an **improvise** payment for a spell (CR 702.126a: "For each generic mana in this
     * spell's total cost, you may tap an untapped artifact you control rather than pay that
     * mana"). The artifacts-only case of the shared [applyTapForGeneric] rail.
     *
     * Improvise is neither an additional nor an alternative cost and applies only after the total
     * cost is determined (CR 702.126b), so [cost] here is already the fully-modified total cost
     * and the only bound is its generic portion — no extra cap. Colored pips are never touched.
     *
     * Ignored unless the spell effectively has improvise (printed, or granted to it by a
     * permanent such as Ironheart, Clever Champion) — so a stale or forged choice can't tap
     * artifacts for a spell that never had the keyword.
     */
    fun applyImproviseForSpell(
        state: GameState,
        cost: ManaCost,
        payment: AlternativePaymentChoice,
        playerId: EntityId,
        cardDef: CardDefinition
    ): AlternativePaymentResult {
        if (!effectivelyHasKeyword(state, playerId, cardDef, Keyword.IMPROVISE)) {
            return AlternativePaymentResult(cost, state, emptyList())
        }
        return applyTapForGeneric(state, cost, payment, playerId, TapForGeneric.IMPROVISE)
    }

    /**
     * Calculate the reduced cost after a waterbend payment for an activated ability,
     * without mutating state. Used during validation/affordability.
     */
    fun calculateReducedCostForWaterbend(
        cost: ManaCost,
        payment: AlternativePaymentChoice
    ): ManaCost = calculateReducedCostForTapForGeneric(cost, payment, Int.MAX_VALUE)

    /**
     * Calculate the reduced cost after a waterbend payment, capping the generic reduction at
     * [maxGenericReduction] (the waterbend amount for a spell-level cost; [Int.MAX_VALUE] for an
     * ability whose whole cost is the waterbend cost). Used during validation/affordability.
     */
    fun calculateReducedCostForWaterbend(
        cost: ManaCost,
        payment: AlternativePaymentChoice,
        maxGenericReduction: Int
    ): ManaCost = calculateReducedCostForTapForGeneric(cost, payment, maxGenericReduction)

    /**
     * Calculate the reduced cost after an improvise payment (CR 702.126a), without mutating
     * state. Bounded only by the generic mana in the total cost. Returns [cost] unchanged when
     * the spell doesn't effectively have improvise.
     *
     * [state] and [playerId] are required, not optional: improvise is grantable at runtime
     * (Ironheart, Clever Champion), and without them [effectivelyHasKeyword] degrades to a
     * printed-keyword-only check — a caller that omitted them would silently make every *granted*
     * improvise vanish from the cost, with no error to notice.
     */
    fun calculateReducedCostForImprovise(
        cost: ManaCost,
        payment: AlternativePaymentChoice,
        cardDef: CardDefinition,
        state: GameState,
        playerId: EntityId
    ): ManaCost {
        if (!effectivelyHasKeyword(state, playerId, cardDef, Keyword.IMPROVISE)) return cost
        return calculateReducedCostForTapForGeneric(cost, payment, Int.MAX_VALUE)
    }

    /**
     * Shared "each tapped permanent pays {1} generic" cost math for [TapForGeneric] payments.
     * Every tap removes one generic, bounded by the generic left in [cost] and by
     * [maxGenericReduction]. Eligibility isn't re-checked here — this is the no-state
     * affordability twin of [applyTapForGeneric], which does validate.
     */
    private fun calculateReducedCostForTapForGeneric(
        cost: ManaCost,
        payment: AlternativePaymentChoice,
        maxGenericReduction: Int
    ): ManaCost {
        var reducedCost = cost
        var applied = 0
        for (i in 0 until payment.tapForGenericPermanents.size) {
            if (applied >= maxGenericReduction) break
            if (reducedCost.genericAmount <= 0) break
            reducedCost = reduceGenericCost(reducedCost, 1)
            applied++
        }
        return reducedCost
    }

    /**
     * Tap the chosen permanents, each reducing the generic portion of [cost] by {1}. The one
     * rail behind every "tap untapped permanents you control, each paying {1} generic" mechanic;
     * [eligibility] is the only thing that differs between them (see [TapForGeneric]).
     *
     * Invalid choices (not on battlefield, tapped, not controlled, wrong type) are silently
     * ignored — the enumerator and handler validation gate the legal choices. Reads
     * types/controller from projected state so animated lands and type-changed permanents are
     * honored (CR battlefield reads).
     */
    private fun applyTapForGeneric(
        state: GameState,
        cost: ManaCost,
        payment: AlternativePaymentChoice,
        playerId: EntityId,
        eligibility: TapForGeneric,
        maxGenericReduction: Int = Int.MAX_VALUE
    ): AlternativePaymentResult {
        if (payment.tapForGenericPermanents.isEmpty() || maxGenericReduction <= 0) {
            return AlternativePaymentResult(cost, state, emptyList())
        }

        var currentState = state
        var reducedCost = cost
        var applied = 0
        val events = mutableListOf<GameEvent>()

        val battlefieldZone = ZoneKey(playerId, Zone.BATTLEFIELD)
        // Tapping a permanent this way changes neither type nor controller, so the projection
        // computed once from the starting state is valid for every eligibility check below.
        val projected = state.projectedState

        for (permanentId in payment.tapForGenericPermanents) {
            // Bound by the generic mana in the cost (CR 702.126a / waterbend: "for each generic
            // mana in that cost") and, for a spell-level waterbend cost, by its amount N.
            if (applied >= maxGenericReduction) break
            if (reducedCost.genericAmount <= 0) break
            if (permanentId !in currentState.getZone(battlefieldZone)) continue
            val container = currentState.getEntity(permanentId) ?: continue
            // Card-backed permanents only, mirroring the eligibility scan in
            // `CostEnumerationUtils.findTapForGenericPermanents` (which needs the name). Every
            // battlefield permanent carries one today, so this is symmetry rather than a live
            // guard — but the two sides of the same payment should agree on what qualifies.
            container.get<CardComponent>() ?: continue

            // Must be an untapped, eligible permanent the player controls.
            if (!eligibility.matches(projected, permanentId)) continue
            if (container.has<TappedComponent>()) continue
            if (projected.getController(permanentId) != playerId) continue

            val (tappedState, tapEvent) = tap(currentState, permanentId)
            currentState = tappedState
            tapEvent?.let(events::add)
            reducedCost = reduceGenericCost(reducedCost, 1)
            applied++
        }

        return AlternativePaymentResult(reducedCost, currentState, events)
    }
}
