FROM node:18-alpine AS build
ARG COMMIT_HASH=unknown
ENV VITE_COMMIT_HASH=$COMMIT_HASH
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
