// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pcy.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Bog Glider
 * {2}{B}
 * Creature — Human Mercenary
 * 1/1
 * Flying
 * {T}, Sacrifice a land: Search your library for a Mercenary permanent card with mana value 2 or less, put it onto the battlefield, then shuffle.
 */
val BogGlider = card("Bog Glider") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Human Mercenary"
    oracleText = "Flying\n{T}, Sacrifice a land: Search your library for a Mercenary permanent card with mana value 2 or less, put it onto the battlefield, then shuffle."
    power = 1
    toughness = 1
    keywords(Keyword.FLYING)
    activatedAbility {
        cost = Costs.Composite(Costs.Tap, Costs.Sacrifice(GameObjectFilter.Land))
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Any.withSubtype("Mercenary"),
            count = 2,
            destination = SearchDestination.BATTLEFIELD
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "58"
        artist = "Brian Snõddy"
        imageUri = "https://cards.scryfall.io/normal/front/0/8/086a5620-704b-47a9-9a5d-73e28631d6f8.jpg"
    }
}
