// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pcy.cards

import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.CanBlockAnyNumber


/**
 * Entangler
 * {2}{W}{W}
 * Enchantment — Aura
 * Enchant creature
 * Enchanted creature can block any number of creatures.
 */
val Entangler = card("Entangler") {
    manaCost = "{2}{W}{W}"
    colorIdentity = "W"
    typeLine = "Enchantment — Aura"
    oracleText = "Enchant creature\nEnchanted creature can block any number of creatures."
    auraTarget = Targets.Creature
    staticAbility {
        ability = CanBlockAnyNumber()
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "7"
        artist = "D. Alexander Gregory"
        flavorText = "\"Tell me again,\" said Latulla, raising her fist, \"how just one woman held back an entire Keldon platoon.\""
        imageUri = "https://cards.scryfall.io/normal/front/e/c/ecc20785-4512-4ef6-8f62-928482cb585f.jpg"
    }
}
