// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pcy.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.ModifyStats


/**
 * Greel's Caress
 * {1}{B}
 * Enchantment — Aura
 * Flash
 * Enchant creature
 * Enchanted creature gets -3/-0.
 */
val GreelsCaress = card("Greel's Caress") {
    manaCost = "{1}{B}"
    colorIdentity = "B"
    typeLine = "Enchantment — Aura"
    oracleText = "Flash\nEnchant creature\nEnchanted creature gets -3/-0."
    keywords(Keyword.FLASH)
    auraTarget = Targets.Creature
    staticAbility {
        ability = ModifyStats(-3, 0)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "67"
        artist = "Chippy"
        flavorText = "Greel's grin is far less loathsome than his touch."
        imageUri = "https://cards.scryfall.io/normal/front/5/b/5b25ce3f-fab3-40f8-8a16-fe580f3d97a5.jpg"
    }
}
