// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pcy.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.SkipUntapEffect
import com.wingedsheep.sdk.scripting.targets.TargetPlayer


/**
 * Mana Vapors
 * {1}{U}
 * Sorcery
 * Lands target player controls don't untap during their next untap step.
 */
val ManaVapors = card("Mana Vapors") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Lands target player controls don't untap during their next untap step."
    spell {
        val t = target("target", TargetPlayer())
        effect = SkipUntapEffect(t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "38"
        artist = "Mark Romanoski"
        flavorText = "The scent of magic can rob you of your senses, blinding you to the world."
        imageUri = "https://cards.scryfall.io/normal/front/0/b/0b6dfe49-9fd6-4fa0-b73e-e6470d8e7ca7.jpg"
    }
}
