// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pcy.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.PayOrSufferEffect
import com.wingedsheep.sdk.scripting.effects.SacrificeSelfEffect


/**
 * Pit Raptor
 * {2}{B}{B}
 * Creature — Bird Mercenary
 * 4/3
 * Flying, first strike
 * At the beginning of your upkeep, sacrifice this creature unless you pay {2}{B}{B}.
 */
val PitRaptor = card("Pit Raptor") {
    manaCost = "{2}{B}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Bird Mercenary"
    oracleText = "Flying, first strike\nAt the beginning of your upkeep, sacrifice this creature unless you pay {2}{B}{B}."
    power = 4
    toughness = 3
    keywords(Keyword.FLYING, Keyword.FIRST_STRIKE)
    triggeredAbility {
        trigger = Triggers.YourUpkeep
        effect = PayOrSufferEffect(cost = Costs.pay.OwnManaCost, suffer = SacrificeSelfEffect)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "72"
        artist = "Thomas Gianni"
        imageUri = "https://cards.scryfall.io/normal/front/e/3/e37cd150-1064-43b7-919b-8922d8a18f21.jpg"
    }
}
