// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pcy.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Searing Wind
 * {8}{R}
 * Instant
 * Searing Wind deals 10 damage to any target.
 */
val SearingWind = card("Searing Wind") {
    manaCost = "{8}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Searing Wind deals 10 damage to any target."
    spell {
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(10, t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "103"
        artist = "John Matson"
        flavorText = "\"The first wind of ascension is Forger, burning away impurity.\"\n—Keld Triumphant"
        imageUri = "https://cards.scryfall.io/normal/front/7/b/7b761f97-3690-497a-b6ab-c71f61b8e841.jpg"
    }
}
