// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pcy.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Troubled Healer
 * {2}{W}
 * Creature — Human Cleric
 * 1/2
 * Sacrifice a land: Prevent the next 2 damage that would be dealt to any target this turn.
 */
val TroubledHealer = card("Troubled Healer") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Cleric"
    oracleText = "Sacrifice a land: Prevent the next 2 damage that would be dealt to any target this turn."
    power = 1
    toughness = 2
    activatedAbility {
        cost = Costs.Sacrifice(GameObjectFilter.Land)
        val t = target("target", AnyTarget())
        effect = Effects.PreventNextDamage(2, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "27"
        artist = "Terese Nielsen"
        flavorText = "\"Which is worse: nothing to defend, or no one to defend it?\""
        imageUri = "https://cards.scryfall.io/normal/front/5/4/54407ba7-6671-42a9-acbe-8a1104c7166c.jpg"
    }
}
