package com.wingedsheep.mtg.sets.definitions.mh3.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.dsl.times
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.effects.CardSource
import com.wingedsheep.sdk.scripting.effects.ManaRestriction
import com.wingedsheep.sdk.scripting.references.Player

/**
 * Rosheen, Roaring Prophet — Modern Horizons 3 #202
 * {2}{R}{G} · Legendary Creature — Giant Shaman · 4/4
 *
 * When Rosheen enters, mill six cards. You may put a card with {X} in its mana cost from among them
 * into your hand.
 * {T}: Reveal any number of cards with {X} in their mana cost in your hand. Add {C}{C} for each card
 * revealed this way. Spend this mana only on costs that contain {X}.
 *
 * The mana is [ManaRestriction.CostsContainingXOnly]: a spell or an activated ability whose mana cost
 * contains {X}. The reveal is a choose-any-number over the hand's X cards (zero allowed), and the
 * amount is twice the chosen count.
 */
val RosheenRoaringProphet = card("Rosheen, Roaring Prophet") {
    manaCost = "{2}{R}{G}"
    colorIdentity = "RG"
    typeLine = "Legendary Creature — Giant Shaman"
    power = 4
    toughness = 4
    oracleText = "When Rosheen enters, mill six cards. You may put a card with {X} in its mana cost from " +
        "among them into your hand.\n" +
        "{T}: Reveal any number of cards with {X} in their mana cost in your hand. Add {C}{C} for each " +
        "card revealed this way. Spend this mana only on costs that contain {X}."

    triggeredAbility {
        trigger = Triggers.self.enters()
        effect = Effects.Pipeline {
            val milled = mill(6)
            val kept = chooseUpTo(
                1,
                from = milled,
                filter = GameObjectFilter.Any.hasXInManaCost(),
                showAllCards = true,
                prompt = "You may put a card with {X} in its mana cost into your hand",
                selectedLabel = "Put in hand",
                remainderLabel = "Leave in graveyard"
            )
            toHand(kept)
        }
        description = "When Rosheen enters, mill six cards. You may put a card with {X} in its mana cost " +
            "from among them into your hand."
    }

    activatedAbility {
        cost = Costs.Tap
        effect = Effects.Pipeline {
            val xCards = gather(CardSource.FromZone(Zone.HAND, Player.You, GameObjectFilter.Any.hasXInManaCost()))
            val revealed = chooseAnyNumber(
                xCards,
                prompt = "Reveal any number of cards with {X} in their mana cost",
                name = "rosheenRevealed",
            )
            reveal(revealed)
            run(
                Effects.AddColorlessMana(
                    revealed.count * 2,
                    ManaRestriction.CostsContainingXOnly
                )
            )
        }
        manaAbility = true
        timing = TimingRule.ManaAbility
        description = "{T}: Reveal any number of cards with {X} in their mana cost in your hand. Add {C}{C} " +
            "for each card revealed this way. Spend this mana only on costs that contain {X}."
    }

    metadata {
        rarity = Rarity.RARE
        collectorNumber = "202"
        artist = "Fang Xinyu"
        imageUri = "https://cards.scryfall.io/normal/front/b/5/b5ac88b2-a92e-4a12-9ba3-5a4b8cdb58dc.jpg?1783911245"
        ruling("2024-06-07", "You can spend mana generated with Rosheen's last ability on any part of a cost that contains {X}. You're not limited to spending it only on the {X} part.")
        ruling("2024-06-07", "You don't have to spend all of the mana generated with Rosheen's last ability on the same cost.")
        ruling("2024-06-07", "You can use the mana generated with Rosheen's last ability in any cost you pay that includes {X}, including the mana costs of spells, activation costs, and even costs for special actions (such as morph). Any time you pay mana, that's a cost.")
        ruling("2024-06-07", "A \"cost that contains {X}\" may be a spell's total cost, an activated ability's cost, a suspend cost, or a cost you're asked to pay as part of the resolution of a spell or ability (such as Condescend). A spell's total cost includes either its mana cost (printed in the upper right corner) or its alternative cost (such as flashback), as well as any additional costs (such as kicker). If it's something you can spend mana on, it's a cost. If that cost includes the {X} symbol in it, you can spend mana generated by Rosheen on that cost.")
    }
}
