package com.wingedsheep.mtg.sets.definitions.mh3.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.effects.ManaRestriction

/**
 * Sage of the Unknowable — Modern Horizons 3 #68
 * {1}{U} · Creature — Human Wizard · 0/4
 *
 * {T}: Add {C}. Spend this mana only to cast a colorless spell or to activate an ability.
 *
 * `AnyOf(ColorlessSpellsOnly, AbilityActivationOnly)` — the ability half is any activated ability of
 * any source, per the ruling, not only abilities of colorless sources.
 */
val SageOfTheUnknowable = card("Sage of the Unknowable") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Human Wizard"
    power = 0
    toughness = 4
    oracleText = "{T}: Add {C}. Spend this mana only to cast a colorless spell or to activate an ability."

    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddColorlessMana(
            1,
            restriction = ManaRestriction.AnyOf(
                listOf(ManaRestriction.ColorlessSpellsOnly, ManaRestriction.AbilityActivationOnly)
            )
        )
        manaAbility = true
        timing = TimingRule.ManaAbility
        description = "{T}: Add {C}. Spend this mana only to cast a colorless spell or to activate an ability."
    }

    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "68"
        artist = "Josu Hernaiz"
        flavorText = "\"Someday, we will walk the Blind Eternities and see the truths that lie beyond the stifling veil of reality.\""
        imageUri = "https://cards.scryfall.io/normal/front/9/f/9f481ab3-ca6c-4a5c-aa32-d087464fc4da.jpg?1783911288"
        ruling(
            "2024-06-07",
            "The mana generated by Sage of the Unknowable's activated ability can be used to activate any " +
                "ability, not just abilities of colorless sources."
        )
    }
}
