// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fin.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.TriggerBinding
import com.wingedsheep.sdk.scripting.TriggeredAbility
import com.wingedsheep.sdk.scripting.effects.CreateTokenEffect
import com.wingedsheep.sdk.scripting.effects.SearchDestination
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Call the Mountain Chocobo
 * {3}{R}
 * Sorcery
 * Search your library for a Mountain card, reveal it, put it into your hand, then shuffle. Create a 2/2 green Bird creature token with "Whenever a land you control enters, this token gets +1/+0 until end of turn."
 * Flashback {5}{R} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val CallTheMountainChocobo = card("Call the Mountain Chocobo") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Search your library for a Mountain card, reveal it, put it into your hand, then shuffle. Create a 2/2 green Bird creature token with \"Whenever a land you control enters, this token gets +1/+0 until end of turn.\"\nFlashback {5}{R} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        effect = Effects.Composite(
            Patterns.Library.searchLibrary(
                filter = GameObjectFilter.Land.withSubtype(Subtype.MOUNTAIN),
                destination = SearchDestination.HAND,
                reveal = true
            ),
            CreateTokenEffect(
                power = 2,
                toughness = 2,
                colors = setOf(Color.GREEN),
                creatureTypes = setOf("Bird"),
                triggeredAbilities = listOf(
                    TriggeredAbility.create(
                        trigger = Triggers.entersBattlefield(
                            filter = GameObjectFilter.Land.youControl(),
                            binding = TriggerBinding.ANY
                        ).event,
                        binding = Triggers.entersBattlefield(
                            filter = GameObjectFilter.Land.youControl(),
                            binding = TriggerBinding.ANY
                        ).binding,
                        effect = Effects.ModifyStats(1, 0, EffectTarget.Self)
                    )
                )
            )
        )
    }
    keywordAbility(KeywordAbility.flashback("{5}{R}"))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "131"
        artist = "Randy Gallegos"
        imageUri = "https://cards.scryfall.io/normal/front/b/2/b2e1986c-2852-4843-bdc4-eddb727ba3d4.jpg"
    }
}
