// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fin.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TriggerBinding
import com.wingedsheep.sdk.scripting.TriggeredAbility
import com.wingedsheep.sdk.scripting.effects.CreateTokenEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Chocobo Racetrack
 * {3}{G}{G}
 * Artifact
 * Landfall — Whenever a land you control enters, create a 2/2 green Bird creature token with "Whenever a land you control enters, this token gets +1/+0 until end of turn."
 */
val ChocoboRacetrack = card("Chocobo Racetrack") {
    manaCost = "{3}{G}{G}"
    colorIdentity = "G"
    typeLine = "Artifact"
    oracleText = "Landfall — Whenever a land you control enters, create a 2/2 green Bird creature token with \"Whenever a land you control enters, this token gets +1/+0 until end of turn.\""
    triggeredAbility {
        trigger = Triggers.entersBattlefield(filter = GameObjectFilter.Land.youControl(), binding = TriggerBinding.ANY)
        effect = CreateTokenEffect(
            power = 2,
            toughness = 2,
            colors = setOf(Color.GREEN),
            creatureTypes = setOf("Bird"),
            triggeredAbilities = listOf(
                TriggeredAbility.create(
                    trigger = Triggers.entersBattlefield(
                        filter = GameObjectFilter.Land.youControl(),
                        binding = TriggerBinding.ANY
                    ).event,
                    binding = Triggers.entersBattlefield(
                        filter = GameObjectFilter.Land.youControl(),
                        binding = TriggerBinding.ANY
                    ).binding,
                    effect = Effects.ModifyStats(1, 0, EffectTarget.Self)
                )
            )
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "179"
        artist = "Bachzim"
        flavorText = "\"No matter how you make your bet, you win some and you lose some. It all comes down to skill and luck.\"\n—Racing expert"
        imageUri = "https://cards.scryfall.io/normal/front/1/5/1565813b-6912-42f4-bae0-22136a2d6a92.jpg"
    }
}
