// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fin.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.ChoiceType
import com.wingedsheep.sdk.scripting.EntersTapped
import com.wingedsheep.sdk.scripting.EntersWithChoice
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Crossroads Village
 * Land — Town
 * This land enters tapped. As it enters, choose a color.
 * {T}: Add one mana of the chosen color.
 */
val CrossroadsVillage = card("Crossroads Village") {
    manaCost = ""
    colorIdentity = ""
    typeLine = "Land — Town"
    oracleText = "This land enters tapped. As it enters, choose a color.\n{T}: Add one mana of the chosen color."
    replacementEffect(EntersTapped())
    replacementEffect(EntersWithChoice(ChoiceType.COLOR))
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddManaOfChosenColor()
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "276"
        artist = "Hristo D. Chukov"
        flavorText = "\"You've got to destroy the Dreadnought!\"\n—Bafsk resident"
        imageUri = "https://cards.scryfall.io/normal/front/6/4/64db46d4-f91f-49cc-971c-b8e19f0c4ea9.jpg"
    }
}
