// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fin.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.EntersTapped
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Rabanastre, Royal City
 * Land — Town
 * This land enters tapped.
 * {T}: Add {R} or {W}.
 */
val RabanastreRoyalCity = card("Rabanastre, Royal City") {
    manaCost = ""
    colorIdentity = "WR"
    typeLine = "Land — Town"
    oracleText = "This land enters tapped.\n{T}: Add {R} or {W}."
    replacementEffect(EntersTapped())
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(Color.RED)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(Color.WHITE)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "287"
        artist = "Shahab Alizadeh"
        flavorText = "The town proper of Rabanastre is divided into four sections by the cardinal directions of the compass. The east and west are merchant districts, the streets lined with shops and stalls of every description."
        imageUri = "https://cards.scryfall.io/normal/front/c/4/c44c9bbe-f4c6-41cf-b3c3-b943f4011bc1.jpg"
    }
}
