// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fin.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Rosa, Resolute White Mage
 * {3}{W}
 * Legendary Creature — Human Noble Cleric
 * 2/3
 * Reach (This creature can block creatures with flying.)
 * At the beginning of combat on your turn, put a +1/+1 counter on target creature you control. It gains lifelink until end of turn. (Damage dealt by the creature also causes you to gain that much life.)
 */
val RosaResoluteWhiteMage = card("Rosa, Resolute White Mage") {
    manaCost = "{3}{W}"
    colorIdentity = "W"
    typeLine = "Legendary Creature — Human Noble Cleric"
    oracleText = "Reach (This creature can block creatures with flying.)\nAt the beginning of combat on your turn, put a +1/+1 counter on target creature you control. It gains lifelink until end of turn. (Damage dealt by the creature also causes you to gain that much life.)"
    power = 2
    toughness = 3
    keywords(Keyword.REACH)
    triggeredAbility {
        trigger = Triggers.BeginCombat
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.youControl()))
        effect = Effects.Composite(
            AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = t),
            Effects.GrantKeyword(Keyword.LIFELINK, t)
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "555"
        artist = "Christian Angel"
        imageUri = "https://cards.scryfall.io/normal/front/c/4/c44e0ad6-9f44-4e4c-8c3b-3ee99409a740.jpg"
    }
}
