// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fin.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TriggerBinding
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.events.DamageType
import com.wingedsheep.sdk.scripting.events.RecipientFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Ultimecia, Temporal Threat
 * {4}{U}{U}
 * Legendary Creature — Human Warlock
 * 4/4
 * When Ultimecia enters, tap all creatures your opponents control.
 * Whenever a creature you control deals combat damage to a player, draw a card.
 */
val UltimeciaTemporalThreat = card("Ultimecia, Temporal Threat") {
    manaCost = "{4}{U}{U}"
    colorIdentity = "U"
    typeLine = "Legendary Creature — Human Warlock"
    oracleText = "When Ultimecia enters, tap all creatures your opponents control.\nWhenever a creature you control deals combat damage to a player, draw a card."
    power = 4
    toughness = 4
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature.opponentControls()),
            Effects.Tap(EffectTarget.Self)
        )
    }
    triggeredAbility {
        trigger = Triggers.dealsDamage(
            DamageType.Combat,
            RecipientFilter.AnyPlayer,
            sourceFilter = GameObjectFilter.Creature.youControl(),
            binding = TriggerBinding.ANY
        )
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "556"
        artist = "Bachzim"
        flavorText = "\"Ultimecia is a fearful sorceress. Her heart is filled with anger and hate.\"\n—Edea Kramer"
        imageUri = "https://cards.scryfall.io/normal/front/b/6/b64e4475-f1c6-4d85-b42f-6d84d06855bb.jpg"
    }
}
