// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.xln.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter


/**
 * Makeshift Munitions
 * {1}{R}
 * Enchantment
 * {1}, Sacrifice an artifact or creature: This enchantment deals 1 damage to any target.
 */
val MakeshiftMunitions = card("Makeshift Munitions") {
    manaCost = "{1}{R}"
    colorIdentity = "R"
    typeLine = "Enchantment"
    oracleText = "{1}, Sacrifice an artifact or creature: This enchantment deals 1 damage to any target."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}"), Costs.Sacrifice(GameObjectFilter.Artifact or GameObjectFilter.Creature))
        val t = target(Targets.Any)
        effect = Effects.DealDamage(1, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "151"
        artist = "Filip Burburan"
        flavorText = "\"Grease up a firecannon good and proper with dinosaur-liver oil, and it'll shoot just about anything.\""
        imageUri = "https://cards.scryfall.io/normal/front/6/5/65689442-e679-4844-91a8-f6a39a7c1f9b.jpg"
    }
}
