// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.atq.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Sage of Lat-Nam
 * {1}{U}
 * Creature — Human Artificer
 * 1/2
 * {T}, Sacrifice an artifact: Draw a card.
 */
val SageOfLatNam = card("Sage of Lat-Nam") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Human Artificer"
    oracleText = "{T}, Sacrifice an artifact: Draw a card."
    power = 1
    toughness = 2
    activatedAbility {
        cost = Costs.Composite(Costs.Tap, Costs.Sacrifice(GameObjectFilter.Artifact))
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "13"
        artist = "Pete Venters"
        imageUri = "https://cards.scryfall.io/normal/front/b/4/b4ff60ce-073c-46b8-807c-8b40467b960c.jpg"
    }
}
