// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.atq.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Wall of Spears
 * {3}
 * Artifact Creature — Wall
 * 2/3
 * Defender (This creature can't attack.)
 * First strike
 */
val WallOfSpears = card("Wall of Spears") {
    manaCost = "{3}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Wall"
    oracleText = "Defender (This creature can't attack.)\nFirst strike"
    power = 2
    toughness = 3
    keywords(Keyword.DEFENDER, Keyword.FIRST_STRIKE)
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "77"
        artist = "Sandra Everingham"
        flavorText = "Even the most conservative generals revised their tactics after the Battle of Sarinth, during which a handful of peasant-pikemen held off a trio of rampaging Craw Wurms."
        imageUri = "https://cards.scryfall.io/normal/front/b/1/b1dda179-c49a-4995-ba5a-db93ac43dbe7.jpg"
    }
}
