// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.soi.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.ZonePlacement
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Epitaph Golem
 * {5}
 * Artifact Creature — Golem
 * 3/5
 * {2}: Put target card from your graveyard on the bottom of your library.
 */
val EpitaphGolem = card("Epitaph Golem") {
    manaCost = "{5}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Golem"
    oracleText = "{2}: Put target card from your graveyard on the bottom of your library."
    power = 3
    toughness = 5
    activatedAbility {
        cost = Costs.Mana("{2}")
        val t = target(
            "target",
            TargetObject(filter = TargetFilter(GameObjectFilter.Any.ownedByYou(), zone = Zone.GRAVEYARD))
        )
        effect = Effects.Move(t, Zone.LIBRARY, ZonePlacement.Bottom)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "254"
        artist = "Adam Paquette"
        flavorText = "Many names and many memories bound together in grim purpose."
        imageUri = "https://cards.scryfall.io/normal/front/9/3/937aaed7-d9ad-45e0-915c-df61316c606a.jpg"
    }
}
