// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.TargetCreature
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Ben-Ben, Akki Hermit
 * {2}{R}{R}
 * Legendary Creature — Goblin Shaman
 * 1/1
 * {T}: Ben-Ben deals damage to target attacking creature equal to the number of untapped Mountains you control.
 */
val BenBenAkkiHermit = card("Ben-Ben, Akki Hermit") {
    manaCost = "{2}{R}{R}"
    colorIdentity = "R"
    typeLine = "Legendary Creature — Goblin Shaman"
    oracleText = "{T}: Ben-Ben deals damage to target attacking creature equal to the number of untapped Mountains you control."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.attacking()))
        effect = DealDamageEffect(
            DynamicAmount.AggregateBattlefield(
                Player.You,
                GameObjectFilter.Land.withSubtype(Subtype.MOUNTAIN).untapped()
            ),
            t
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "157"
        artist = "Greg Staples"
        flavorText = "Some akki thought of Ben-Ben as a kami of trickery in disguise. They hunted for him in the maze of warrens, often falling prey to his traps."
        imageUri = "https://cards.scryfall.io/normal/front/d/7/d7c015a6-4d7d-421b-84fa-30bf070cff83.jpg"
    }
}
