// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Kami of Ancient Law
 * {1}{W}
 * Creature — Spirit
 * 2/2
 * Sacrifice this creature: Destroy target enchantment.
 */
val KamiOfAncientLaw = card("Kami of Ancient Law") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Spirit"
    oracleText = "Sacrifice this creature: Destroy target enchantment."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.SacrificeSelf
        val t = target("target", TargetPermanent(filter = TargetFilter.Enchantment))
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "21"
        artist = "Mark Tedin"
        flavorText = "\"Duty and law are the foundation on which civilization stands. They must not fall, for when they do, they take everything with them.\"\n—Lord Konda"
        imageUri = "https://cards.scryfall.io/normal/front/b/7/b7cb7fdc-fa47-4485-b268-7c2ddff28568.jpg"
    }
}
