// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Kitsune Diviner
 * {W}
 * Creature — Fox Cleric
 * 0/1
 * {T}: Tap target Spirit.
 */
val KitsuneDiviner = card("Kitsune Diviner") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Creature — Fox Cleric"
    oracleText = "{T}: Tap target Spirit."
    power = 0
    toughness = 1
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", TargetCreature(filter = TargetFilter(GameObjectFilter.Creature.withSubtype("Spirit"))))
        effect = Effects.Tap(t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "26"
        artist = "Pete Venters"
        flavorText = "She who once led prayers honoring the kami adapted to use her influence to stay them."
        imageUri = "https://cards.scryfall.io/normal/front/c/5/c50fb007-d1fd-4b61-91c3-4863e40472ed.jpg"
    }
}
