// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Lantern Kami
 * {W}
 * Creature — Spirit
 * 1/1
 * Flying
 */
val LanternKami = card("Lantern Kami") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Creature — Spirit"
    oracleText = "Flying"
    power = 1
    toughness = 1
    keywords(Keyword.FLYING)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "32"
        artist = "John Avon"
        flavorText = "\"Snuffing the light of a lantern without saying a small prayer is bad luck. Though its flame can only singe, its soul can repeatedly visit misery on one's house.\"\n—Teachings of Eight-and-a-Half-Tails"
        imageUri = "https://cards.scryfall.io/normal/front/9/9/99625787-f184-48a5-a678-e30b7024c7bb.jpg"
    }
}
