// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.CantBlock


/**
 * Nezumi Cutthroat
 * {1}{B}
 * Creature — Rat Warrior
 * 2/1
 * Fear (This creature can't be blocked except by artifact creatures and/or black creatures.)
 * This creature can't block.
 */
val NezumiCutthroat = card("Nezumi Cutthroat") {
    manaCost = "{1}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Rat Warrior"
    oracleText = "Fear (This creature can't be blocked except by artifact creatures and/or black creatures.)\nThis creature can't block."
    power = 2
    toughness = 1
    keywords(Keyword.FEAR)
    staticAbility {
        ability = CantBlock()
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "128"
        artist = "Carl Critchlow"
        flavorText = "\"These nezumi, they disgust me. The things they will do for money no other thinking creature would consider. This, of course, makes them useful beyond words.\"\n—Meloku the Clouded Mirror"
        imageUri = "https://cards.scryfall.io/normal/front/1/6/166af8cd-9690-4741-ade3-5d5f9723c431.jpg"
    }
}
