// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Reach Through Mists
 * {U}
 * Instant — Arcane
 * Draw a card.
 */
val ReachThroughMists = card("Reach Through Mists") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Instant — Arcane"
    oracleText = "Draw a card."
    spell {
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "81"
        artist = "Anthony S. Waters"
        flavorText = "\"Know one part of the name, obsession begins. Know two parts, paranoia sets in. Know three parts, madness descends. Know all, and only the kami know what will become of you.\"\n—Lady Azami"
        imageUri = "https://cards.scryfall.io/normal/front/9/d/9d63a2cd-dd67-4692-9baf-520ebf6ab331.jpg"
    }
}
