// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.CounterEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetSpell


/**
 * Thoughtbind
 * {2}{U}
 * Instant
 * Counter target spell with mana value 4 or less.
 */
val Thoughtbind = card("Thoughtbind") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Counter target spell with mana value 4 or less."
    spell {
        val t = target("target", TargetSpell(filter = TargetFilter.SpellOnStack.manaValueAtMost(4)))
        effect = CounterEffect()
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "96"
        artist = "Rob Alexander"
        flavorText = "\"As the rest of the mortal world waged war, Lady Azami and her students invaded tomes of knowledge. Their search yielded spells critical in the fight.\"\n—Observations of the Kami War"
        imageUri = "https://cards.scryfall.io/normal/front/7/9/7919cf41-67bb-4dc4-90de-cf3fa2096c2e.jpg"
    }
}
