// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Time of Need
 * {1}{G}
 * Sorcery
 * Search your library for a legendary creature card, reveal it, put it into your hand, then shuffle.
 */
val TimeOfNeed = card("Time of Need") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Sorcery"
    oracleText = "Search your library for a legendary creature card, reveal it, put it into your hand, then shuffle."
    spell {
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Creature.legendary(),
            destination = SearchDestination.HAND,
            reveal = true
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "247"
        artist = "Dany Orizio"
        flavorText = "\"When the kumo attacked the monks' sacred shrine, a mournful toll for help echoed through the forest. Thus began the Battle of Silk, which would last six years.\"\n—Great Battles of Kamigawa"
        imageUri = "https://cards.scryfall.io/normal/front/5/1/514577a5-c7ae-4cfc-872a-e3786d78a6c3.jpg"
    }
}
