// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GrantKeyword


/**
 * Vigilance
 * {W}
 * Enchantment — Aura
 * Enchant creature
 * Enchanted creature has vigilance. (Attacking doesn't cause it to tap.)
 */
val Vigilance = card("Vigilance") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Enchantment — Aura"
    oracleText = "Enchant creature\nEnchanted creature has vigilance. (Attacking doesn't cause it to tap.)"
    auraTarget = Targets.Creature
    staticAbility {
        ability = GrantKeyword(Keyword.VIGILANCE)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "49"
        artist = "Tsutomu Kawade"
        flavorText = "\"Put a spear in a peasant's hands, and you have an expendable troop. Put a purpose in his heart, and you win a warrior.\"\n—Sensei Golden-Tail"
        imageUri = "https://cards.scryfall.io/normal/front/d/2/d24dc353-abc9-430a-a7f5-5da3b38cd411.jpg"
    }
}
