// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.TargetPlayer


/**
 * Waking Nightmare
 * {2}{B}
 * Sorcery — Arcane
 * Target player discards two cards.
 */
val WakingNightmare = card("Waking Nightmare") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Sorcery — Arcane"
    oracleText = "Target player discards two cards."
    spell {
        val t = target("target", TargetPlayer())
        effect = Patterns.Hand.discardCards(2, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "149"
        artist = "Mitch Cotie"
        flavorText = "\"Once each year, the oni and other evil spirits paraded through villages to disturb mortals' sleep. During the war, this parade became a nightly event.\"\n—Observations of the Kami War"
        imageUri = "https://cards.scryfall.io/normal/front/1/b/1b892f31-816e-47c0-98b9-d71008bb6af4.jpg"
    }
}
