// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Wandering Ones
 * {U}
 * Creature — Spirit
 * 1/1
 */
val WanderingOnes = card("Wandering Ones") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Creature — Spirit"
    power = 1
    toughness = 1
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "100"
        artist = "Heather Hudson"
        flavorText = "\"I saw them once, when I was a child. They led me to my parents' arms when I was lost. Why have they abandoned me now? Why won't they take me home again?\"\n—Unnamed beggar"
        imageUri = "https://cards.scryfall.io/normal/front/8/f/8f973d6b-4a34-4b0e-b092-ead05bf2e535.jpg"
    }
}
