// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.leg.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Moss Monster
 * {3}{G}{G}
 * Creature — Elemental
 * 3/6
 */
val MossMonster = card("Moss Monster") {
    manaCost = "{3}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Elemental"
    power = 3
    toughness = 6
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "195"
        artist = "Jesper Myrfors"
        flavorText = "After the battle, an eerie silence gripped the forest. The losers' remains were lightly dusted with green."
        imageUri = "https://cards.scryfall.io/normal/front/9/9/9903c043-9a7a-4994-b532-136d4c46edfd.jpg"
    }
}
