// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.leg.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.ActivationRestriction
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Vampire Bats
 * {B}
 * Creature — Bat
 * 0/1
 * Flying (This creature can't be blocked except by creatures with flying or reach.)
 * {B}: This creature gets +1/+0 until end of turn. Activate no more than twice each turn.
 */
val VampireBats = card("Vampire Bats") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Creature — Bat"
    oracleText = "Flying (This creature can't be blocked except by creatures with flying or reach.)\n{B}: This creature gets +1/+0 until end of turn. Activate no more than twice each turn."
    power = 0
    toughness = 1
    keywords(Keyword.FLYING)
    activatedAbility {
        cost = Costs.Mana("{B}")
        restrictions = listOf(ActivationRestriction.MaxPerTurn(2))
        effect = Effects.ModifyStats(1, 0, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "125"
        artist = "Anson Maddocks"
        flavorText = "\"For something is amiss or out of place/ When mice with wings can wear a human face.\" —Theodore Roethke, \"The Bat\""
        imageUri = "https://cards.scryfall.io/normal/front/6/a/6a6a6f50-7b86-461e-80a7-e35d0e7cf52f.jpg"
    }
}
