// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Alpha Myr
 * {2}
 * Artifact Creature — Myr
 * 2/1
 */
val AlphaMyr = card("Alpha Myr") {
    manaCost = "{2}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Myr"
    power = 2
    toughness = 1
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "142"
        artist = "Dany Orizio"
        flavorText = "First to charge, first to fight."
        imageUri = "https://cards.scryfall.io/normal/front/f/3/f3f792d7-75be-429e-8f62-0b563b103642.jpg"
    }
}
