// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Auriok Transfixer
 * {W}
 * Creature — Human Scout
 * 1/1
 * {W}, {T}: Tap target artifact.
 */
val AuriokTransfixer = card("Auriok Transfixer") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Scout"
    oracleText = "{W}, {T}: Tap target artifact."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{W}"), Costs.Tap)
        val t = target("target", TargetPermanent(filter = TargetFilter.Artifact))
        effect = Effects.Tap(t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "5"
        artist = "Stephen Tappin"
        flavorText = "\"My grandfather knew enough spells to fill a hundred scrolls. Nowadays, if a spell cannot fight the levelers, it is not even taught to our young.\""
        imageUri = "https://cards.scryfall.io/normal/front/9/f/9f5c3f22-f228-4503-9d35-ee1b36a46ef0.jpg"
    }
}
