// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.EntersTapped
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Cloudpost
 * Land — Locus
 * This land enters tapped.
 * {T}: Add {C} for each Locus on the battlefield.
 */
val Cloudpost = card("Cloudpost") {
    manaCost = ""
    colorIdentity = ""
    typeLine = "Land — Locus"
    oracleText = "This land enters tapped.\n{T}: Add {C} for each Locus on the battlefield."
    replacementEffect(EntersTapped())
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddColorlessMana(
            DynamicAmount.AggregateBattlefield(Player.Each, GameObjectFilter.Land.withSubtype("Locus"))
        )
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "280"
        artist = "Martina Pilcerova"
        flavorText = "\"He watches from above. He watches from below. He watches from within.\"\n—Inscription on Tel-Jilad, the Tree of Tales"
        imageUri = "https://cards.scryfall.io/normal/front/2/f/2f28ecdc-a4f0-4327-a78c-340be41555ee.jpg"
    }
}
