// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Fabricate
 * {2}{U}
 * Sorcery
 * Search your library for an artifact card, reveal it, put it into your hand, then shuffle.
 */
val Fabricate = card("Fabricate") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Search your library for an artifact card, reveal it, put it into your hand, then shuffle."
    spell {
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Artifact,
            destination = SearchDestination.HAND,
            reveal = true
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "35"
        artist = "Glen Angus"
        flavorText = "\"The secret to invention is to see something in your mind, then find where it hides in the world.\""
        imageUri = "https://cards.scryfall.io/normal/front/a/7/a742e23c-1991-4dce-b670-dea92a1cf4ec.jpg"
    }
}
