// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Lumengrid Warden
 * {1}{U}
 * Creature — Human Wizard
 * 1/3
 */
val LumengridWarden = card("Lumengrid Warden") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Human Wizard"
    power = 1
    toughness = 3
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "41"
        artist = "Matt Thompson"
        flavorText = "The Neurok, like the vedalken, are on a constant quest for knowledge. It is their currency, their trade, their life."
        imageUri = "https://cards.scryfall.io/normal/front/4/4/44aadd54-6e83-4bcf-9760-16479d919a56.jpg"
    }
}
