// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GrantKeyword


/**
 * Neurok Hoversail
 * {1}
 * Artifact — Equipment
 * Equipped creature has flying.
 * Equip {2} ({2}: Attach to target creature you control. Equip only as a sorcery.)
 */
val NeurokHoversail = card("Neurok Hoversail") {
    manaCost = "{1}"
    colorIdentity = ""
    typeLine = "Artifact — Equipment"
    oracleText = "Equipped creature has flying.\nEquip {2} ({2}: Attach to target creature you control. Equip only as a sorcery.)"
    staticAbility {
        ability = GrantKeyword(Keyword.FLYING)
    }
    equipAbility("{2}")
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "218"
        artist = "Alan Pollack"
        imageUri = "https://cards.scryfall.io/normal/front/0/f/0fa5790b-5388-4bf9-9caa-44d8cbb64708.jpg"
    }
}
