// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Predator's Strike
 * {1}{G}
 * Instant
 * Target creature gets +3/+3 and gains trample until end of turn. (It can deal excess combat damage to the player or planeswalker it's attacking.)
 */
val PredatorsStrike = card("Predator's Strike") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Target creature gets +3/+3 and gains trample until end of turn. (It can deal excess combat damage to the player or planeswalker it's attacking.)"
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Composite(
            Effects.ModifyStats(3, 3, t),
            Effects.GrantKeyword(Keyword.TRAMPLE, t)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "128"
        artist = "Tony Szczudlo"
        flavorText = "If you hear it coming, you're not its prey."
        imageUri = "https://cards.scryfall.io/normal/front/7/5/75e5bcc2-9203-4526-a9a9-fac6fd02a854.jpg"
    }
}
