// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Pyrite Spellbomb
 * {1}
 * Artifact
 * {R}, Sacrifice this artifact: It deals 2 damage to any target.
 * {1}, Sacrifice this artifact: Draw a card.
 */
val PyriteSpellbomb = card("Pyrite Spellbomb") {
    manaCost = "{1}"
    colorIdentity = "R"
    typeLine = "Artifact"
    oracleText = "{R}, Sacrifice this artifact: It deals 2 damage to any target.\n{1}, Sacrifice this artifact: Draw a card."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{R}"), Costs.SacrificeSelf)
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(2, t)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}"), Costs.SacrificeSelf)
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "232"
        artist = "Jim Nelson"
        flavorText = "\"Melt that which was never frozen.\"\n—Spellbomb inscription"
        imageUri = "https://cards.scryfall.io/normal/front/9/7/97b9bab9-12ee-4da5-9d53-d0b82d9279cd.jpg"
    }
}
