// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Talisman of Dominance
 * {2}
 * Artifact
 * {T}: Add {C}.
 * {T}: Add {U} or {B}. This artifact deals 1 damage to you.
 */
val TalismanOfDominance = card("Talisman of Dominance") {
    manaCost = "{2}"
    colorIdentity = "UB"
    typeLine = "Artifact"
    oracleText = "{T}: Add {C}.\n{T}: Add {U} or {B}. This artifact deals 1 damage to you."
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddColorlessMana(1)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.Composite(
            Effects.AddMana(Color.BLUE),
            DealDamageEffect(1, EffectTarget.PlayerRef(Player.You))
        )
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.Composite(
            Effects.AddMana(Color.BLACK),
            DealDamageEffect(1, EffectTarget.PlayerRef(Player.You))
        )
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "253"
        artist = "Mike Dringenberg"
        imageUri = "https://cards.scryfall.io/normal/front/9/9/991037a2-fea2-49f5-8ace-ebbf9f678cff.jpg"
    }
}
