// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Talisman of Unity
 * {2}
 * Artifact
 * {T}: Add {C}.
 * {T}: Add {G} or {W}. This artifact deals 1 damage to you.
 */
val TalismanOfUnity = card("Talisman of Unity") {
    manaCost = "{2}"
    colorIdentity = "WG"
    typeLine = "Artifact"
    oracleText = "{T}: Add {C}.\n{T}: Add {G} or {W}. This artifact deals 1 damage to you."
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddColorlessMana(1)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.Composite(
            Effects.AddMana(Color.GREEN),
            DealDamageEffect(1, EffectTarget.PlayerRef(Player.You))
        )
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.Composite(
            Effects.AddMana(Color.WHITE),
            DealDamageEffect(1, EffectTarget.PlayerRef(Player.You))
        )
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "257"
        artist = "Mike Dringenberg"
        imageUri = "https://cards.scryfall.io/normal/front/d/6/d6cc8a5a-b98b-4758-a168-bf2ef738fb05.jpg"
    }
}
