// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Tower of Fortunes
 * {4}
 * Artifact
 * {8}, {T}: Draw four cards.
 */
val TowerOfFortunes = card("Tower of Fortunes") {
    manaCost = "{4}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{8}, {T}: Draw four cards."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{8}"), Costs.Tap)
        effect = DrawCardsEffect(4)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "267"
        artist = "Matt Cavotta"
        flavorText = "The ur-golem etchings begin by celebrating Mirrodin's creator, a golem of almost limitless power. They end by cursing its protector, a being called Memnarch."
        imageUri = "https://cards.scryfall.io/normal/front/4/3/433bab44-b644-4e77-a187-bd924d21e91f.jpg"
    }
}
