// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Tree of Tales
 * Artifact Land
 * {T}: Add {G}.
 */
val TreeOfTales = card("Tree of Tales") {
    manaCost = ""
    colorIdentity = "G"
    typeLine = "Artifact Land"
    oracleText = "{T}: Add {G}."
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(Color.GREEN)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "285"
        artist = "John Avon"
        flavorText = "Tel-Jilad, sanctum of the ancient trolls, keepers of the secret of Mirrodin's origin."
        imageUri = "https://cards.scryfall.io/normal/front/9/4/94db07aa-43d3-41b5-924e-60f1756b9c69.jpg"
    }
}
