// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Vault of Whispers
 * Artifact Land
 * {T}: Add {B}.
 */
val VaultOfWhispers = card("Vault of Whispers") {
    manaCost = ""
    colorIdentity = "B"
    typeLine = "Artifact Land"
    oracleText = "{T}: Add {B}."
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(Color.BLACK)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "286"
        artist = "Rob Alexander"
        flavorText = "Ish Sah, den of the warlord Geth, commander of countless nim."
        imageUri = "https://cards.scryfall.io/normal/front/7/3/73866487-33f4-4f64-b100-2c4ddadcd74e.jpg"
    }
}
