// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.CantBeBlockedByMoreThan
import com.wingedsheep.sdk.scripting.GrantKeyword


/**
 * Vorrac Battlehorns
 * {2}
 * Artifact — Equipment
 * Equipped creature has trample and can't be blocked by more than one creature.
 * Equip {1} ({1}: Attach to target creature you control. Equip only as a sorcery.)
 */
val VorracBattlehorns = card("Vorrac Battlehorns") {
    manaCost = "{2}"
    colorIdentity = ""
    typeLine = "Artifact — Equipment"
    oracleText = "Equipped creature has trample and can't be blocked by more than one creature.\nEquip {1} ({1}: Attach to target creature you control. Equip only as a sorcery.)"
    staticAbility {
        ability = GrantKeyword(Keyword.TRAMPLE)
    }
    staticAbility {
        ability = CantBeBlockedByMoreThan(maxBlockers = 1)
    }
    equipAbility("{1}")
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "271"
        artist = "David Martin"
        imageUri = "https://cards.scryfall.io/normal/front/b/1/b1b19949-90c9-46f1-85d4-d6eda0b7977e.jpg"
    }
}
